import type { Language } from "@/components/LanguageProvider";

const en = {
  appNavigation: { navigation: "Primary navigation", dashboard: "Dashboard", transactions: "Transactions", budgets: "Budgets", insights: "AI Insights", goals: "Goals", investments: "Investments", settings: "Settings", help: "Help", logout: "Logout", theme: "Appearance", darkTheme: "Use dark theme", lightTheme: "Use light theme" },
  appDashboard: {
    welcome: "Welcome,", welcomeBack: "Welcome back,", neutralName: "there", today: "Today", month: "Month", date: "Date", profilePhoto: "Profile photo",
    spendingTitle: "Where did your money go?", spendingAttentionTitle: "Shopping needs attention", spendingAttentionDescription: "It is your largest variable expense this month.",
    availableToSpend: "Available to spend", safe: "Safe", availableDescription: "You can use this amount without compromising bills and goals.", untilDate: "Until 31 Aug", viewCalculation: "View calculation →",
    income: "Income", expenses: "Expenses", accountBalance: "Account balance", versusLastMonth: "vs last month", totalThisMonth: "Total this month", totalConnected: "Total connected", viewAccounts: "View accounts →", hideValues: "Hide financial values", showValues: "Show financial values",
    goalsStatus: "Goals status", viewAll: "View all →", viewAllGoals: "View all goals", mainGoal: "Main goal", italyTrip: "Trip to Italy", onSchedule: "On schedule", ofAmount: "of €6,000", forecastMay2028: "Forecast: May 2028",
    nextBestAction: "Next best action", opportunityDetected: "OPPORTUNITY DETECTED", freePerMonth: "Free up €100/month", reduceFood: "Reduce €25/week on food.", goalImpact: "Goal impact", threeMonthsEarlier: "≈ 3 months earlier", tripPlan: "Trip • keeping the rest of the plan", applyPlan: "Apply plan", seeHow: "See how →",
    upcomingBills: "Upcoming bills", untilSep1: "until 01 Sep", viewCalendar: "View calendar →", monthStatus: "Month status", onTrack: "On track",
    monthStatusDescription: "You used 59.7% of your income and there are still 9 days until the next payment. Food is above the expected pace, but the month can still close within plan.", viewDiagnosis: "View diagnosis",
    total: "Total", bills: { internet: "Internet", energy: "Energy", rent: "Rent", aug27: "27 Aug", aug29: "29 Aug", sep1: "01 Sep" }, categories: { rent: "Rent", supermarket: "Supermarket", other: "Other", housing: "Housing", food: "Food", transportation: "Transportation", leisure: "Leisure", health: "Health", shopping: "Shopping" },
  },
  financialFlow: {
    pageTitle: "Financial Flow", pageDescription: "Analyze your balance, income and expenses in detail.", title: "Your financial flow", balance: "Balance", income: "Income", expenses: "Expenses", periodSummary: "Period summary",
    availableBalance: "Available balance", savings: "Savings", salary: "Salary", business: "Business", food: "Food", versusPreviousPeriod: "vs previous period", versusLastMonth: "vs last month",
    lastSevenDaysBalance: "Available balance · last 7 days", lastSevenDaysIncome: "Income · last 7 days", lastSevenDaysExpenses: "Expenses · last 7 days", averagePerDay: "Average / day",
    barView: "Bar view", distributionView: "Distribution view", trendView: "Trend view", currentDistribution: "current distribution", account: "Account", category: "Category",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    labels: { accountBalance: "Account balance", accounts: "5 accounts", mainAccount: "Main account", investments: "Investments", wallet: "Wallet", totalBalance: "Total balance", inPeriod: "in the period", largestIncome: "Largest income", sources: "5 sources", freelanceProjects: "Freelance / Projects", other: "Other", totalIncome: "Total income", largestCategory: "Largest category", homeShare: "Home · 36%", categories: "Categories", totalExpenses: "Total expenses", fiveCategories: "5 categories", housing: "Housing", transportation: "Transportation", subscriptions: "Subscriptions", leisure: "Leisure" },
  },
  appTransactions: {
    eyebrow: "TRANSACTIONS", title: "Transactions", description: "See what changed and how each expense impacts your month.", search: "Search transaction", month: "Month", newTransaction: "New transaction", avatar: "User avatar",
    close: "Close", modalDescription: "Add a manual transaction to your account.", descriptionField: "Description", value: "Amount", category: "Category", addTransaction: "Add transaction",
    filters: ["August 2026", "All categories", "All payments", "All sources", "Most recent"], movements: "Transactions", newLastSevenDays: "7 new in the last 7 days", monthlySpend: "Monthly spend", incomeUsage: "59.7% of income • +8.7% vs Jul", variableSpendRising: "Variable spending rising", shopping: "Shopping", largestVariableExpense: "€134.60 • largest variable expense", availableToSpend: "Available to spend", protectedAmount: "Until 31 Aug • bills and goals protected",
    augustTransactions: "August transactions", found: "45 transactions found", columns: ["Description / Merchant", "Category", "Payment", "Date", "Source", "Amount", "Actions", "Delete"], empty: "No transactions found.", showing: "Showing 1–7 of 45 transactions", actionsFor: "Actions for", delete: "Delete",
    patternDetected: "Pattern detected", patternBadge: "5× in 3 days", patternCopy: "Supermarket appeared 5 times in the last 3 days.", related: "View related transactions →", goalImpact: "Goal impact", trip: "TRIP", impactCopy: "Shopping totals €134.60; at the current pace, Trip may be delayed by ~12 days.", viewGoalImpact: "View goal impact →",
    labels: { subscriptions: "Subscriptions", supermarket: "Supermarket", coffee: "Coffee", card: "Card", statement: "Statement", manual: "Manual" },
  },
  appBudgets: {
    eyebrow: "BUDGETS", title: "Budgets", description: "Track spending pace and adjust before compromising your goals.", search: "Search budgets", month: "Month", selectMonth: "Select month", newBudget: "New budget", close: "Close", modalDescription: "Set a monthly limit for a category.", category: "Category", monthlyLimit: "Monthly limit", addBudget: "Add budget",
    planned: "Planned budget", plannedDetail: "August · 11 planned categories", spent: "Spent so far", spentDetail: "73.3% used · 61% of the month elapsed", forecast: "Closing forecast", forecastDetail: "≈ €95 above plan at the current pace", needsAction: "Needs action", needsActionDetail: "Shopping · Coffee · Subscriptions",
    yourBudgets: "Your budgets", categoriesPeriod: "11 categories · August 2026", columns: ["Category", "Budget", "Spent", "Remaining", "Progress", "Status", "Actions"], empty: "No budgets found.", addCategory: "+ Add category", actionsFor: "Actions for", editLimit: "Edit limit",
    statuses: { onPlan: "On plan", inControl: "In control", attention: "Attention", nearLimit: "Near limit", exceeded: "Exceeded" },
    nextBestAction: "Next best action", priority: "PRIORITY", recover: "Recover €34.60", recoverCopy: "Shopping is already over the limit. Reduce ~€9/week until the end of the month.", applyAdjustment: "Apply adjustment", budgetPace: "Budget pace", budgetUsed: "budget used", monthElapsed: "of the month elapsed", budget: "Budget", monthTime: "Month time", closingForecast: "Closing forecast", abovePlan: "≈ €95 above plan if the pace continues.", viewProjection: "View projection →", goalImpact: "Goal impact", trip: "TRIP", delayCopy: "Your budget may delay the goal by ~12 days.", contributionCopy: "With the suggested adjustment, your €250/month contribution remains protected.", viewGoalImpact: "View goal impact",
  },
  appSettings: {
    title: "Settings", description: "Manage preferences, appearance, notifications, data and account security.", save: "Save changes", saved: "Changes saved", settingsSummary: "Settings summary", generalPreferences: "General preferences", currentCurrency: "Current currency", currency: "Currency", currencyDetail: "Used in reports, budgets and goals.", language: "Language", languageDetail: "Primary interface language.", theme: "Theme", themeDetail: "Appearance applied to the application.", currentExperience: "Current MoneyPilot visual experience.", financialCycleDay: "Financial cycle day", cycleDetail: "Budgets renew every day 7.", notifications: "Notifications", active: "Active", ofNotifications: "of 5 notifications are enabled.", dark: "Dark", light: "Light", toggle: "Toggle", changeProfilePhoto: "Change profile photo",
    notificationItems: ["Transaction capture", "Budget alerts", "Goal reminders", "AI insights", "Weekly summary"], notificationDetails: ["Notify me when a new transaction is identified.", "Warn me when a category approaches its limit.", "Remind me about contributions and goal deadlines.", "Notify me when a new recommendation is available.", "Send a weekly summary of my financial progress."],
    backgroundPersonalization: "Background personalization", currentBackground: "Current background image", backgroundDescription: "Use a custom image while keeping the dark overlay for readability.", changeImage: "Change image", restoreDefault: "Restore default", imageRecommendation: "JPG or PNG · recommended 1920 × 1080", backgroundScroll: "The background follows scrolling; side navigation remains fixed.",
    accountSecurity: "Data, account and security", profile: "Profile", loading: "Loading...", securityItems: ["Export data", "Bank sync", "Change password", "Connected sessions", "Categories and classification"], securityDetails: ["Download a copy of your MoneyPilot data.", "Manage connected accounts and institutions.", "Update your account access password.", "Review devices with access to your account.", "Manage categories and automatic classification rules."], securityActions: ["Export", "Manage", "Change", "Review", "Open"],
    dangerZone: "Danger zone", dangerDescription: "Permanently delete your account and all associated data.", deleteAccount: "Delete account", actionDisabled: "Action disabled", support: "Support and help", supportDescription: "Find answers or contact our team when you need help.", contactSupport: "Contact support",
  },
  appCommon: { userAvatar: "User avatar", august2026: "August 2026", actions: "Actions", edit: "Edit", moreOptions: "More options for", cancel: "Cancel", saveChanges: "Save changes", remove: "Remove" },
} as const;

type DeepStrings<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly DeepStrings<U>[] : T extends object ? { readonly [K in keyof T]: DeepStrings<T[K]> } : T;
export type AppTranslation = DeepStrings<typeof en>;

const pt: AppTranslation = {
  appNavigation: { navigation: "Navegação principal", dashboard: "Dashboard", transactions: "Transações", budgets: "Orçamentos", insights: "Insights IA", goals: "Objetivos", investments: "Investimentos", settings: "Configurações", help: "Ajuda", logout: "Sair", theme: "Aparência", darkTheme: "Usar tema escuro", lightTheme: "Usar tema claro" },
  appDashboard: { welcome: "Bem-vindo,", welcomeBack: "Bem-vindo de volta,", neutralName: "olá", today: "Hoje", month: "Mês", date: "Data", profilePhoto: "Foto do perfil", spendingTitle: "Para onde foi o seu dinheiro?", spendingAttentionTitle: "Compras merece atenção", spendingAttentionDescription: "É seu maior gasto variável neste mês.", availableToSpend: "Disponível para gastar", safe: "Seguro", availableDescription: "Você pode usar este valor sem comprometer contas e metas.", untilDate: "Até 31 Ago", viewCalculation: "Ver cálculo →", income: "Receitas", expenses: "Despesas", accountBalance: "Saldo em contas", versusLastMonth: "vs mês passado", totalThisMonth: "Total este mês", totalConnected: "Total conectado", viewAccounts: "Ver contas →", hideValues: "Ocultar valores financeiros", showValues: "Mostrar valores financeiros", goalsStatus: "Status das Metas", viewAll: "Ver todas →", viewAllGoals: "Ver todas as metas", mainGoal: "Meta principal", italyTrip: "Viagem para Itália", onSchedule: "Dentro do prazo", ofAmount: "de €6.000", forecastMay2028: "Previsão: Maio 2028", nextBestAction: "Próxima melhor ação", opportunityDetected: "OPORTUNIDADE DETECTADA", freePerMonth: "Libere €100/mês", reduceFood: "Reduza €25/semana em alimentação.", goalImpact: "Impacto na meta", threeMonthsEarlier: "≈ 3 meses antes", tripPlan: "Viagem • mantendo o restante do plano", applyPlan: "Aplicar plano", seeHow: "Ver como →", upcomingBills: "Próximas contas", untilSep1: "até 01 Set", viewCalendar: "Ver calendário →", monthStatus: "Status do mês", onTrack: "No caminho certo", monthStatusDescription: "Você usou 59,7% da renda e ainda faltam 9 dias para o próximo pagamento. Alimentação está acima do ritmo esperado, mas o mês ainda pode fechar dentro do planejado.", viewDiagnosis: "Ver diagnóstico", total: "Total", bills: { internet: "Internet", energy: "Energia", rent: "Aluguel", aug27: "27 Ago", aug29: "29 Ago", sep1: "01 Set" }, categories: { rent: "Aluguel", supermarket: "Supermercado", other: "Outros", housing: "Moradia", food: "Alimentação", transportation: "Transporte", leisure: "Lazer", health: "Saúde", shopping: "Compras" } },
  financialFlow: { pageTitle: "Fluxo Financeiro", pageDescription: "Analise seu saldo, receitas e despesas em detalhes.", title: "Seu fluxo financeiro", balance: "Saldo", income: "Receitas", expenses: "Despesas", periodSummary: "Resumo do período", availableBalance: "Saldo disponível", savings: "Poupança", salary: "Salário", business: "Negócios", food: "Alimentação", versusPreviousPeriod: "vs. período anterior", versusLastMonth: "vs. mês passado", lastSevenDaysBalance: "Saldo disponível · últimos 7 dias", lastSevenDaysIncome: "Receitas · últimos 7 dias", lastSevenDaysExpenses: "Despesas · últimos 7 dias", averagePerDay: "Média / dia", barView: "Visualização em barras", distributionView: "Visualização de distribuição", trendView: "Visualização de tendência", currentDistribution: "distribuição atual", account: "Conta", category: "Categoria", months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"], labels: { accountBalance: "Saldo em contas", accounts: "5 contas", mainAccount: "Conta principal", investments: "Investimentos", wallet: "Carteira", totalBalance: "Saldo total", inPeriod: "no período", largestIncome: "Maior entrada", sources: "5 fontes", freelanceProjects: "Freelance / Projetos", other: "Outros", totalIncome: "Total receitas", largestCategory: "Maior categoria", homeShare: "Casa · 36%", categories: "Categorias", totalExpenses: "Total despesas", fiveCategories: "5 categorias", housing: "Moradia", transportation: "Transporte", subscriptions: "Assinaturas", leisure: "Lazer" } },
  appTransactions: { eyebrow: "TRANSAÇÕES", title: "Transações", description: "Veja o que mudou e como cada gasto impacta seu mês.", search: "Buscar transação", month: "Mês", newTransaction: "Nova transação", avatar: "Avatar do usuário", close: "Fechar", modalDescription: "Adicione uma movimentação manual à sua conta.", descriptionField: "Descrição", value: "Valor", category: "Categoria", addTransaction: "Adicionar transação", filters: ["Agosto 2026", "Todas as categorias", "Todos os pagamentos", "Todas as origens", "Mais recentes"], movements: "Movimentações", newLastSevenDays: "7 novas nos últimos 7 dias", monthlySpend: "Gasto do mês", incomeUsage: "59,7% da renda • +8,7% vs jul", variableSpendRising: "Gasto variável em alta", shopping: "Compras", largestVariableExpense: "€134,60 • maior gasto variável", availableToSpend: "Disponível para gastar", protectedAmount: "Até 31 Ago • contas e metas protegidas", augustTransactions: "Transações de Agosto", found: "45 transações encontradas", columns: ["Descrição / Estabelecimento", "Categoria", "Pagamento", "Data", "Origem", "Valor", "Ações", "Excluir"], empty: "Nenhuma transação encontrada.", showing: "Mostrando 1–7 de 45 transações", actionsFor: "Ações de", delete: "Excluir", patternDetected: "Padrão detectado", patternBadge: "5× em 3 dias", patternCopy: "Supermercado apareceu 5 vezes nos últimos 3 dias.", related: "Ver transações relacionadas →", goalImpact: "Impacto na meta", trip: "VIAGEM", impactCopy: "Compras somam €134,60; no ritmo atual, Viagem pode atrasar ~12 dias.", viewGoalImpact: "Ver impacto na meta →", labels: { subscriptions: "Assinaturas", supermarket: "Supermercado", coffee: "Café", card: "Cartão", statement: "Extrato", manual: "Manual" } },
  appBudgets: { eyebrow: "ORÇAMENTOS", title: "Orçamentos", description: "Acompanhe o ritmo dos gastos e ajuste antes de comprometer suas metas.", search: "Buscar orçamentos", month: "Mês", selectMonth: "Selecionar mês", newBudget: "Novo orçamento", close: "Fechar", modalDescription: "Defina um limite mensal para uma categoria.", category: "Categoria", monthlyLimit: "Limite mensal", addBudget: "Adicionar orçamento", planned: "Orçamento planejado", plannedDetail: "Agosto · 11 categorias planejadas", spent: "Gasto até agora", spentDetail: "73,3% usado · 61% do mês passou", forecast: "Previsão de fechamento", forecastDetail: "≈ €95 acima do planejado no ritmo atual", needsAction: "Precisa de ação", needsActionDetail: "Compras · Café · Assinaturas", yourBudgets: "Seus orçamentos", categoriesPeriod: "11 categorias · Agosto 2026", columns: ["Categoria", "Orçamento", "Gasto", "Restante", "Progresso", "Status", "Ações"], empty: "Nenhum orçamento encontrado.", addCategory: "+ Adicionar categoria", actionsFor: "Ações de", editLimit: "Editar limite", statuses: { onPlan: "Dentro do plano", inControl: "No controle", attention: "Atenção", nearLimit: "Perto do limite", exceeded: "Estourado" }, nextBestAction: "Próxima melhor ação", priority: "PRIORIDADE", recover: "Recupere €34,60", recoverCopy: "Compras já passou do limite. Reduza ~€9/semana até o fim do mês.", applyAdjustment: "Aplicar ajuste", budgetPace: "Ritmo do orçamento", budgetUsed: "orçamento usado", monthElapsed: "do mês passou", budget: "Orçamento", monthTime: "Tempo do mês", closingForecast: "Previsão de fechamento", abovePlan: "≈ €95 acima do plano se mantiver o ritmo.", viewProjection: "Ver projeção →", goalImpact: "Impacto na meta", trip: "VIAGEM", delayCopy: "Seu orçamento pode atrasar a meta em ~12 dias.", contributionCopy: "Com o ajuste sugerido, sua contribuição de €250/mês continua protegida.", viewGoalImpact: "Ver impacto na meta" },
  appSettings: { title: "Configurações", description: "Gerencie preferências, aparência, notificações, dados e segurança da sua conta.", save: "Salvar alterações", saved: "Alterações salvas", settingsSummary: "Resumo das configurações", generalPreferences: "Preferências gerais", currentCurrency: "Moeda atual", currency: "Moeda", currencyDetail: "Usada em relatórios, orçamentos e metas.", language: "Idioma", languageDetail: "Idioma principal da interface.", theme: "Tema", themeDetail: "Aparência aplicada ao aplicativo.", currentExperience: "Experiência visual atual do MoneyPilot.", financialCycleDay: "Dia do ciclo financeiro", cycleDetail: "Orçamentos renovados todo dia 7.", notifications: "Notificações", active: "Ativas", ofNotifications: "de 5 notificações estão ligadas.", dark: "Escuro", light: "Claro", toggle: "Alternar", changeProfilePhoto: "Alterar foto do perfil", notificationItems: ["Captura de transações", "Alertas de orçamento", "Lembretes de metas", "Insights da IA", "Resumo semanal"], notificationDetails: ["Avise quando uma nova transação for identificada.", "Avise quando uma categoria se aproximar do limite.", "Lembre aportes e prazos das metas.", "Avise quando houver uma nova recomendação.", "Envie um resumo semanal do progresso financeiro."], backgroundPersonalization: "Personalização do fundo", currentBackground: "Imagem de fundo atual", backgroundDescription: "Use uma imagem personalizada mantendo o overlay escuro para preservar a leitura.", changeImage: "Trocar imagem", restoreDefault: "Restaurar padrão", imageRecommendation: "JPG ou PNG · recomendado 1920 × 1080", backgroundScroll: "O background acompanha o scroll; a navegação lateral continua fixa.", accountSecurity: "Dados, conta e segurança", profile: "Perfil", loading: "Carregando...", securityItems: ["Exportar dados", "Sincronização bancária", "Alterar senha", "Sessões conectadas", "Categorias e classificação"], securityDetails: ["Baixe uma cópia dos seus dados do MoneyPilot.", "Gerencie contas e instituições conectadas.", "Atualize a senha de acesso à sua conta.", "Revise dispositivos com acesso à sua conta.", "Gerencie categorias e regras de classificação automática."], securityActions: ["Exportar", "Gerenciar", "Alterar", "Revisar", "Abrir"], dangerZone: "Zona de perigo", dangerDescription: "Exclua permanentemente sua conta e todos os dados associados.", deleteAccount: "Excluir conta", actionDisabled: "Ação desativada", support: "Suporte e ajuda", supportDescription: "Encontre respostas ou fale com nossa equipe quando precisar.", contactSupport: "Falar com suporte" },
  appCommon: { userAvatar: "Avatar do usuário", august2026: "Agosto 2026", actions: "Ações", edit: "Editar", moreOptions: "Mais opções para", cancel: "Cancelar", saveChanges: "Salvar alterações", remove: "Remover" },
};

const es: AppTranslation = {
  ...pt,
  appNavigation: { navigation: "Navegación principal", dashboard: "Dashboard", transactions: "Transacciones", budgets: "Presupuestos", insights: "Insights de IA", goals: "Objetivos", investments: "Inversiones", settings: "Configuración", help: "Ayuda", logout: "Cerrar sesión", theme: "Apariencia", darkTheme: "Usar tema oscuro", lightTheme: "Usar tema claro" },
  appDashboard: { ...pt.appDashboard, welcome: "Bienvenido,", welcomeBack: "Bienvenido de nuevo,", neutralName: "hola", today: "Hoy", month: "Mes", date: "Fecha", profilePhoto: "Foto de perfil", spendingTitle: "¿A dónde fue tu dinero?", spendingAttentionTitle: "Las compras requieren atención", spendingAttentionDescription: "Es tu mayor gasto variable este mes.", availableToSpend: "Disponible para gastar", safe: "Seguro", availableDescription: "Puedes usar este importe sin comprometer facturas y objetivos.", untilDate: "Hasta el 31 Ago", viewCalculation: "Ver cálculo →", income: "Ingresos", expenses: "Gastos", accountBalance: "Saldo en cuentas", versusLastMonth: "vs mes pasado", totalThisMonth: "Total este mes", totalConnected: "Total conectado", viewAccounts: "Ver cuentas →", hideValues: "Ocultar valores financieros", showValues: "Mostrar valores financieros", goalsStatus: "Estado de los objetivos", viewAll: "Ver todos →", viewAllGoals: "Ver todos los objetivos", mainGoal: "Objetivo principal", italyTrip: "Viaje a Italia", onSchedule: "Dentro del plazo", ofAmount: "de €6.000", forecastMay2028: "Previsión: Mayo 2028", nextBestAction: "Próxima mejor acción", opportunityDetected: "OPORTUNIDAD DETECTADA", freePerMonth: "Libera €100/mes", reduceFood: "Reduce €25/semana en alimentación.", goalImpact: "Impacto en el objetivo", threeMonthsEarlier: "≈ 3 meses antes", tripPlan: "Viaje • manteniendo el resto del plan", applyPlan: "Aplicar plan", seeHow: "Ver cómo →", upcomingBills: "Próximas facturas", untilSep1: "hasta el 01 Sep", viewCalendar: "Ver calendario →", monthStatus: "Estado del mes", onTrack: "Por buen camino", monthStatusDescription: "Has usado el 59,7% de tus ingresos y aún faltan 9 días para el próximo pago. Alimentación está por encima del ritmo esperado, pero el mes todavía puede cerrar dentro de lo planificado.", viewDiagnosis: "Ver diagnóstico", total: "Total", bills: { internet: "Internet", energy: "Energía", rent: "Alquiler", aug27: "27 Ago", aug29: "29 Ago", sep1: "01 Sep" }, categories: { rent: "Alquiler", supermarket: "Supermercado", other: "Otros", housing: "Vivienda", food: "Alimentación", transportation: "Transporte", leisure: "Ocio", health: "Salud", shopping: "Compras" } },
  financialFlow: { ...pt.financialFlow, pageTitle: "Flujo financiero", pageDescription: "Analiza tu saldo, ingresos y gastos en detalle.", title: "Tu flujo financiero", balance: "Saldo", income: "Ingresos", expenses: "Gastos", periodSummary: "Resumen del período", availableBalance: "Saldo disponible", savings: "Ahorros", salary: "Salario", business: "Negocios", food: "Alimentación", versusPreviousPeriod: "vs. período anterior", versusLastMonth: "vs. mes pasado", lastSevenDaysBalance: "Saldo disponible · últimos 7 días", lastSevenDaysIncome: "Ingresos · últimos 7 días", lastSevenDaysExpenses: "Gastos · últimos 7 días", averagePerDay: "Media / día", barView: "Vista de barras", distributionView: "Vista de distribución", trendView: "Vista de tendencia", currentDistribution: "distribución actual", account: "Cuenta", category: "Categoría", months: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"], labels: { accountBalance: "Saldo en cuentas", accounts: "5 cuentas", mainAccount: "Cuenta principal", investments: "Inversiones", wallet: "Cartera", totalBalance: "Saldo total", inPeriod: "en el período", largestIncome: "Mayor ingreso", sources: "5 fuentes", freelanceProjects: "Freelance / Proyectos", other: "Otros", totalIncome: "Total ingresos", largestCategory: "Mayor categoría", homeShare: "Vivienda · 36%", categories: "Categorías", totalExpenses: "Total gastos", fiveCategories: "5 categorías", housing: "Vivienda", transportation: "Transporte", subscriptions: "Suscripciones", leisure: "Ocio" } },
  appTransactions: { ...pt.appTransactions, eyebrow: "TRANSACCIONES", title: "Transacciones", description: "Descubre qué cambió y cómo afecta cada gasto a tu mes.", search: "Buscar transacción", month: "Mes", newTransaction: "Nueva transacción", avatar: "Avatar del usuario", close: "Cerrar", modalDescription: "Añade un movimiento manual a tu cuenta.", descriptionField: "Descripción", value: "Importe", category: "Categoría", addTransaction: "Añadir transacción", filters: ["Agosto 2026", "Todas las categorías", "Todos los pagos", "Todos los orígenes", "Más recientes"], movements: "Movimientos", newLastSevenDays: "7 nuevos en los últimos 7 días", monthlySpend: "Gasto del mes", incomeUsage: "59,7% de los ingresos • +8,7% vs jul", variableSpendRising: "Gasto variable al alza", shopping: "Compras", largestVariableExpense: "€134,60 • mayor gasto variable", availableToSpend: "Disponible para gastar", protectedAmount: "Hasta el 31 Ago • facturas y objetivos protegidos", augustTransactions: "Transacciones de agosto", found: "45 transacciones encontradas", columns: ["Descripción / Establecimiento", "Categoría", "Pago", "Fecha", "Origen", "Importe", "Acciones", "Eliminar"], empty: "No se encontraron transacciones.", showing: "Mostrando 1–7 de 45 transacciones", actionsFor: "Acciones de", delete: "Eliminar", patternDetected: "Patrón detectado", patternBadge: "5× en 3 días", patternCopy: "Supermercado apareció 5 veces en los últimos 3 días.", related: "Ver transacciones relacionadas →", goalImpact: "Impacto en el objetivo", trip: "VIAJE", impactCopy: "Las compras suman €134,60; al ritmo actual, Viaje podría retrasarse ~12 días.", viewGoalImpact: "Ver impacto en el objetivo →", labels: { subscriptions: "Suscripciones", supermarket: "Supermercado", coffee: "Café", card: "Tarjeta", statement: "Extracto", manual: "Manual" } },
  appBudgets: { ...pt.appBudgets, eyebrow: "PRESUPUESTOS", title: "Presupuestos", description: "Sigue el ritmo de los gastos y ajusta antes de comprometer tus objetivos.", search: "Buscar presupuestos", month: "Mes", selectMonth: "Seleccionar mes", newBudget: "Nuevo presupuesto", close: "Cerrar", modalDescription: "Define un límite mensual para una categoría.", category: "Categoría", monthlyLimit: "Límite mensual", addBudget: "Añadir presupuesto", planned: "Presupuesto planificado", plannedDetail: "Agosto · 11 categorías planificadas", spent: "Gastado hasta ahora", spentDetail: "73,3% usado · 61% del mes transcurrido", forecast: "Previsión de cierre", forecastDetail: "≈ €95 por encima del plan al ritmo actual", needsAction: "Requiere acción", needsActionDetail: "Compras · Café · Suscripciones", yourBudgets: "Tus presupuestos", categoriesPeriod: "11 categorías · Agosto 2026", columns: ["Categoría", "Presupuesto", "Gastado", "Restante", "Progreso", "Estado", "Acciones"], empty: "No se encontraron presupuestos.", addCategory: "+ Añadir categoría", actionsFor: "Acciones de", editLimit: "Editar límite", statuses: { onPlan: "Dentro del plan", inControl: "Bajo control", attention: "Atención", nearLimit: "Cerca del límite", exceeded: "Excedido" }, nextBestAction: "Próxima mejor acción", priority: "PRIORIDAD", recover: "Recupera €34,60", recoverCopy: "Compras ya superó el límite. Reduce ~€9/semana hasta final de mes.", applyAdjustment: "Aplicar ajuste", budgetPace: "Ritmo del presupuesto", budgetUsed: "presupuesto usado", monthElapsed: "del mes transcurrido", budget: "Presupuesto", monthTime: "Tiempo del mes", closingForecast: "Previsión de cierre", abovePlan: "≈ €95 por encima del plan si se mantiene el ritmo.", viewProjection: "Ver proyección →", goalImpact: "Impacto en el objetivo", trip: "VIAJE", delayCopy: "Tu presupuesto puede retrasar el objetivo ~12 días.", contributionCopy: "Con el ajuste sugerido, tu aportación de €250/mes sigue protegida.", viewGoalImpact: "Ver impacto en el objetivo" },
  appSettings: { ...pt.appSettings, settingsSummary: "Resumen de configuración", currentCurrency: "Moneda actual", currencyDetail: "Usada en informes, presupuestos y objetivos.", languageDetail: "Idioma principal de la interfaz.", themeDetail: "Apariencia aplicada a la aplicación.", currentExperience: "Experiencia visual actual de MoneyPilot.", cycleDetail: "Los presupuestos se renuevan cada día 7.", toggle: "Alternar", changeProfilePhoto: "Cambiar foto de perfil", title: "Configuración", description: "Gestiona preferencias, notificaciones, personalización y seguridad de la cuenta.", save: "Guardar cambios", saved: "Cambios guardados", generalPreferences: "Preferencias generales", currency: "Moneda", language: "Idioma", theme: "Tema", financialCycleDay: "Día del ciclo financiero", notifications: "Notificaciones", active: "Activas", ofNotifications: "de 5 notificaciones están activadas.", dark: "Oscuro", light: "Claro", notificationItems: ["Captura de transacciones", "Alertas de presupuesto", "Recordatorios de objetivos", "Insights de IA", "Resumen semanal"], notificationDetails: ["Avísame cuando se identifique una nueva transacción.", "Avísame cuando una categoría se acerque al límite.", "Recuérdame las aportaciones y plazos de los objetivos.", "Avísame cuando haya una nueva recomendación.", "Envía un resumen semanal de mi progreso financiero."], backgroundPersonalization: "Personalización del fondo", currentBackground: "Imagen de fondo actual", backgroundDescription: "Usa una imagen personalizada manteniendo la capa oscura para conservar la legibilidad.", changeImage: "Cambiar imagen", restoreDefault: "Restaurar predeterminado", imageRecommendation: "JPG o PNG · recomendado 1920 × 1080", backgroundScroll: "El fondo acompaña el desplazamiento; la navegación lateral permanece fija.", accountSecurity: "Datos, cuenta y seguridad", profile: "Perfil", loading: "Cargando...", securityItems: ["Exportar datos", "Sincronización bancaria", "Cambiar contraseña", "Sesiones conectadas", "Categorías y clasificación"], securityDetails: ["Descarga una copia de tus datos de MoneyPilot.", "Gestiona cuentas e instituciones conectadas.", "Actualiza la contraseña de acceso a tu cuenta.", "Revisa los dispositivos con acceso a tu cuenta.", "Gestiona categorías y reglas de clasificación automática."], securityActions: ["Exportar", "Gestionar", "Cambiar", "Revisar", "Abrir"], dangerZone: "Zona de peligro", dangerDescription: "Elimina permanentemente tu cuenta y todos los datos asociados.", deleteAccount: "Eliminar cuenta", actionDisabled: "Acción desactivada", support: "Soporte y ayuda", supportDescription: "Encuentra respuestas o contacta con nuestro equipo cuando lo necesites.", contactSupport: "Contactar con soporte" },
  appCommon: { userAvatar: "Avatar del usuario", august2026: "Agosto 2026", actions: "Acciones", edit: "Editar", moreOptions: "Más opciones para", cancel: "Cancelar", saveChanges: "Guardar cambios", remove: "Eliminar" },
};

const de: AppTranslation = { ...en, appNavigation: { ...en.appNavigation, dashboard: "Übersicht", transactions: "Transaktionen", budgets: "Budgets", insights: "Einblicke", goals: "Ziele", investments: "Investitionen", settings: "Einstellungen", help: "Hilfe", logout: "Abmelden", theme: "Darstellung", darkTheme: "Dunkles Design", lightTheme: "Helles Design" }, appSettings: { ...en.appSettings, title: "Einstellungen", description: "Verwalte Sprache, Währung, Darstellung und Kontosicherheit.", save: "Änderungen speichern", saved: "Änderungen gespeichert", settingsSummary: "Übersicht der Einstellungen", generalPreferences: "Allgemeine Einstellungen", currentCurrency: "Aktuelle Währung", currency: "Währung", currencyDetail: "Basiswährung für Beträge, Budgets und Ziele.", language: "Sprache", languageDetail: "Sprache der Benutzeroberfläche.", theme: "Design", themeDetail: "Darstellung der Anwendung.", currentExperience: "Aktuelle MoneyPilot-Darstellung.", financialCycleDay: "Tag des Finanzzyklus", notifications: "Benachrichtigungen", dark: "Dunkel", light: "Hell", backgroundPersonalization: "Hintergrund", currentBackground: "Aktueller Hintergrund", accountSecurity: "Daten, Konto und Sicherheit", profile: "Profil", loading: "Wird geladen …", dangerZone: "Gefahrenbereich", deleteAccount: "Konto löschen", support: "Hilfe und Support", contactSupport: "Support kontaktieren" } };
const fr: AppTranslation = { ...en, appNavigation: { ...en.appNavigation, dashboard: "Tableau de bord", transactions: "Transactions", budgets: "Budgets", insights: "Analyses", goals: "Objectifs", investments: "Investissements", settings: "Paramètres", help: "Aide", logout: "Se déconnecter", theme: "Apparence", darkTheme: "Thème sombre", lightTheme: "Thème clair" }, appSettings: { ...en.appSettings, title: "Paramètres", description: "Gérez la langue, la devise, l’apparence et la sécurité du compte.", save: "Enregistrer", saved: "Modifications enregistrées", settingsSummary: "Résumé des paramètres", generalPreferences: "Préférences générales", currentCurrency: "Devise actuelle", currency: "Devise", currencyDetail: "Devise de base des montants, budgets et objectifs.", language: "Langue", languageDetail: "Langue principale de l’interface.", theme: "Thème", themeDetail: "Apparence de l’application.", currentExperience: "Apparence actuelle de MoneyPilot.", financialCycleDay: "Jour du cycle financier", notifications: "Notifications", dark: "Sombre", light: "Clair", backgroundPersonalization: "Personnalisation du fond", currentBackground: "Fond actuel", accountSecurity: "Données, compte et sécurité", profile: "Profil", loading: "Chargement…", dangerZone: "Zone sensible", deleteAccount: "Supprimer le compte", support: "Aide et assistance", contactSupport: "Contacter l’assistance" } };
const nl: AppTranslation = { ...en, appNavigation: { ...en.appNavigation, dashboard: "Overzicht", transactions: "Transacties", budgets: "Budgetten", insights: "Inzichten", goals: "Doelen", investments: "Beleggingen", settings: "Instellingen", help: "Help", logout: "Uitloggen", theme: "Weergave", darkTheme: "Donker thema", lightTheme: "Licht thema" }, appSettings: { ...en.appSettings, title: "Instellingen", description: "Beheer taal, valuta, weergave en accountbeveiliging.", save: "Wijzigingen opslaan", saved: "Wijzigingen opgeslagen", settingsSummary: "Overzicht instellingen", generalPreferences: "Algemene voorkeuren", currentCurrency: "Huidige valuta", currency: "Valuta", currencyDetail: "Basisvaluta voor bedragen, budgetten en doelen.", language: "Taal", languageDetail: "Hoofdtaal van de interface.", theme: "Thema", themeDetail: "Weergave van de app.", currentExperience: "Huidige MoneyPilot-weergave.", financialCycleDay: "Dag van de financiële cyclus", notifications: "Meldingen", dark: "Donker", light: "Licht", backgroundPersonalization: "Achtergrond", currentBackground: "Huidige achtergrond", accountSecurity: "Gegevens, account en beveiliging", profile: "Profiel", loading: "Laden…", dangerZone: "Gevarenzone", deleteAccount: "Account verwijderen", support: "Hulp en ondersteuning", contactSupport: "Contact opnemen" } };
const it: AppTranslation = { ...en, appNavigation: { ...en.appNavigation, dashboard: "Panoramica", transactions: "Transazioni", budgets: "Budget", insights: "Analisi", goals: "Obiettivi", investments: "Investimenti", settings: "Impostazioni", help: "Aiuto", logout: "Esci", theme: "Aspetto", darkTheme: "Tema scuro", lightTheme: "Tema chiaro" }, appSettings: { ...en.appSettings, title: "Impostazioni", description: "Gestisci lingua, valuta, aspetto e sicurezza dell’account.", save: "Salva modifiche", saved: "Modifiche salvate", settingsSummary: "Riepilogo impostazioni", generalPreferences: "Preferenze generali", currentCurrency: "Valuta attuale", currency: "Valuta", currencyDetail: "Valuta di base per importi, budget e obiettivi.", language: "Lingua", languageDetail: "Lingua principale dell’interfaccia.", theme: "Tema", themeDetail: "Aspetto dell’applicazione.", currentExperience: "Aspetto attuale di MoneyPilot.", financialCycleDay: "Giorno del ciclo finanziario", notifications: "Notifiche", dark: "Scuro", light: "Chiaro", backgroundPersonalization: "Sfondo", currentBackground: "Sfondo attuale", accountSecurity: "Dati, account e sicurezza", profile: "Profilo", loading: "Caricamento…", dangerZone: "Zona pericolosa", deleteAccount: "Elimina account", support: "Aiuto e supporto", contactSupport: "Contatta il supporto" } };
Object.assign(de, {
  appDashboard: { ...en.appDashboard, welcome: "Willkommen,", welcomeBack: "Willkommen zurück,", neutralName: "Hallo", today: "Heute", month: "Monat", date: "Datum", spendingTitle: "Wofür hast du dein Geld ausgegeben?", availableToSpend: "Verfügbar", safe: "Sicher", income: "Einnahmen", expenses: "Ausgaben", accountBalance: "Kontostand", versusLastMonth: "zum Vormonat", totalThisMonth: "Gesamt in diesem Monat", goalsStatus: "Zielstatus", viewAll: "Alle anzeigen →", mainGoal: "Hauptziel", nextBestAction: "Nächste beste Aktion", upcomingBills: "Anstehende Rechnungen", monthStatus: "Monatsstatus", onTrack: "Im Plan", viewDiagnosis: "Analyse ansehen", total: "Gesamt", categories: { ...en.appDashboard.categories, rent: "Miete", supermarket: "Supermarkt", other: "Sonstiges", housing: "Wohnen", food: "Lebensmittel", transportation: "Verkehr", leisure: "Freizeit", health: "Gesundheit", shopping: "Einkäufe" } },
  financialFlow: { ...en.financialFlow, pageTitle: "Finanzübersicht", pageDescription: "Analysiere Kontostand, Einnahmen und Ausgaben im Detail.", title: "Dein Finanzfluss", balance: "Saldo", income: "Einnahmen", expenses: "Ausgaben", periodSummary: "Zeitraumübersicht", availableBalance: "Verfügbarer Saldo", savings: "Ersparnisse", salary: "Gehalt", business: "Geschäft", food: "Lebensmittel", versusPreviousPeriod: "zum vorherigen Zeitraum", versusLastMonth: "zum Vormonat", averagePerDay: "Durchschnitt / Tag", account: "Konto", category: "Kategorie" },
  appTransactions: { ...en.appTransactions, eyebrow: "TRANSAKTIONEN", title: "Transaktionen", description: "Sieh, was sich geändert hat und wie jede Ausgabe deinen Monat beeinflusst.", search: "Transaktion suchen", month: "Monat", newTransaction: "Neue Transaktion", close: "Schließen", modalDescription: "Füge deinem Konto eine manuelle Transaktion hinzu.", descriptionField: "Beschreibung", value: "Betrag", category: "Kategorie", addTransaction: "Transaktion hinzufügen", filters: ["August 2026", "Alle Kategorien", "Alle Zahlungen", "Alle Quellen", "Neueste"], movements: "Transaktionen", monthlySpend: "Monatsausgaben", availableToSpend: "Verfügbar", augustTransactions: "Transaktionen im August", columns: ["Beschreibung / Händler", "Kategorie", "Zahlung", "Datum", "Quelle", "Betrag", "Aktionen", "Löschen"], empty: "Keine Transaktionen gefunden.", actionsFor: "Aktionen für", delete: "Löschen", labels: { subscriptions: "Abonnements", supermarket: "Supermarkt", coffee: "Kaffee", card: "Karte", statement: "Kontoauszug", manual: "Manuell" } },
  appBudgets: { ...en.appBudgets, eyebrow: "BUDGETS", title: "Budgets", description: "Behalte dein Ausgabentempo im Blick und passe es rechtzeitig an.", search: "Budgets suchen", month: "Monat", selectMonth: "Monat auswählen", newBudget: "Neues Budget", close: "Schließen", modalDescription: "Lege ein Monatslimit für eine Kategorie fest.", category: "Kategorie", monthlyLimit: "Monatslimit", addBudget: "Budget hinzufügen", planned: "Geplantes Budget", spent: "Bisher ausgegeben", forecast: "Monatsprognose", needsAction: "Handlung nötig", yourBudgets: "Deine Budgets", columns: ["Kategorie", "Budget", "Ausgegeben", "Verbleibend", "Fortschritt", "Status", "Aktionen"], empty: "Keine Budgets gefunden.", addCategory: "+ Kategorie hinzufügen", editLimit: "Limit bearbeiten", statuses: { onPlan: "Im Plan", inControl: "Unter Kontrolle", attention: "Achtung", nearLimit: "Nahe am Limit", exceeded: "Überschritten" }, nextBestAction: "Nächste beste Aktion", applyAdjustment: "Anpassung anwenden", budgetPace: "Budgettempo", budgetUsed: "Budget verwendet", monthElapsed: "des Monats vergangen", closingForecast: "Monatsprognose", viewProjection: "Prognose anzeigen →", goalImpact: "Auswirkung auf das Ziel" },
  appCommon: { ...en.appCommon, userAvatar: "Benutzeravatar", actions: "Aktionen", edit: "Bearbeiten", moreOptions: "Weitere Optionen für", cancel: "Abbrechen", saveChanges: "Änderungen speichern", remove: "Entfernen" },
});
Object.assign(fr, {
  appDashboard: { ...en.appDashboard, welcome: "Bienvenue,", welcomeBack: "Bon retour,", neutralName: "bonjour", today: "Aujourd’hui", month: "Mois", date: "Date", spendingTitle: "Où est passé votre argent ?", availableToSpend: "Disponible", safe: "Sûr", income: "Revenus", expenses: "Dépenses", accountBalance: "Solde du compte", versusLastMonth: "par rapport au mois dernier", totalThisMonth: "Total ce mois-ci", goalsStatus: "État des objectifs", viewAll: "Tout afficher →", mainGoal: "Objectif principal", nextBestAction: "Prochaine action recommandée", upcomingBills: "Factures à venir", monthStatus: "Situation du mois", onTrack: "En bonne voie", viewDiagnosis: "Voir l’analyse", total: "Total", categories: { ...en.appDashboard.categories, rent: "Loyer", supermarket: "Supermarché", other: "Autres", housing: "Logement", food: "Alimentation", transportation: "Transport", leisure: "Loisirs", health: "Santé", shopping: "Achats" } },
  financialFlow: { ...en.financialFlow, pageTitle: "Flux financier", pageDescription: "Analysez votre solde, vos revenus et vos dépenses en détail.", title: "Votre flux financier", balance: "Solde", income: "Revenus", expenses: "Dépenses", periodSummary: "Résumé de la période", availableBalance: "Solde disponible", savings: "Épargne", salary: "Salaire", business: "Activité", food: "Alimentation", versusPreviousPeriod: "par rapport à la période précédente", versusLastMonth: "par rapport au mois dernier", averagePerDay: "Moyenne / jour", account: "Compte", category: "Catégorie" },
  appTransactions: { ...en.appTransactions, eyebrow: "TRANSACTIONS", title: "Transactions", description: "Découvrez ce qui a changé et l’impact de chaque dépense sur votre mois.", search: "Rechercher une transaction", month: "Mois", newTransaction: "Nouvelle transaction", close: "Fermer", modalDescription: "Ajoutez une transaction manuelle à votre compte.", descriptionField: "Description", value: "Montant", category: "Catégorie", addTransaction: "Ajouter la transaction", filters: ["Août 2026", "Toutes les catégories", "Tous les paiements", "Toutes les sources", "Plus récentes"], movements: "Transactions", monthlySpend: "Dépenses du mois", availableToSpend: "Disponible", augustTransactions: "Transactions d’août", columns: ["Description / Commerçant", "Catégorie", "Paiement", "Date", "Source", "Montant", "Actions", "Supprimer"], empty: "Aucune transaction trouvée.", actionsFor: "Actions pour", delete: "Supprimer", labels: { subscriptions: "Abonnements", supermarket: "Supermarché", coffee: "Café", card: "Carte", statement: "Relevé", manual: "Manuel" } },
  appBudgets: { ...en.appBudgets, eyebrow: "BUDGETS", title: "Budgets", description: "Suivez le rythme des dépenses et ajustez-le avant qu’il n’affecte vos objectifs.", search: "Rechercher des budgets", month: "Mois", selectMonth: "Choisir le mois", newBudget: "Nouveau budget", close: "Fermer", modalDescription: "Définissez une limite mensuelle pour une catégorie.", category: "Catégorie", monthlyLimit: "Limite mensuelle", addBudget: "Ajouter le budget", planned: "Budget prévu", spent: "Dépensé à ce jour", forecast: "Prévision de fin de mois", needsAction: "Action requise", yourBudgets: "Vos budgets", columns: ["Catégorie", "Budget", "Dépensé", "Restant", "Progression", "État", "Actions"], empty: "Aucun budget trouvé.", addCategory: "+ Ajouter une catégorie", editLimit: "Modifier la limite", statuses: { onPlan: "Conforme au plan", inControl: "Sous contrôle", attention: "Attention", nearLimit: "Proche de la limite", exceeded: "Dépassé" }, nextBestAction: "Prochaine action recommandée", applyAdjustment: "Appliquer l’ajustement", budgetPace: "Rythme du budget", budgetUsed: "budget utilisé", monthElapsed: "du mois écoulé", closingForecast: "Prévision de fin de mois", viewProjection: "Voir la prévision →", goalImpact: "Impact sur l’objectif" },
  appCommon: { ...en.appCommon, userAvatar: "Avatar utilisateur", actions: "Actions", edit: "Modifier", moreOptions: "Plus d’options pour", cancel: "Annuler", saveChanges: "Enregistrer", remove: "Supprimer" },
});
Object.assign(nl, {
  appDashboard: { ...en.appDashboard, welcome: "Welkom,", welcomeBack: "Welkom terug,", neutralName: "hallo", today: "Vandaag", month: "Maand", date: "Datum", spendingTitle: "Waar ging je geld naartoe?", availableToSpend: "Beschikbaar", safe: "Veilig", income: "Inkomsten", expenses: "Uitgaven", accountBalance: "Rekeningsaldo", versusLastMonth: "ten opzichte van vorige maand", totalThisMonth: "Totaal deze maand", goalsStatus: "Status van doelen", viewAll: "Alles bekijken →", mainGoal: "Belangrijkste doel", nextBestAction: "Beste volgende stap", upcomingBills: "Aankomende rekeningen", monthStatus: "Maandstatus", onTrack: "Op schema", viewDiagnosis: "Analyse bekijken", total: "Totaal", categories: { ...en.appDashboard.categories, rent: "Huur", supermarket: "Supermarkt", other: "Overig", housing: "Wonen", food: "Voeding", transportation: "Vervoer", leisure: "Vrije tijd", health: "Gezondheid", shopping: "Aankopen" } },
  financialFlow: { ...en.financialFlow, pageTitle: "Financiële stroom", pageDescription: "Analyseer je saldo, inkomsten en uitgaven in detail.", title: "Je financiële stroom", balance: "Saldo", income: "Inkomsten", expenses: "Uitgaven", periodSummary: "Overzicht van de periode", availableBalance: "Beschikbaar saldo", savings: "Spaargeld", salary: "Salaris", business: "Zakelijk", food: "Voeding", versusPreviousPeriod: "ten opzichte van vorige periode", versusLastMonth: "ten opzichte van vorige maand", averagePerDay: "Gemiddeld / dag", account: "Rekening", category: "Categorie" },
  appTransactions: { ...en.appTransactions, eyebrow: "TRANSACTIES", title: "Transacties", description: "Bekijk wat veranderde en hoe elke uitgave je maand beïnvloedt.", search: "Transactie zoeken", month: "Maand", newTransaction: "Nieuwe transactie", close: "Sluiten", modalDescription: "Voeg handmatig een transactie aan je rekening toe.", descriptionField: "Beschrijving", value: "Bedrag", category: "Categorie", addTransaction: "Transactie toevoegen", filters: ["Augustus 2026", "Alle categorieën", "Alle betalingen", "Alle bronnen", "Meest recent"], movements: "Transacties", monthlySpend: "Uitgaven deze maand", availableToSpend: "Beschikbaar", augustTransactions: "Transacties van augustus", columns: ["Beschrijving / Handelaar", "Categorie", "Betaling", "Datum", "Bron", "Bedrag", "Acties", "Verwijderen"], empty: "Geen transacties gevonden.", actionsFor: "Acties voor", delete: "Verwijderen", labels: { subscriptions: "Abonnementen", supermarket: "Supermarkt", coffee: "Koffie", card: "Kaart", statement: "Afschrift", manual: "Handmatig" } },
  appBudgets: { ...en.appBudgets, eyebrow: "BUDGETTEN", title: "Budgetten", description: "Volg je uitgaventempo en stuur bij voordat je doelen in gevaar komen.", search: "Budgetten zoeken", month: "Maand", selectMonth: "Maand kiezen", newBudget: "Nieuw budget", close: "Sluiten", modalDescription: "Stel een maandlimiet voor een categorie in.", category: "Categorie", monthlyLimit: "Maandlimiet", addBudget: "Budget toevoegen", planned: "Gepland budget", spent: "Tot nu toe uitgegeven", forecast: "Verwachting voor maandeinde", needsAction: "Actie nodig", yourBudgets: "Je budgetten", columns: ["Categorie", "Budget", "Uitgegeven", "Resterend", "Voortgang", "Status", "Acties"], empty: "Geen budgetten gevonden.", addCategory: "+ Categorie toevoegen", editLimit: "Limiet bewerken", statuses: { onPlan: "Volgens plan", inControl: "Onder controle", attention: "Let op", nearLimit: "Bijna op limiet", exceeded: "Overschreden" }, nextBestAction: "Beste volgende stap", applyAdjustment: "Aanpassing toepassen", budgetPace: "Budgettempo", budgetUsed: "budget gebruikt", monthElapsed: "van de maand verstreken", closingForecast: "Verwachting voor maandeinde", viewProjection: "Verwachting bekijken →", goalImpact: "Effect op doel" },
  appCommon: { ...en.appCommon, userAvatar: "Gebruikersavatar", actions: "Acties", edit: "Bewerken", moreOptions: "Meer opties voor", cancel: "Annuleren", saveChanges: "Wijzigingen opslaan", remove: "Verwijderen" },
});
Object.assign(it, {
  appDashboard: { ...en.appDashboard, welcome: "Benvenuto,", welcomeBack: "Bentornato,", neutralName: "ciao", today: "Oggi", month: "Mese", date: "Data", spendingTitle: "Dove sono finiti i tuoi soldi?", availableToSpend: "Disponibile", safe: "Sicuro", income: "Entrate", expenses: "Spese", accountBalance: "Saldo del conto", versusLastMonth: "rispetto al mese scorso", totalThisMonth: "Totale del mese", goalsStatus: "Stato degli obiettivi", viewAll: "Vedi tutto →", mainGoal: "Obiettivo principale", nextBestAction: "Prossima azione consigliata", upcomingBills: "Prossime fatture", monthStatus: "Stato del mese", onTrack: "In linea", viewDiagnosis: "Vedi analisi", total: "Totale", categories: { ...en.appDashboard.categories, rent: "Affitto", supermarket: "Supermercato", other: "Altro", housing: "Casa", food: "Alimentazione", transportation: "Trasporti", leisure: "Tempo libero", health: "Salute", shopping: "Acquisti" } },
  financialFlow: { ...en.financialFlow, pageTitle: "Flusso finanziario", pageDescription: "Analizza nel dettaglio saldo, entrate e spese.", title: "Il tuo flusso finanziario", balance: "Saldo", income: "Entrate", expenses: "Spese", periodSummary: "Riepilogo del periodo", availableBalance: "Saldo disponibile", savings: "Risparmi", salary: "Stipendio", business: "Attività", food: "Alimentazione", versusPreviousPeriod: "rispetto al periodo precedente", versusLastMonth: "rispetto al mese scorso", averagePerDay: "Media / giorno", account: "Conto", category: "Categoria" },
  appTransactions: { ...en.appTransactions, eyebrow: "TRANSAZIONI", title: "Transazioni", description: "Scopri cosa è cambiato e come ogni spesa incide sul mese.", search: "Cerca transazione", month: "Mese", newTransaction: "Nuova transazione", close: "Chiudi", modalDescription: "Aggiungi manualmente una transazione al conto.", descriptionField: "Descrizione", value: "Importo", category: "Categoria", addTransaction: "Aggiungi transazione", filters: ["Agosto 2026", "Tutte le categorie", "Tutti i pagamenti", "Tutte le origini", "Più recenti"], movements: "Transazioni", monthlySpend: "Spese del mese", availableToSpend: "Disponibile", augustTransactions: "Transazioni di agosto", columns: ["Descrizione / Esercente", "Categoria", "Pagamento", "Data", "Origine", "Importo", "Azioni", "Elimina"], empty: "Nessuna transazione trovata.", actionsFor: "Azioni per", delete: "Elimina", labels: { subscriptions: "Abbonamenti", supermarket: "Supermercato", coffee: "Caffè", card: "Carta", statement: "Estratto conto", manual: "Manuale" } },
  appBudgets: { ...en.appBudgets, eyebrow: "BUDGET", title: "Budget", description: "Controlla il ritmo delle spese e correggilo prima che comprometta gli obiettivi.", search: "Cerca budget", month: "Mese", selectMonth: "Seleziona mese", newBudget: "Nuovo budget", close: "Chiudi", modalDescription: "Imposta un limite mensile per una categoria.", category: "Categoria", monthlyLimit: "Limite mensile", addBudget: "Aggiungi budget", planned: "Budget pianificato", spent: "Speso finora", forecast: "Previsione di fine mese", needsAction: "Azione necessaria", yourBudgets: "I tuoi budget", columns: ["Categoria", "Budget", "Speso", "Rimanente", "Avanzamento", "Stato", "Azioni"], empty: "Nessun budget trovato.", addCategory: "+ Aggiungi categoria", editLimit: "Modifica limite", statuses: { onPlan: "In linea con il piano", inControl: "Sotto controllo", attention: "Attenzione", nearLimit: "Vicino al limite", exceeded: "Superato" }, nextBestAction: "Prossima azione consigliata", applyAdjustment: "Applica modifica", budgetPace: "Ritmo del budget", budgetUsed: "budget utilizzato", monthElapsed: "del mese trascorso", closingForecast: "Previsione di fine mese", viewProjection: "Vedi previsione →", goalImpact: "Impatto sull’obiettivo" },
  appCommon: { ...en.appCommon, userAvatar: "Avatar utente", actions: "Azioni", edit: "Modifica", moreOptions: "Altre opzioni per", cancel: "Annulla", saveChanges: "Salva modifiche", remove: "Rimuovi" },
});
export const appTranslations: Record<Language, AppTranslation> = { en, pt, es, de, fr, nl, it };

const supplementalEn = {
  appBudgetsContent: {
    categories: [
      { category: "Rent", subtitle: "Housing" }, { category: "Supermarket", subtitle: "Food and groceries" }, { category: "Delivery", subtitle: "Delivery and orders" }, { category: "Coffee", subtitle: "Coffee and quick meals" },
      { category: "Energy", subtitle: "Electricity, gas and heating" }, { category: "Internet", subtitle: "Internet and phone" }, { category: "Shopping", subtitle: "Clothes, electronics and others" }, { category: "Subscriptions", subtitle: "Apps and recurring services" },
    ],
    search: "Search budgets", month: "Month", selectMonth: "Select month", newBudget: "New budget", userAvatar: "User avatar", actionsFor: "Actions for", editLimit: "Edit limit",
    nextBestAction: "Next best action", priority: "PRIORITY", recover: "Recover €34.60", recoverDescription: "Shopping is already over the limit. Reduce ~€9/week until the end of the month.", applyAdjustment: "Apply adjustment",
    budgetPace: "Budget pace", budgetUsed: "budget used", monthElapsed: "of the month elapsed", budget: "Budget", monthTime: "Month time", closingForecast: "Closing forecast", forecastText: "≈ €95 above plan if the pace continues.", viewProjection: "View projection →",
    goalImpact: "Goal impact", trip: "TRIP", delayText: "Your budget may delay the goal by ~12 days.", contributionText: "With the suggested adjustment, your €250/month contribution remains protected.", viewGoalImpact: "View goal impact",
  },
} as const;
type SupplementalTranslation = DeepStrings<typeof supplementalEn>;

const supplementalPt: SupplementalTranslation = {
  appBudgetsContent: {
    categories: [
      { category: "Aluguel", subtitle: "Moradia" }, { category: "Supermercado", subtitle: "Alimentação e mercado" }, { category: "Delivery", subtitle: "Delivery e pedidos" }, { category: "Café", subtitle: "Cafés e refeições rápidas" },
      { category: "Energia", subtitle: "Luz, gás e aquecimento" }, { category: "Internet", subtitle: "Internet e telefone" }, { category: "Compras", subtitle: "Roupas, eletrônicos e outros" }, { category: "Assinaturas", subtitle: "Apps e serviços recorrentes" },
    ],
    search: "Buscar orçamentos", month: "Mês", selectMonth: "Selecionar mês", newBudget: "Novo orçamento", userAvatar: "Avatar do usuário", actionsFor: "Ações de", editLimit: "Editar limite",
    nextBestAction: "Próxima melhor ação", priority: "PRIORIDADE", recover: "Recupere €34,60", recoverDescription: "Compras já passou do limite. Reduza ~€9/semana até o fim do mês.", applyAdjustment: "Aplicar ajuste",
    budgetPace: "Ritmo do orçamento", budgetUsed: "orçamento usado", monthElapsed: "do mês passou", budget: "Orçamento", monthTime: "Tempo do mês", closingForecast: "Previsão de fechamento", forecastText: "≈ €95 acima do plano se mantiver o ritmo.", viewProjection: "Ver projeção →",
    goalImpact: "Impacto na meta", trip: "VIAGEM", delayText: "Seu orçamento pode atrasar a meta em ~12 dias.", contributionText: "Com o ajuste sugerido, sua contribuição de €250/mês continua protegida.", viewGoalImpact: "Ver impacto na meta",
  },
};
const supplementalEs: SupplementalTranslation = {
  appBudgetsContent: {
    categories: [
      { category: "Alquiler", subtitle: "Vivienda" }, { category: "Supermercado", subtitle: "Alimentación y supermercado" }, { category: "Delivery", subtitle: "Delivery y pedidos" }, { category: "Café", subtitle: "Café y comidas rápidas" },
      { category: "Energía", subtitle: "Electricidad, gas y calefacción" }, { category: "Internet", subtitle: "Internet y teléfono" }, { category: "Compras", subtitle: "Ropa, electrónica y otros" }, { category: "Suscripciones", subtitle: "Apps y servicios recurrentes" },
    ],
    search: "Buscar presupuestos", month: "Mes", selectMonth: "Seleccionar mes", newBudget: "Nuevo presupuesto", userAvatar: "Avatar del usuario", actionsFor: "Acciones de", editLimit: "Editar límite",
    nextBestAction: "Próxima mejor acción", priority: "PRIORIDAD", recover: "Recupera €34,60", recoverDescription: "Compras ya superó el límite. Reduce ~€9/semana hasta final de mes.", applyAdjustment: "Aplicar ajuste",
    budgetPace: "Ritmo del presupuesto", budgetUsed: "presupuesto usado", monthElapsed: "del mes transcurrido", budget: "Presupuesto", monthTime: "Tiempo del mes", closingForecast: "Previsión de cierre", forecastText: "≈ €95 por encima del plan si se mantiene el ritmo.", viewProjection: "Ver proyección →",
    goalImpact: "Impacto en el objetivo", trip: "VIAJE", delayText: "Tu presupuesto puede retrasar el objetivo ~12 días.", contributionText: "Con el ajuste sugerido, tu aportación de €250/mes sigue protegida.", viewGoalImpact: "Ver impacto en el objetivo",
  },
};

const supplementalDe: SupplementalTranslation = { appBudgetsContent: { ...supplementalEn.appBudgetsContent, search: "Budgets suchen", month: "Monat", selectMonth: "Monat auswählen", newBudget: "Neues Budget", userAvatar: "Benutzeravatar", actionsFor: "Aktionen für", editLimit: "Limit bearbeiten", nextBestAction: "Nächste beste Aktion", priority: "PRIORITÄT", applyAdjustment: "Anpassung anwenden", budgetPace: "Budgettempo", budgetUsed: "Budget verwendet", monthElapsed: "des Monats vergangen", budget: "Budget", monthTime: "Monatsverlauf", closingForecast: "Monatsprognose", viewProjection: "Prognose anzeigen →", goalImpact: "Auswirkung auf das Ziel", viewGoalImpact: "Zielauswirkung anzeigen" } };
const supplementalFr: SupplementalTranslation = { appBudgetsContent: { ...supplementalEn.appBudgetsContent, search: "Rechercher des budgets", month: "Mois", selectMonth: "Choisir le mois", newBudget: "Nouveau budget", userAvatar: "Avatar utilisateur", actionsFor: "Actions pour", editLimit: "Modifier la limite", nextBestAction: "Prochaine action recommandée", priority: "PRIORITÉ", applyAdjustment: "Appliquer l’ajustement", budgetPace: "Rythme du budget", budgetUsed: "budget utilisé", monthElapsed: "du mois écoulé", budget: "Budget", monthTime: "Avancement du mois", closingForecast: "Prévision de fin de mois", viewProjection: "Voir la prévision →", goalImpact: "Impact sur l’objectif", viewGoalImpact: "Voir l’impact sur l’objectif" } };
const supplementalNl: SupplementalTranslation = { appBudgetsContent: { ...supplementalEn.appBudgetsContent, search: "Budgetten zoeken", month: "Maand", selectMonth: "Maand kiezen", newBudget: "Nieuw budget", userAvatar: "Gebruikersavatar", actionsFor: "Acties voor", editLimit: "Limiet bewerken", nextBestAction: "Beste volgende stap", priority: "PRIORITEIT", applyAdjustment: "Aanpassing toepassen", budgetPace: "Budgettempo", budgetUsed: "budget gebruikt", monthElapsed: "van de maand verstreken", budget: "Budget", monthTime: "Maandverloop", closingForecast: "Verwachting voor maandeinde", viewProjection: "Verwachting bekijken →", goalImpact: "Effect op doel", viewGoalImpact: "Effect op doel bekijken" } };
const supplementalIt: SupplementalTranslation = { appBudgetsContent: { ...supplementalEn.appBudgetsContent, search: "Cerca budget", month: "Mese", selectMonth: "Seleziona mese", newBudget: "Nuovo budget", userAvatar: "Avatar utente", actionsFor: "Azioni per", editLimit: "Modifica limite", nextBestAction: "Prossima azione consigliata", priority: "PRIORITÀ", applyAdjustment: "Applica modifica", budgetPace: "Ritmo del budget", budgetUsed: "budget utilizzato", monthElapsed: "del mese trascorso", budget: "Budget", monthTime: "Avanzamento del mese", closingForecast: "Previsione di fine mese", viewProjection: "Vedi previsione →", goalImpact: "Impatto sull’obiettivo", viewGoalImpact: "Vedi impatto sull’obiettivo" } };
export const supplementalTranslations: Record<Language, SupplementalTranslation> = { en: supplementalEn, pt: supplementalPt, es: supplementalEs, de: supplementalDe, fr: supplementalFr, nl: supplementalNl, it: supplementalIt };

const goalsEn = {
  appGoals: {
    title: "Goals", description: "See whether your goal is on track and what action to take to reach it sooner.", newGoal: "New goal", summaryAria: "Goals summary", userAvatar: "User avatar", tripImageAlt: "Trip destination in Italy", yourGoal: "Your goal", editGoal: "Edit goal", goalProgress: "Goal progress", goalDate: "Goal date", nextBestAction: "Next best action", applyPlan: "Apply €83.80/month plan →", savingsPlanTitle: "Plan to free up €83.80/month", columns: ["Category", "Current / month", "Suggested", "Savings"], totalFreed: "Total that can be freed up: €83.80 / month", estimatedCost: "Estimated goal cost", estimatedTotal: "Estimated total", actionPlan: "Action plan", recommendedSteps: "3 recommended steps",
    metrics: [{ label: "Main goal", value: "Trip to Italy", detail: "May 2027 · priority goal" }, { label: "Required contribution", value: "€ 198 / month", detail: "To reach the goal by May 2027" }, { label: "Saved progress", value: "€ 620.00", detail: "25.8% completed · €1,780 remaining" }, { label: "Savings found", value: "€ 83.80 / month", detail: "Could bring the goal forward by ~3 months" }],
    details: { title: "Italy · Rome + Florence", attributes: ["7 days", "Hotel", "Travelling alone"], progress: "25.8%", saved: "€620 of €2,400", remaining: "€1,780 remaining · €198/month", date: "May 2027", status: "In progress" },
    nextActions: ["€20/month is still needed to maintain the required €198 pace.", "AI found €83.80/month in Shopping, Coffee and Subscriptions.", "Direct these savings to the goal and bring the trip forward by ~3 months."],
    categories: ["Shopping", "Coffee", "Subscriptions", "Other"], costs: ["Flights", "Accommodation", "Food", "Transportation", "Extra reserve"],
    steps: [{ title: "Apply suggested savings", copy: "Free up €83.80 per month" }, { title: "Activate €198/month contribution", copy: "Keep the May 2027 deadline" }, { title: "Review in 30 days", copy: "Adjust based on your actual spending" }],
  },
} as const;
type GoalsTranslation = DeepStrings<typeof goalsEn>;
const goalsPt: GoalsTranslation = { appGoals: {
  title: "Objetivos", description: "Veja se sua meta está no ritmo certo e qual ação tomar para chegar mais rápido.", newGoal: "Nova meta", summaryAria: "Resumo dos objetivos", userAvatar: "Avatar do usuário", tripImageAlt: "Destino da viagem para a Itália", yourGoal: "Sua meta", editGoal: "Editar meta", goalProgress: "Progresso da meta", goalDate: "Data da meta", nextBestAction: "Próxima melhor ação", applyPlan: "Aplicar plano de €83,80/mês →", savingsPlanTitle: "Plano para liberar €83,80/mês", columns: ["Categoria", "Atual / mês", "Sugerido", "Economia"], totalFreed: "Total que pode ser liberado: €83,80 / mês", estimatedCost: "Custo estimado da meta", estimatedTotal: "Total estimado", actionPlan: "Plano de ação", recommendedSteps: "3 passos recomendados",
  metrics: [{ label: "Meta principal", value: "Viagem para Itália", detail: "Maio 2027 · meta prioritária" }, { label: "Aporte necessário", value: "€ 198 / mês", detail: "Para chegar à meta em Maio 2027" }, { label: "Progresso guardado", value: "€ 620,00", detail: "25,8% concluído · faltam €1.780" }, { label: "Economia encontrada", value: "€ 83,80 / mês", detail: "Pode antecipar a meta em ~3 meses" }],
  details: { title: "Itália · Roma + Florença", attributes: ["7 dias", "Hotel", "Viajando sozinho"], progress: "25,8%", saved: "€620 de €2.400", remaining: "Faltam €1.780 · €198/mês", date: "Maio 2027", status: "Em andamento" },
  nextActions: ["Faltam €20/mês para o ritmo necessário de €198.", "A IA encontrou €83,80/mês em Compras, Café e Assinaturas.", "Direcione essa economia à meta e antecipe a viagem em ~3 meses."], categories: ["Compras", "Café", "Assinaturas", "Outros"], costs: ["Passagens", "Hospedagem", "Alimentação", "Transporte", "Reserva extra"],
  steps: [{ title: "Aplicar economia sugerida", copy: "Liberar €83,80 por mês" }, { title: "Ativar aporte de €198/mês", copy: "Manter o prazo de Maio 2027" }, { title: "Revisar em 30 dias", copy: "Ajustar conforme os gastos reais" }],
} };
const goalsEs: GoalsTranslation = { appGoals: {
  title: "Objetivos", description: "Comprueba si tu objetivo va al ritmo adecuado y qué acción tomar para alcanzarlo antes.", newGoal: "Nueva meta", summaryAria: "Resumen de objetivos", userAvatar: "Avatar del usuario", tripImageAlt: "Destino del viaje a Italia", yourGoal: "Tu meta", editGoal: "Editar meta", goalProgress: "Progreso de la meta", goalDate: "Fecha de la meta", nextBestAction: "Próxima mejor acción", applyPlan: "Aplicar plan de €83,80/mes →", savingsPlanTitle: "Plan para liberar €83,80/mes", columns: ["Categoría", "Actual / mes", "Sugerido", "Ahorro"], totalFreed: "Total que se puede liberar: €83,80 / mes", estimatedCost: "Coste estimado de la meta", estimatedTotal: "Total estimado", actionPlan: "Plan de acción", recommendedSteps: "3 pasos recomendados",
  metrics: [{ label: "Meta principal", value: "Viaje a Italia", detail: "Mayo 2027 · meta prioritaria" }, { label: "Aporte necesario", value: "€ 198 / mes", detail: "Para alcanzar la meta en mayo de 2027" }, { label: "Progreso ahorrado", value: "€ 620,00", detail: "25,8% completado · faltan €1.780" }, { label: "Ahorro encontrado", value: "€ 83,80 / mes", detail: "Puede adelantar la meta ~3 meses" }],
  details: { title: "Italia · Roma + Florencia", attributes: ["7 días", "Hotel", "Viajando solo"], progress: "25,8%", saved: "€620 de €2.400", remaining: "Faltan €1.780 · €198/mes", date: "Mayo 2027", status: "En progreso" },
  nextActions: ["Faltan €20/mes para mantener el ritmo necesario de €198.", "La IA encontró €83,80/mes en Compras, Café y Suscripciones.", "Dirige este ahorro a la meta y adelanta el viaje ~3 meses."], categories: ["Compras", "Café", "Suscripciones", "Otros"], costs: ["Vuelos", "Alojamiento", "Alimentación", "Transporte", "Reserva extra"],
  steps: [{ title: "Aplicar ahorro sugerido", copy: "Liberar €83,80 al mes" }, { title: "Activar aporte de €198/mes", copy: "Mantener la fecha de mayo de 2027" }, { title: "Revisar en 30 días", copy: "Ajustar según los gastos reales" }],
} };
const goalsDe: GoalsTranslation = { appGoals: {
  ...goalsEn.appGoals, title: "Ziele", description: "Sieh, ob dein Ziel im Plan liegt und welcher Schritt dich schneller dorthin bringt.", newGoal: "Neues Ziel", summaryAria: "Zielübersicht", userAvatar: "Benutzeravatar", tripImageAlt: "Reiseziel in Italien", yourGoal: "Dein Ziel", editGoal: "Ziel bearbeiten", goalProgress: "Zielfortschritt", goalDate: "Zieldatum", nextBestAction: "Nächste beste Aktion", applyPlan: "Plan über €83,80/Monat anwenden →", savingsPlanTitle: "Plan, um €83,80/Monat freizusetzen", columns: ["Kategorie", "Aktuell / Monat", "Vorschlag", "Ersparnis"], totalFreed: "Insgesamt verfügbar: €83,80 / Monat", estimatedCost: "Geschätzte Zielkosten", estimatedTotal: "Geschätzte Gesamtsumme", actionPlan: "Aktionsplan", recommendedSteps: "3 empfohlene Schritte",
  metrics: [{ label: "Hauptziel", value: "Reise nach Italien", detail: "Mai 2027 · vorrangiges Ziel" }, { label: "Erforderlicher Beitrag", value: "€ 198 / Monat", detail: "Um das Ziel bis Mai 2027 zu erreichen" }, { label: "Gesparter Fortschritt", value: "€ 620,00", detail: "25,8 % erreicht · €1.780 verbleiben" }, { label: "Gefundene Einsparung", value: "€ 83,80 / Monat", detail: "Kann das Ziel um etwa 3 Monate vorziehen" }], details: { title: "Italien · Rom + Florenz", attributes: ["7 Tage", "Hotel", "Alleinreisend"], progress: "25,8 %", saved: "€620 von €2.400", remaining: "€1.780 verbleiben · €198/Monat", date: "Mai 2027", status: "In Bearbeitung" }, nextActions: ["Es fehlen noch €20/Monat für den erforderlichen Beitrag von €198.", "Die KI hat €83,80/Monat bei Einkäufen, Kaffee und Abonnements gefunden.", "Leite diese Ersparnis zum Ziel und ziehe die Reise um etwa 3 Monate vor."], categories: ["Einkäufe", "Kaffee", "Abonnements", "Sonstiges"], costs: ["Flüge", "Unterkunft", "Verpflegung", "Transport", "Zusätzliche Reserve"], steps: [{ title: "Vorgeschlagene Einsparung anwenden", copy: "€83,80 pro Monat freisetzen" }, { title: "Beitrag von €198/Monat aktivieren", copy: "Termin Mai 2027 beibehalten" }, { title: "In 30 Tagen prüfen", copy: "An die tatsächlichen Ausgaben anpassen" }],
} };
const goalsFr: GoalsTranslation = { appGoals: {
  ...goalsEn.appGoals, title: "Objectifs", description: "Vérifiez si votre objectif est en bonne voie et quelle action vous permettra de l’atteindre plus vite.", newGoal: "Nouvel objectif", summaryAria: "Résumé des objectifs", userAvatar: "Avatar utilisateur", tripImageAlt: "Destination de voyage en Italie", yourGoal: "Votre objectif", editGoal: "Modifier l’objectif", goalProgress: "Progression de l’objectif", goalDate: "Date de l’objectif", nextBestAction: "Prochaine action recommandée", applyPlan: "Appliquer le plan de 83,80 €/mois →", savingsPlanTitle: "Plan pour libérer 83,80 €/mois", columns: ["Catégorie", "Actuel / mois", "Suggéré", "Économie"], totalFreed: "Total pouvant être libéré : 83,80 € / mois", estimatedCost: "Coût estimé de l’objectif", estimatedTotal: "Total estimé", actionPlan: "Plan d’action", recommendedSteps: "3 étapes recommandées",
  metrics: [{ label: "Objectif principal", value: "Voyage en Italie", detail: "Mai 2027 · objectif prioritaire" }, { label: "Versement requis", value: "198 € / mois", detail: "Pour atteindre l’objectif en mai 2027" }, { label: "Progression épargnée", value: "620,00 €", detail: "25,8 % réalisé · 1 780 € restants" }, { label: "Économies trouvées", value: "83,80 € / mois", detail: "Peut avancer l’objectif d’environ 3 mois" }], details: { title: "Italie · Rome + Florence", attributes: ["7 jours", "Hôtel", "Voyage en solo"], progress: "25,8 %", saved: "620 € sur 2 400 €", remaining: "1 780 € restants · 198 €/mois", date: "Mai 2027", status: "En cours" }, nextActions: ["Il manque encore 20 €/mois pour maintenir le rythme requis de 198 €.", "L’IA a identifié 83,80 €/mois dans les achats, le café et les abonnements.", "Affectez ces économies à l’objectif et avancez le voyage d’environ 3 mois."], categories: ["Achats", "Café", "Abonnements", "Autres"], costs: ["Vols", "Hébergement", "Repas", "Transport", "Réserve supplémentaire"], steps: [{ title: "Appliquer les économies suggérées", copy: "Libérer 83,80 € par mois" }, { title: "Activer le versement de 198 €/mois", copy: "Conserver l’échéance de mai 2027" }, { title: "Réévaluer dans 30 jours", copy: "Ajuster selon les dépenses réelles" }],
} };
const goalsNl: GoalsTranslation = { appGoals: {
  ...goalsEn.appGoals, title: "Doelen", description: "Bekijk of je doel op schema ligt en welke stap je sneller vooruithelpt.", newGoal: "Nieuw doel", summaryAria: "Doelenoverzicht", userAvatar: "Gebruikersavatar", tripImageAlt: "Reisbestemming in Italië", yourGoal: "Je doel", editGoal: "Doel bewerken", goalProgress: "Voortgang doel", goalDate: "Doeldatum", nextBestAction: "Beste volgende stap", applyPlan: "Plan van € 83,80/maand toepassen →", savingsPlanTitle: "Plan om € 83,80/maand vrij te maken", columns: ["Categorie", "Huidig / maand", "Voorgesteld", "Besparing"], totalFreed: "Totaal vrij te maken: € 83,80 / maand", estimatedCost: "Geschatte kosten van doel", estimatedTotal: "Geschat totaal", actionPlan: "Actieplan", recommendedSteps: "3 aanbevolen stappen",
  metrics: [{ label: "Belangrijkste doel", value: "Reis naar Italië", detail: "Mei 2027 · prioritair doel" }, { label: "Benodigde inleg", value: "€ 198 / maand", detail: "Om het doel in mei 2027 te bereiken" }, { label: "Gespaarde voortgang", value: "€ 620,00", detail: "25,8% voltooid · € 1.780 resterend" }, { label: "Gevonden besparing", value: "€ 83,80 / maand", detail: "Kan het doel ongeveer 3 maanden vervroegen" }], details: { title: "Italië · Rome + Florence", attributes: ["7 dagen", "Hotel", "Alleenreizend"], progress: "25,8%", saved: "€ 620 van € 2.400", remaining: "€ 1.780 resterend · € 198/maand", date: "Mei 2027", status: "Bezig" }, nextActions: ["Er is nog € 20/maand nodig voor het vereiste tempo van € 198.", "AI vond € 83,80/maand bij Winkelen, Koffie en Abonnementen.", "Zet deze besparing in voor het doel en haal de reis ongeveer 3 maanden naar voren."], categories: ["Winkelen", "Koffie", "Abonnementen", "Overig"], costs: ["Vluchten", "Accommodatie", "Eten", "Vervoer", "Extra reserve"], steps: [{ title: "Voorgestelde besparing toepassen", copy: "€ 83,80 per maand vrijmaken" }, { title: "Inleg van € 198/maand activeren", copy: "Deadline mei 2027 behouden" }, { title: "Over 30 dagen bekijken", copy: "Aanpassen aan je werkelijke uitgaven" }],
} };
const goalsIt: GoalsTranslation = { appGoals: {
  ...goalsEn.appGoals, title: "Obiettivi", description: "Verifica se il tuo obiettivo è in linea e quale azione può aiutarti a raggiungerlo prima.", newGoal: "Nuovo obiettivo", summaryAria: "Riepilogo obiettivi", userAvatar: "Avatar utente", tripImageAlt: "Destinazione di viaggio in Italia", yourGoal: "Il tuo obiettivo", editGoal: "Modifica obiettivo", goalProgress: "Avanzamento obiettivo", goalDate: "Data obiettivo", nextBestAction: "Prossima azione consigliata", applyPlan: "Applica il piano da 83,80 €/mese →", savingsPlanTitle: "Piano per liberare 83,80 €/mese", columns: ["Categoria", "Attuale / mese", "Suggerito", "Risparmio"], totalFreed: "Totale liberabile: 83,80 € / mese", estimatedCost: "Costo stimato dell’obiettivo", estimatedTotal: "Totale stimato", actionPlan: "Piano d’azione", recommendedSteps: "3 passaggi consigliati",
  metrics: [{ label: "Obiettivo principale", value: "Viaggio in Italia", detail: "Maggio 2027 · obiettivo prioritario" }, { label: "Contributo richiesto", value: "198 € / mese", detail: "Per raggiungere l’obiettivo entro maggio 2027" }, { label: "Progresso risparmiato", value: "620,00 €", detail: "25,8% completato · 1.780 € rimanenti" }, { label: "Risparmio individuato", value: "83,80 € / mese", detail: "Può anticipare l’obiettivo di circa 3 mesi" }], details: { title: "Italia · Roma + Firenze", attributes: ["7 giorni", "Hotel", "Viaggio in solitaria"], progress: "25,8%", saved: "620 € su 2.400 €", remaining: "1.780 € rimanenti · 198 €/mese", date: "Maggio 2027", status: "In corso" }, nextActions: ["Servono ancora 20 €/mese per mantenere il ritmo richiesto di 198 €.", "L’IA ha individuato 83,80 €/mese in Acquisti, Caffè e Abbonamenti.", "Destina questo risparmio all’obiettivo e anticipa il viaggio di circa 3 mesi."], categories: ["Acquisti", "Caffè", "Abbonamenti", "Altro"], costs: ["Voli", "Alloggio", "Cibo", "Trasporti", "Riserva extra"], steps: [{ title: "Applica il risparmio suggerito", copy: "Libera 83,80 € al mese" }, { title: "Attiva il contributo di 198 €/mese", copy: "Mantieni la scadenza di maggio 2027" }, { title: "Rivedi tra 30 giorni", copy: "Adatta alle spese effettive" }],
} };
export const goalTranslations: Record<Language, GoalsTranslation> = { en: goalsEn, pt: goalsPt, es: goalsEs, de: goalsDe, fr: goalsFr, nl: goalsNl, it: goalsIt };
