import type { Language } from "./config";
export function getCsvImportCopy(language: Language) {
  const copy = language === "pt" ? {
    title: "Importar extrato", description: "Envie um arquivo CSV para revisar suas transações antes de adicioná-las ao MoneyPilot.", choose: "Selecionar arquivo CSV", privacy: "Seu arquivo é processado localmente e não é enviado para servidores nesta etapa.", found: "Transações encontradas", errors: "Com erro", income: "Receitas detectadas", expenses: "Despesas detectadas", total: "Total de registros", review: "Revisar transações", ready: "Arquivo preparado para a etapa de revisão.", cancel: "Cancelar", statusReady: "Pronta", statusReview: "Revisar",
  } : language === "es" ? {
    title: "Importar extracto", description: "Envía un archivo CSV para revisar tus transacciones antes de añadirlas a MoneyPilot.", choose: "Seleccionar archivo CSV", privacy: "Tu archivo se procesa localmente y no se envía a servidores en esta etapa.", found: "Transacciones encontradas", errors: "Con error", income: "Ingresos detectados", expenses: "Gastos detectados", total: "Total de registros", review: "Revisar transacciones", ready: "Archivo preparado para la etapa de revisión.", cancel: "Cancelar", statusReady: "Lista", statusReview: "Revisar",
  } : language === "de" ? {
    title: "Kontoauszug importieren", description: "Wähle eine CSV-Datei, um die Transaktionen vor dem Hinzufügen zu prüfen.", choose: "CSV-Datei auswählen", privacy: "Deine Datei wird lokal verarbeitet und in diesem Schritt nicht an Server gesendet.", found: "Transaktionen gefunden", errors: "Mit Fehlern", income: "Einnahmen erkannt", expenses: "Ausgaben erkannt", total: "Datensätze gesamt", review: "Transaktionen prüfen", ready: "Datei für die Prüfung vorbereitet.", cancel: "Abbrechen", statusReady: "Bereit", statusReview: "Prüfen",
  } : language === "fr" ? {
    title: "Importer un relevé", description: "Sélectionnez un fichier CSV pour vérifier les transactions avant de les ajouter.", choose: "Sélectionner un fichier CSV", privacy: "Votre fichier est traité localement et n’est pas envoyé à un serveur à cette étape.", found: "Transactions trouvées", errors: "Avec erreurs", income: "Revenus détectés", expenses: "Dépenses détectées", total: "Total des lignes", review: "Vérifier les transactions", ready: "Fichier prêt pour la vérification.", cancel: "Annuler", statusReady: "Prête", statusReview: "Vérifier",
  } : language === "nl" ? {
    title: "Afschrift importeren", description: "Selecteer een CSV-bestand om transacties te controleren voordat je ze toevoegt.", choose: "CSV-bestand selecteren", privacy: "Je bestand wordt lokaal verwerkt en in deze stap niet naar servers gestuurd.", found: "Transacties gevonden", errors: "Met fouten", income: "Inkomen herkend", expenses: "Uitgaven herkend", total: "Totaal aantal regels", review: "Transacties controleren", ready: "Bestand voorbereid voor controle.", cancel: "Annuleren", statusReady: "Gereed", statusReview: "Controleren",
  } : language === "it" ? {
    title: "Importa estratto conto", description: "Seleziona un file CSV per verificare le transazioni prima di aggiungerle.", choose: "Seleziona file CSV", privacy: "Il file viene elaborato localmente e non viene inviato ai server in questa fase.", found: "Transazioni trovate", errors: "Con errori", income: "Entrate rilevate", expenses: "Spese rilevate", total: "Totale righe", review: "Rivedi transazioni", ready: "File pronto per la revisione.", cancel: "Annulla", statusReady: "Pronta", statusReview: "Rivedi",
  } : {
    title: "Import statement", description: "Send a CSV file to review your transactions before adding them to MoneyPilot.", choose: "Select CSV file", privacy: "Your file is processed locally and is not sent to servers at this stage.", found: "Transactions found", errors: "With errors", income: "Income detected", expenses: "Expenses detected", total: "Total records", review: "Review transactions", ready: "File prepared for the review stage.", cancel: "Cancel", statusReady: "Ready", statusReview: "Review",
  };
  const reviewCopy = language === "pt"
    ? { reviewTitle: "Revisar transações", reviewDescription: "Confira os dados detectados antes de adicioná-los ao MoneyPilot.", duplicate: "Possível duplicata", selected: "Selecionadas", selectValid: "Selecionar todas as válidas", clear: "Limpar seleção", complete: "Importação concluída", view: "Ver transações", notSpecified: "Não informado", importedOrigin: "Importado" }
    : language === "es"
      ? { reviewTitle: "Revisa las transacciones", reviewDescription: "Edita los datos y elige qué transacciones importar.", duplicate: "Posible duplicado", selected: "Seleccionadas", selectValid: "Seleccionar válidas", clear: "Limpiar selección", complete: "Importación completada", view: "Ver transacciones", notSpecified: "No especificado", importedOrigin: "Importado" }
      : language === "de" ? { reviewTitle: "Transaktionen prüfen", reviewDescription: "Bearbeite die Daten und wähle die zu importierenden Transaktionen.", duplicate: "Mögliches Duplikat", selected: "Ausgewählt", selectValid: "Gültige auswählen", clear: "Auswahl löschen", complete: "Import abgeschlossen", view: "Transaktionen anzeigen", notSpecified: "Nicht angegeben", importedOrigin: "Importiert" }
      : language === "fr" ? { reviewTitle: "Vérifier les transactions", reviewDescription: "Modifiez les données et choisissez les transactions à importer.", duplicate: "Doublon possible", selected: "Sélectionnées", selectValid: "Sélectionner les valides", clear: "Effacer la sélection", complete: "Importation terminée", view: "Voir les transactions", notSpecified: "Non indiqué", importedOrigin: "Importé" }
      : language === "nl" ? { reviewTitle: "Transacties controleren", reviewDescription: "Bewerk de gegevens en kies welke transacties je importeert.", duplicate: "Mogelijk dubbel", selected: "Geselecteerd", selectValid: "Geldige selecteren", clear: "Selectie wissen", complete: "Import voltooid", view: "Transacties bekijken", notSpecified: "Niet opgegeven", importedOrigin: "Geïmporteerd" }
      : language === "it" ? { reviewTitle: "Rivedi transazioni", reviewDescription: "Modifica i dati e scegli quali transazioni importare.", duplicate: "Possibile duplicato", selected: "Selezionate", selectValid: "Seleziona valide", clear: "Cancella selezione", complete: "Importazione completata", view: "Vedi transazioni", notSpecified: "Non specificato", importedOrigin: "Importato" }
      : { reviewTitle: "Review transactions", reviewDescription: "Edit the data and choose which transactions to import.", duplicate: "Possible duplicate", selected: "Selected", selectValid: "Select valid", clear: "Clear selection", complete: "Import complete", view: "View transactions", notSpecified: "Not specified", importedOrigin: "Imported" };
  const analysisCopy = language === "pt"
    ? { title: "Analisando extrato", subtitle: "Estamos preparando suas transações para revisão.", analyzing: "Analisando", progress: "concluído", localTitle: "Processamento local e privado", localText: "Nenhum dado está sendo enviado para servidores.", retry: "Tentar novamente", other: "Selecionar outro arquivo", lines: "linhas detectadas", steps: ["Lendo arquivo", "Identificando colunas", "Normalizando datas", "Detectando receitas e despesas", "Preparando transações para revisão"], done: "Concluído", processing: "Processando", waiting: "Aguardando" }
    : language === "es"
      ? { title: "Analizando extracto", subtitle: "Estamos preparando tus transacciones para revisión.", analyzing: "Analizando", progress: "completado", localTitle: "Procesamiento local y privado", localText: "No se envían datos a servidores.", retry: "Intentar de nuevo", other: "Seleccionar otro archivo", lines: "líneas detectadas", steps: ["Leyendo archivo", "Identificando columnas", "Normalizando fechas", "Detectando ingresos y gastos", "Preparando transacciones para revisión"], done: "Completado", processing: "Procesando", waiting: "Esperando" }
      : language === "de" ? { title: "Kontoauszug wird analysiert", subtitle: "Wir bereiten deine Transaktionen zur Prüfung vor.", analyzing: "Analysieren", progress: "abgeschlossen", localTitle: "Lokale und private Verarbeitung", localText: "Es werden keine Daten an Server gesendet.", retry: "Erneut versuchen", other: "Andere Datei auswählen", lines: "Zeilen erkannt", steps: ["Datei lesen", "Spalten erkennen", "Daten normalisieren", "Einnahmen und Ausgaben erkennen", "Transaktionen zur Prüfung vorbereiten"], done: "Abgeschlossen", processing: "Wird verarbeitet", waiting: "Wartet" }
      : language === "fr" ? { title: "Analyse du relevé", subtitle: "Nous préparons vos transactions pour la vérification.", analyzing: "Analyse", progress: "terminé", localTitle: "Traitement local et privé", localText: "Aucune donnée n’est envoyée à un serveur.", retry: "Réessayer", other: "Choisir un autre fichier", lines: "lignes détectées", steps: ["Lecture du fichier", "Identification des colonnes", "Normalisation des dates", "Détection des revenus et dépenses", "Préparation des transactions"], done: "Terminé", processing: "Traitement", waiting: "En attente" }
      : language === "nl" ? { title: "Afschrift analyseren", subtitle: "We bereiden je transacties voor op controle.", analyzing: "Analyseren", progress: "voltooid", localTitle: "Lokale en privéverwerking", localText: "Er worden geen gegevens naar servers gestuurd.", retry: "Opnieuw proberen", other: "Ander bestand selecteren", lines: "regels herkend", steps: ["Bestand lezen", "Kolommen herkennen", "Datums normaliseren", "Inkomen en uitgaven herkennen", "Transacties voorbereiden"], done: "Voltooid", processing: "Verwerken", waiting: "Wachten" }
      : language === "it" ? { title: "Analisi estratto conto", subtitle: "Stiamo preparando le transazioni per la revisione.", analyzing: "Analisi", progress: "completato", localTitle: "Elaborazione locale e privata", localText: "Nessun dato viene inviato ai server.", retry: "Riprova", other: "Seleziona un altro file", lines: "righe rilevate", steps: ["Lettura file", "Identificazione colonne", "Normalizzazione date", "Rilevamento entrate e spese", "Preparazione transazioni"], done: "Completato", processing: "Elaborazione", waiting: "In attesa" }
      : { title: "Analyzing statement", subtitle: "We are preparing your transactions for review.", analyzing: "Analyzing", progress: "complete", localTitle: "Local and private processing", localText: "No data is being sent to servers.", retry: "Try again", other: "Select another file", lines: "lines detected", steps: ["Reading file", "Identifying columns", "Normalizing dates", "Detecting income and expenses", "Preparing transactions for review"], done: "Complete", processing: "Processing", waiting: "Waiting" };
  const csvText = {
    en: { invalid: "Select a valid CSV file.", empty: "The selected file is empty.", large: "The file exceeds the 5 MB limit.", date: "Date", description: "Description", category: "Category", type: "Type", value: "Value", status: "Status", expense: "Expense", income: "Income", added: "transactions were added to MoneyPilot.", steps: "Select ✓ · Analyze ✓ · Review ✓ · Import ✓", importCount: (count: number) => `Import ${count} transactions` }, pt: { invalid: "Selecione um arquivo CSV válido.", empty: "O arquivo selecionado está vazio.", large: "O arquivo excede o limite de 5 MB.", date: "Data", description: "Descrição", category: "Categoria", type: "Tipo", value: "Valor", status: "Status", expense: "Despesa", income: "Receita", added: "transações foram adicionadas ao MoneyPilot.", steps: "Selecionar ✓ · Analisar ✓ · Revisar ✓ · Importar ✓", importCount: (count: number) => `Importar ${count} transações` }, es: { invalid: "Selecciona un archivo CSV válido.", empty: "El archivo seleccionado está vacío.", large: "El archivo supera el límite de 5 MB.", date: "Fecha", description: "Descripción", category: "Categoría", type: "Tipo", value: "Valor", status: "Estado", expense: "Gasto", income: "Ingreso", added: "transacciones fueron añadidas a MoneyPilot.", steps: "Seleccionar ✓ · Analizar ✓ · Revisar ✓ · Importar ✓", importCount: (count: number) => `Importar ${count} transacciones` },
    de: { invalid: "Wähle eine gültige CSV-Datei aus.", empty: "Die ausgewählte Datei ist leer.", large: "Die Datei überschreitet das Limit von 5 MB.", date: "Datum", description: "Beschreibung", category: "Kategorie", type: "Typ", value: "Betrag", status: "Status", expense: "Ausgabe", income: "Einnahme", added: "Transaktionen wurden zu MoneyPilot hinzugefügt.", steps: "Auswählen ✓ · Analysieren ✓ · Prüfen ✓ · Importieren ✓", importCount: (count: number) => `${count} Transaktionen importieren` }, fr: { invalid: "Sélectionnez un fichier CSV valide.", empty: "Le fichier sélectionné est vide.", large: "Le fichier dépasse la limite de 5 Mo.", date: "Date", description: "Description", category: "Catégorie", type: "Type", value: "Montant", status: "État", expense: "Dépense", income: "Revenu", added: "transactions ont été ajoutées à MoneyPilot.", steps: "Sélectionner ✓ · Analyser ✓ · Vérifier ✓ · Importer ✓", importCount: (count: number) => `Importer ${count} transactions` }, nl: { invalid: "Selecteer een geldig CSV-bestand.", empty: "Het geselecteerde bestand is leeg.", large: "Het bestand overschrijdt de limiet van 5 MB.", date: "Datum", description: "Beschrijving", category: "Categorie", type: "Type", value: "Bedrag", status: "Status", expense: "Uitgave", income: "Inkomen", added: "transacties zijn aan MoneyPilot toegevoegd.", steps: "Selecteren ✓ · Analyseren ✓ · Controleren ✓ · Importeren ✓", importCount: (count: number) => `${count} transacties importeren` }, it: { invalid: "Seleziona un file CSV valido.", empty: "Il file selezionato è vuoto.", large: "Il file supera il limite di 5 MB.", date: "Data", description: "Descrizione", category: "Categoria", type: "Tipo", value: "Importo", status: "Stato", expense: "Spesa", income: "Entrata", added: "transazioni sono state aggiunte a MoneyPilot.", steps: "Seleziona ✓ · Analizza ✓ · Rivedi ✓ · Importa ✓", importCount: (count: number) => `Importa ${count} transazioni` },
  }[language];

return { copy, reviewCopy, analysisCopy, csvText };
}

export const csvImportLabels = {
  pt: { selectAll: "Selecionar todas", deselectAll: "Desmarcar todas", allSelected: "Todas selecionadas", partialSelection: "Seleção parcial", previous: "Anterior", next: "Próxima", steps: ["Selecionar", "Analisar", "Revisar", "Importar"], drop: "Arraste e solte seu arquivo CSV aqui", browse: "ou selecione um arquivo do seu computador", limit: "CSV · máximo 5 MB", back: "Voltar", importing: "Importando…", summary: "Resumo da importação", ignored: "Duplicatas ignoradas", duplicates: "Possíveis duplicatas foram desmarcadas automaticamente. Você pode selecioná-las para importar.", note: "As novas transações já participam dos filtros, busca e relatórios.", analysisError: "Não foi possível analisar o CSV. Confira os cabeçalhos, as aspas e o conteúdo do arquivo e tente novamente.", importError: "Não foi possível concluir a importação. Revise os dados e tente novamente.", dateError: "Data inválida. Use AAAA-MM-DD ou DD/MM/AAAA.", descriptionError: "Descrição ausente", amountError: "Valor inválido", typeError: "Tipo não reconhecido" },
  en: { selectAll: "Select all", deselectAll: "Deselect all", allSelected: "All selected", partialSelection: "Partial selection", previous: "Previous", next: "Next", steps: ["Select", "Analyze", "Review", "Import"], drop: "Drag and drop your CSV file here", browse: "or select a file from your computer", limit: "CSV · maximum 5 MB", back: "Back", importing: "Importing…", summary: "Import summary", ignored: "Duplicates ignored", duplicates: "Possible duplicates were automatically deselected. You may select them to import.", note: "New transactions are now included in filters, search and reports.", analysisError: "Unable to analyze the CSV. Check headers, quotes and file contents, then try again.", importError: "Unable to complete the import. Review the data and try again.", dateError: "Invalid date. Use YYYY-MM-DD or DD/MM/YYYY.", descriptionError: "Missing description", amountError: "Invalid amount", typeError: "Unrecognized type" },
  es: { selectAll: "Seleccionar todas", deselectAll: "Desmarcar todas", allSelected: "Todas seleccionadas", partialSelection: "Selección parcial", previous: "Anterior", next: "Siguiente", steps: ["Seleccionar", "Analizar", "Revisar", "Importar"], drop: "Arrastra tu archivo CSV aquí", browse: "o selecciona un archivo de tu ordenador", limit: "CSV · máximo 5 MB", back: "Volver", importing: "Importando…", summary: "Resumen de importación", ignored: "Duplicados ignorados", duplicates: "Los posibles duplicados se desmarcaron automáticamente. Puedes seleccionarlos para importar.", note: "Las nuevas transacciones ya aparecen en filtros, búsqueda e informes.", analysisError: "No se pudo analizar el CSV. Revisa encabezados, comillas y contenido e inténtalo de nuevo.", importError: "No se pudo completar la importación. Revisa los datos e inténtalo de nuevo.", dateError: "Fecha inválida. Usa AAAA-MM-DD o DD/MM/AAAA.", descriptionError: "Falta la descripción", amountError: "Importe inválido", typeError: "Tipo no reconocido" },
  de: { selectAll: "Alle auswählen", deselectAll: "Alle abwählen", allSelected: "Alle ausgewählt", partialSelection: "Teilweise ausgewählt", previous: "Zurück", next: "Weiter", steps: ["Auswählen", "Analysieren", "Prüfen", "Importieren"], drop: "CSV-Datei hier ablegen", browse: "oder eine Datei auf deinem Computer auswählen", limit: "CSV · maximal 5 MB", back: "Zurück", importing: "Importieren…", summary: "Importübersicht", ignored: "Ignorierte Duplikate", duplicates: "Mögliche Duplikate wurden abgewählt. Du kannst sie zum Import auswählen.", note: "Neue Transaktionen erscheinen jetzt in Filtern, Suche und Berichten.", analysisError: "CSV konnte nicht analysiert werden. Prüfe Überschriften, Anführungszeichen und Inhalt und versuche es erneut.", importError: "Import fehlgeschlagen. Prüfe die Daten und versuche es erneut.", dateError: "Ungültiges Datum. Verwende JJJJ-MM-TT oder TT/MM/JJJJ.", descriptionError: "Beschreibung fehlt", amountError: "Ungültiger Betrag", typeError: "Unbekannter Typ" },
  fr: { selectAll: "Tout sélectionner", deselectAll: "Tout désélectionner", allSelected: "Tout est sélectionné", partialSelection: "Sélection partielle", previous: "Précédente", next: "Suivante", steps: ["Sélectionner", "Analyser", "Vérifier", "Importer"], drop: "Déposez votre fichier CSV ici", browse: "ou sélectionnez un fichier sur votre ordinateur", limit: "CSV · maximum 5 Mo", back: "Retour", importing: "Importation…", summary: "Résumé de l’importation", ignored: "Doublons ignorés", duplicates: "Les doublons possibles ont été désélectionnés. Vous pouvez les sélectionner pour les importer.", note: "Les nouvelles transactions figurent dans les filtres, la recherche et les rapports.", analysisError: "Impossible d’analyser le CSV. Vérifiez les en-têtes, les guillemets et le contenu, puis réessayez.", importError: "Importation impossible. Vérifiez les données et réessayez.", dateError: "Date invalide. Utilisez AAAA-MM-JJ ou JJ/MM/AAAA.", descriptionError: "Description manquante", amountError: "Montant invalide", typeError: "Type inconnu" },
  nl: { selectAll: "Alles selecteren", deselectAll: "Alles deselecteren", allSelected: "Alles geselecteerd", partialSelection: "Gedeeltelijke selectie", previous: "Vorige", next: "Volgende", steps: ["Selecteren", "Analyseren", "Controleren", "Importeren"], drop: "Sleep je CSV-bestand hierheen", browse: "of selecteer een bestand op je computer", limit: "CSV · maximaal 5 MB", back: "Terug", importing: "Importeren…", summary: "Importoverzicht", ignored: "Genegeerde duplicaten", duplicates: "Mogelijke duplicaten zijn uitgevinkt. Je kunt ze selecteren om te importeren.", note: "Nieuwe transacties verschijnen nu in filters, zoekresultaten en rapporten.", analysisError: "CSV analyseren mislukt. Controleer koppen, aanhalingstekens en inhoud en probeer opnieuw.", importError: "Import mislukt. Controleer de gegevens en probeer opnieuw.", dateError: "Ongeldige datum. Gebruik JJJJ-MM-DD of DD/MM/JJJJ.", descriptionError: "Beschrijving ontbreekt", amountError: "Ongeldig bedrag", typeError: "Onbekend type" },
  it: { selectAll: "Seleziona tutte", deselectAll: "Deseleziona tutte", allSelected: "Tutte selezionate", partialSelection: "Selezione parziale", previous: "Precedente", next: "Successiva", steps: ["Seleziona", "Analizza", "Rivedi", "Importa"], drop: "Trascina qui il tuo file CSV", browse: "o seleziona un file dal computer", limit: "CSV · massimo 5 MB", back: "Indietro", importing: "Importazione…", summary: "Riepilogo importazione", ignored: "Duplicati ignorati", duplicates: "I possibili duplicati sono stati deselezionati. Puoi selezionarli per importarli.", note: "Le nuove transazioni sono incluse in filtri, ricerca e report.", analysisError: "Impossibile analizzare il CSV. Controlla intestazioni, virgolette e contenuto e riprova.", importError: "Importazione non riuscita. Controlla i dati e riprova.", dateError: "Data non valida. Usa AAAA-MM-GG o GG/MM/AAAA.", descriptionError: "Descrizione mancante", amountError: "Importo non valido", typeError: "Tipo sconosciuto" },
} satisfies Record<Language, { selectAll: string; deselectAll: string; allSelected: string; partialSelection: string; previous: string; next: string; steps: string[]; drop: string; browse: string; limit: string; back: string; importing: string; summary: string; ignored: string; duplicates: string; note: string; analysisError: string; importError: string; dateError: string; descriptionError: string; amountError: string; typeError: string }>;
