import type { Language } from "@/components/LanguageProvider";

export type DashboardCopy = {
  netCashFlow: string; thisMonth: string; currentMonth: string; netCashFlowDescription: string; monthlyFlow: string; addStartingBalance: string; balanceUnavailable: string; accountBalanceUnavailable: string; trendUnavailable: string; historicalSeriesUnavailable: string; distributionUnavailable: string; valuesHidden: string;
  dailyNetFlow: string; dailyIncome: string; dailyExpenses: string; cumulativeNetFlow: string; cumulativeIncome: string; cumulativeExpenses: string; noMovementsInPeriod: string;
  incomeAveragePerDayHelp: string; incomeIndicatorUnavailable: string; noIncomeRecorded: string;
  noSpendingData: string; noSpendingThisMonth: string; noSpendingRecorded: string; spendingCategoriesPlaceholder: string; largestExpense: string; expenseShare: string; other: string; uncategorized: string;
  noGoalYet: string; createGoalHelp: string; createGoal: string; goalCompleted: string; reviewTargetDate: string; reviewNeeded: string; planActive: string; onSchedule: string; saved: string; target: string; remaining: string; requiredPerMonth: string; targetLabel: string; planTargetLabel: string; active: string;
  noScheduledBills: string; scheduledBillsUnavailable: string; noBudgetYet: string; noBudgetRecorded: string; noBudgetRecordedDescription: string; createBudget: string; onTrackStatus: string; withinBudgetProjection: string; withinBudgetActual: string; needsAttention: string; aboveBudgetProjection: string; aboveBudgetActual: string; createBudgetProjection: string; budgetLabel: string; projectedLabel: string; actualLabel: string; moneyPilotInsight: string; currentPeriod: string; budgetUsedLabel: string; budgetSpentLabel: string; budgetExceeded: string; budgetExceededBy: string; budgetUsageUnavailable: string;
  nextActions: Record<"recoveryPlan" | "reviewBudget" | "updateGoalDate" | "reviewGoalPlan" | "insufficientCurrentData" | "createBudget" | "createGoal" | "buildSavingsPlan" | "followSavingsPlan" | "goalCompleted" | "noAction", { title: string; description: string; cta: string }>;
};

export const activeBudgetPlanCopyByLanguage: Record<Language, { title: string; description: string; cta: string; targetLabel: string; reductionAtSaveLabel: string }> = {
  en: { title: "Remaining spending target active", description: "This is a saved spending plan for the rest of the month, not an account balance or realized savings.", cta: "Review budget", targetLabel: "Remaining spending target", reductionAtSaveLabel: "Reduction from projection when saved" },
  pt: { title: "Meta de gasto restante ativa", description: "Este é um planejamento de gasto salvo para o restante do mês, não um saldo em conta nem uma economia realizada.", cta: "Revisar orçamento", targetLabel: "Meta de gasto restante", reductionAtSaveLabel: "Redução em relação à projeção ao salvar" },
  es: { title: "Objetivo de gasto restante activo", description: "Este es un plan de gasto guardado para el resto del mes, no un saldo de cuenta ni un ahorro realizado.", cta: "Revisar presupuesto", targetLabel: "Objetivo de gasto restante", reductionAtSaveLabel: "Reducción frente a la proyección al guardarlo" },
  de: { title: "Restliches Ausgabenziel aktiv", description: "Dies ist ein gespeicherter Ausgabenplan für den restlichen Monat, kein Kontostand oder bereits erzielte Ersparnis.", cta: "Budget prüfen", targetLabel: "Restliches Ausgabenziel", reductionAtSaveLabel: "Reduzierung gegenüber der Prognose beim Speichern" },
  fr: { title: "Objectif de dépense restante actif", description: "Il s’agit d’un plan de dépenses enregistré pour le reste du mois, et non d’un solde de compte ou d’une économie réalisée.", cta: "Vérifier le budget", targetLabel: "Objectif de dépense restante", reductionAtSaveLabel: "Réduction par rapport à la projection lors de l’enregistrement" },
  nl: { title: "Resterend uitgavendoel actief", description: "Dit is een opgeslagen uitgavenplan voor de rest van de maand, geen rekeningsaldo of gerealiseerde besparing.", cta: "Budget bekijken", targetLabel: "Resterend uitgavendoel", reductionAtSaveLabel: "Verlaging ten opzichte van de prognose bij opslaan" },
  it: { title: "Obiettivo di spesa restante attivo", description: "Questo è un piano di spesa salvato per il resto del mese, non un saldo disponibile né un risparmio realizzato.", cta: "Rivedi budget", targetLabel: "Obiettivo di spesa restante", reductionAtSaveLabel: "Riduzione rispetto alla previsione al salvataggio" },
};

type PeriodActionCopy = Record<"historicalOverBudget" | "historicalWithinBudget" | "historicalNoBudget" | "historicalInsufficientData" | "futurePeriod", { title: string; description: string; cta: string }>;

export const periodActionCopyByLanguage: Record<Language, PeriodActionCopy> = {
  en: {
    historicalOverBudget: { title: "Period closed over budget", description: "Actual spending exceeded the spending plan for this period.", cta: "Review budget" },
    historicalWithinBudget: { title: "Period closed within budget", description: "Net cash flow is income minus expenses; it is not an account balance or unused budget.", cta: "View budget" },
    historicalNoBudget: { title: "Period closed without a budget", description: "Net cash flow shows the realized result, not an account balance or a spending plan.", cta: "View period" },
    historicalInsufficientData: { title: "No period analysis available", description: "This completed period has no transactions to support an analysis.", cta: "" },
    futurePeriod: { title: "Future period", description: "There is not enough realized data to generate a recommendation for this period.", cta: "" },
  },
  pt: {
    historicalOverBudget: { title: "Período encerrado acima do orçamento", description: "As despesas realizadas ultrapassaram o planejamento de gastos deste período.", cta: "Revisar orçamento" },
    historicalWithinBudget: { title: "Período encerrado dentro do orçamento", description: "O fluxo líquido é receitas menos despesas; não é saldo em conta nem sobra do orçamento.", cta: "Ver orçamento" },
    historicalNoBudget: { title: "Período encerrado sem orçamento", description: "O fluxo líquido mostra o resultado realizado, não saldo em conta nem planejamento de gastos.", cta: "Ver período" },
    historicalInsufficientData: { title: "Análise indisponível", description: "Este período encerrado não tem transações para sustentar uma análise.", cta: "" },
    futurePeriod: { title: "Período futuro", description: "Ainda não há dados realizados suficientes para gerar uma recomendação deste período.", cta: "" },
  },
  es: {
    historicalOverBudget: { title: "Período cerrado por encima del presupuesto", description: "El gasto real superó el plan de gastos de este período.", cta: "Revisar presupuesto" },
    historicalWithinBudget: { title: "Período cerrado dentro del presupuesto", description: "El flujo neto son ingresos menos gastos; no es saldo de cuenta ni presupuesto sin usar.", cta: "Ver presupuesto" },
    historicalNoBudget: { title: "Período cerrado sin presupuesto", description: "El flujo neto muestra el resultado realizado, no un saldo de cuenta ni un plan de gastos.", cta: "Ver período" },
    historicalInsufficientData: { title: "Análisis no disponible", description: "Este período cerrado no tiene transacciones suficientes para un análisis.", cta: "" },
    futurePeriod: { title: "Período futuro", description: "Aún no hay datos realizados suficientes para generar una recomendación.", cta: "" },
  },
  de: {
    historicalOverBudget: { title: "Zeitraum über Budget abgeschlossen", description: "Die tatsächlichen Ausgaben überschritten den Ausgabenplan dieses Zeitraums.", cta: "Budget prüfen" },
    historicalWithinBudget: { title: "Zeitraum im Budget abgeschlossen", description: "Der Netto-Cashflow ist Einnahmen minus Ausgaben; er ist weder Kontostand noch ungenutztes Budget.", cta: "Budget anzeigen" },
    historicalNoBudget: { title: "Zeitraum ohne Budget abgeschlossen", description: "Der Netto-Cashflow zeigt das tatsächliche Ergebnis, nicht Kontostand oder Ausgabenplan.", cta: "Zeitraum anzeigen" },
    historicalInsufficientData: { title: "Keine Analyse verfügbar", description: "Für diesen abgeschlossenen Zeitraum liegen keine Transaktionen für eine Analyse vor.", cta: "" },
    futurePeriod: { title: "Zukünftiger Zeitraum", description: "Es liegen noch nicht genügend tatsächliche Daten für eine Empfehlung vor.", cta: "" },
  },
  fr: {
    historicalOverBudget: { title: "Période clôturée au-dessus du budget", description: "Les dépenses réelles ont dépassé le plan de dépenses de cette période.", cta: "Vérifier le budget" },
    historicalWithinBudget: { title: "Période clôturée dans le budget", description: "Le flux net correspond aux revenus moins les dépenses, pas au solde du compte ni au budget inutilisé.", cta: "Voir le budget" },
    historicalNoBudget: { title: "Période clôturée sans budget", description: "Le flux net indique le résultat réalisé, pas le solde du compte ni un plan de dépenses.", cta: "Voir la période" },
    historicalInsufficientData: { title: "Analyse indisponible", description: "Cette période clôturée ne contient aucune transaction permettant une analyse.", cta: "" },
    futurePeriod: { title: "Période future", description: "Les données réalisées sont encore insuffisantes pour générer une recommandation.", cta: "" },
  },
  nl: {
    historicalOverBudget: { title: "Periode boven budget afgesloten", description: "De werkelijke uitgaven overschreden het uitgavenplan voor deze periode.", cta: "Budget bekijken" },
    historicalWithinBudget: { title: "Periode binnen budget afgesloten", description: "De netto kasstroom is inkomsten min uitgaven; geen rekeningsaldo of ongebruikt budget.", cta: "Budget bekijken" },
    historicalNoBudget: { title: "Periode zonder budget afgesloten", description: "De netto kasstroom toont het gerealiseerde resultaat, niet een rekeningsaldo of uitgavenplan.", cta: "Periode bekijken" },
    historicalInsufficientData: { title: "Analyse niet beschikbaar", description: "Deze afgesloten periode heeft geen transacties voor een onderbouwde analyse.", cta: "" },
    futurePeriod: { title: "Toekomstige periode", description: "Er zijn nog niet genoeg gerealiseerde gegevens voor een aanbeveling.", cta: "" },
  },
  it: {
    historicalOverBudget: { title: "Periodo chiuso sopra il budget", description: "Le spese effettive hanno superato il piano di spesa del periodo.", cta: "Rivedi budget" },
    historicalWithinBudget: { title: "Periodo chiuso entro il budget", description: "Il flusso netto è entrate meno spese; non è saldo del conto né budget inutilizzato.", cta: "Vedi budget" },
    historicalNoBudget: { title: "Periodo chiuso senza budget", description: "Il flusso netto mostra il risultato realizzato, non il saldo del conto o un piano di spesa.", cta: "Vedi periodo" },
    historicalInsufficientData: { title: "Analisi non disponibile", description: "Questo periodo chiuso non contiene transazioni sufficienti per un'analisi.", cta: "" },
    futurePeriod: { title: "Periodo futuro", description: "Non ci sono ancora dati realizzati sufficienti per generare una raccomandazione.", cta: "" },
  },
};

export const dashboardCopyByLanguage: Record<Language, DashboardCopy> = {
  en: {
    incomeAveragePerDayHelp: "Total income divided by elapsed days: all days for a completed month, or through today for the current month. Future months are unavailable.", incomeIndicatorUnavailable: "Unavailable", noIncomeRecorded: "No income recorded",
    budgetUsedLabel: "Budget used", budgetSpentLabel: "Spent", budgetExceeded: "Budget exceeded", budgetExceededBy: "Exceeded by {percentage}%", budgetUsageUnavailable: "Budget usage is unavailable because the configured limits overlap or are invalid.",
    dailyNetFlow: "Daily net flow", dailyIncome: "Daily income", dailyExpenses: "Daily expenses", cumulativeNetFlow: "Cumulative net flow in period", cumulativeIncome: "Cumulative income in period", cumulativeExpenses: "Cumulative expenses in period", noMovementsInPeriod: "No movements in this period.",
    noBudgetRecorded: "No budget recorded", noBudgetRecordedDescription: "No budget was registered for this period.",
    netCashFlow: "Net cash flow", thisMonth: "THIS MONTH", currentMonth: "Current month", netCashFlowDescription: "Income minus expenses for the selected period.", monthlyFlow: "Monthly flow", addStartingBalance: "Add a starting balance to see this", balanceUnavailable: "Balance unavailable", accountBalanceUnavailable: "Account balance unavailable", trendUnavailable: "Trend unavailable", historicalSeriesUnavailable: "Historical series unavailable", distributionUnavailable: "Distribution unavailable", valuesHidden: "Financial values are hidden.",
    noSpendingData: "No spending data", noSpendingThisMonth: "No spending data this month", noSpendingRecorded: "No spending recorded", spendingCategoriesPlaceholder: "Expense categories will appear here.", largestExpense: "{category} is your largest expense", expenseShare: "{percentage}% of this month's expenses.", other: "Other", uncategorized: "Uncategorized",
    noGoalYet: "No goal yet", createGoalHelp: "Create a financial goal to start tracking progress.", createGoal: "Create goal", goalCompleted: "Goal completed", reviewTargetDate: "Review target date", reviewNeeded: "Review needed", planActive: "Plan active", onSchedule: "On schedule", saved: "Saved", target: "Target", remaining: "Remaining", requiredPerMonth: "Required / month", targetLabel: "Target:", planTargetLabel: "Plan target:", active: "Active",
    noScheduledBills: "No scheduled bills", scheduledBillsUnavailable: "Scheduled bills are not available yet.", noBudgetYet: "No budget yet", createBudget: "Create budget", onTrackStatus: "On track", withinBudgetProjection: "Projected spending is within your monthly budget.", withinBudgetActual: "Actual spending stayed within the budget for this period.", needsAttention: "Needs attention", aboveBudgetProjection: "Projected spending is above your monthly budget.", aboveBudgetActual: "Actual spending exceeded the budget for this period.", createBudgetProjection: "Create a monthly budget to unlock spending projections.", budgetLabel: "Budget", projectedLabel: "Projected", actualLabel: "Actual", moneyPilotInsight: "MoneyPilot insight", currentPeriod: "Current · {period}",
    nextActions: {
      recoveryPlan: { title: "Recovery plan active", description: "Your recovery target is active. Review progress against the current projection.", cta: "Review budget" }, reviewBudget: { title: "Review your monthly budget", description: "Your current projection is above the planned budget.", cta: "Review budget" }, updateGoalDate: { title: "Update your goal date", description: "Your primary goal is past its target date and needs review.", cta: "Review goal" }, reviewGoalPlan: { title: "Review your savings plan", description: "Your budget or goal changed since this plan was created.", cta: "Review plan" }, insufficientCurrentData: { title: "Add current-month activity", description: "There is not enough current-month activity to estimate safe savings capacity yet.", cta: "View transactions" }, createBudget: { title: "Create a monthly budget", description: "A budget lets MoneyPilot project spending and find safe savings capacity.", cta: "Create budget" }, createGoal: { title: "Create your first goal", description: "Turn your available financial capacity into a clear target.", cta: "Create goal" }, buildSavingsPlan: { title: "Put your budget headroom to work", description: "MoneyPilot found conservative monthly capacity that could support your primary goal.", cta: "Review savings plan" }, followSavingsPlan: { title: "Stay on your savings plan", description: "Your saved monthly target is ready to guide this goal.", cta: "View goal" }, goalCompleted: { title: "Goal completed", description: "Your primary goal has reached its target.", cta: "View goals" }, noAction: { title: "You're on track this month", description: "Projected spending is within your configured monthly budget.", cta: "" },
    },
  },
  pt: {
    incomeAveragePerDayHelp: "Total de receitas dividido pelos dias decorridos: todos os dias em um mês encerrado ou até hoje no mês atual. Meses futuros ficam indisponíveis.", incomeIndicatorUnavailable: "Indisponível", noIncomeRecorded: "Nenhuma receita registrada",
    budgetUsedLabel: "Orçamento utilizado", budgetSpentLabel: "Gasto", budgetExceeded: "Orçamento excedido", budgetExceededBy: "Excedido em {percentage}%", budgetUsageUnavailable: "O consumo do orçamento está indisponível porque os limites configurados se sobrepõem ou são inválidos.",
    dailyNetFlow: "Fluxo líquido diário", dailyIncome: "Receitas diárias", dailyExpenses: "Despesas diárias", cumulativeNetFlow: "Fluxo líquido acumulado no período", cumulativeIncome: "Receitas acumuladas no período", cumulativeExpenses: "Despesas acumuladas no período", noMovementsInPeriod: "Nenhuma movimentação neste período.",
    noBudgetRecorded: "Nenhum orçamento registrado", noBudgetRecordedDescription: "Nenhum orçamento foi registrado neste período.",
    netCashFlow: "Fluxo de caixa líquido", thisMonth: "ESTE MÊS", currentMonth: "Mês atual", netCashFlowDescription: "Receitas menos despesas do período selecionado.", monthlyFlow: "Fluxo mensal", addStartingBalance: "Adicione um saldo inicial para ver este valor", balanceUnavailable: "Saldo indisponível", accountBalanceUnavailable: "Saldo da conta indisponível", trendUnavailable: "Tendência indisponível", historicalSeriesUnavailable: "Série histórica indisponível", distributionUnavailable: "Distribuição indisponível", valuesHidden: "Os valores financeiros estão ocultos.",
    noSpendingData: "Sem dados de despesas", noSpendingThisMonth: "Sem dados de despesas neste mês", noSpendingRecorded: "Nenhuma despesa registrada", spendingCategoriesPlaceholder: "As categorias de despesas aparecerão aqui.", largestExpense: "{category} é sua maior despesa", expenseShare: "{percentage}% das despesas deste mês.", other: "Outros", uncategorized: "Sem categoria",
    noGoalYet: "Nenhuma meta ainda", createGoalHelp: "Crie uma meta financeira para começar a acompanhar o progresso.", createGoal: "Criar meta", goalCompleted: "Meta concluída", reviewTargetDate: "Revisar data da meta", reviewNeeded: "Revisão necessária", planActive: "Plano ativo", onSchedule: "Dentro do prazo", saved: "Guardado", target: "Meta", remaining: "Restante", requiredPerMonth: "Necessário / mês", targetLabel: "Meta:", planTargetLabel: "Meta do plano:", active: "Ativo",
    noScheduledBills: "Nenhuma conta agendada", scheduledBillsUnavailable: "As contas agendadas ainda não estão disponíveis.", noBudgetYet: "Nenhum orçamento ainda", createBudget: "Criar orçamento", onTrackStatus: "No caminho certo", withinBudgetProjection: "A projeção de despesas está dentro do orçamento mensal.", withinBudgetActual: "As despesas realizadas ficaram dentro do orçamento deste período.", needsAttention: "Requer atenção", aboveBudgetProjection: "A projeção de despesas está acima do orçamento mensal.", aboveBudgetActual: "As despesas realizadas ultrapassaram o orçamento deste período.", createBudgetProjection: "Crie um orçamento mensal para liberar projeções de despesas.", budgetLabel: "Orçamento", projectedLabel: "Projetado", actualLabel: "Realizado", moneyPilotInsight: "Insight do MoneyPilot", currentPeriod: "Atual · {period}",
    nextActions: {
      recoveryPlan: { title: "Plano de recuperação ativo", description: "Sua meta de recuperação está ativa. Revise o progresso em relação à projeção atual.", cta: "Revisar orçamento" }, reviewBudget: { title: "Revise seu orçamento mensal", description: "Sua projeção atual está acima do orçamento planejado.", cta: "Revisar orçamento" }, updateGoalDate: { title: "Atualize a data da sua meta", description: "Sua meta principal passou da data prevista e precisa ser revisada.", cta: "Revisar meta" }, reviewGoalPlan: { title: "Revise seu plano de economia", description: "Seu orçamento ou sua meta mudou desde a criação deste plano.", cta: "Revisar plano" }, insufficientCurrentData: { title: "Adicione movimentações deste mês", description: "Ainda não há dados suficientes do mês atual para estimar uma capacidade segura de poupança.", cta: "Ver transações" }, createBudget: { title: "Crie um orçamento mensal", description: "Um orçamento permite ao MoneyPilot projetar despesas e encontrar uma capacidade segura de economia.", cta: "Criar orçamento" }, createGoal: { title: "Crie sua primeira meta", description: "Transforme sua capacidade financeira disponível em uma meta clara.", cta: "Criar meta" }, buildSavingsPlan: { title: "Use a folga do orçamento a seu favor", description: "O MoneyPilot encontrou uma capacidade mensal conservadora que pode apoiar sua meta principal.", cta: "Revisar plano de economia" }, followSavingsPlan: { title: "Siga seu plano de economia", description: "Sua meta mensal guardada está pronta para orientar este objetivo.", cta: "Ver meta" }, goalCompleted: { title: "Meta concluída", description: "Sua meta principal atingiu o valor definido.", cta: "Ver metas" }, noAction: { title: "Você está no caminho certo neste mês", description: "A projeção de despesas está dentro do orçamento mensal configurado.", cta: "" },
    },
  },
  es: {
    incomeAveragePerDayHelp: "Ingresos totales divididos por los días transcurridos: todos los días de un mes cerrado o hasta hoy en el mes actual. Los meses futuros no están disponibles.", incomeIndicatorUnavailable: "No disponible", noIncomeRecorded: "No se registraron ingresos",
    budgetUsedLabel: "Presupuesto utilizado", budgetSpentLabel: "Gastado", budgetExceeded: "Presupuesto excedido", budgetExceededBy: "Excedido en un {percentage}%", budgetUsageUnavailable: "El uso del presupuesto no está disponible porque los límites configurados se superponen o no son válidos.",
    dailyNetFlow: "Flujo neto diario", dailyIncome: "Ingresos diarios", dailyExpenses: "Gastos diarios", cumulativeNetFlow: "Flujo neto acumulado en el período", cumulativeIncome: "Ingresos acumulados en el período", cumulativeExpenses: "Gastos acumulados en el período", noMovementsInPeriod: "No hay movimientos en este período.",
    noBudgetRecorded: "Ningún presupuesto registrado", noBudgetRecordedDescription: "No se registró ningún presupuesto en este período.",
    netCashFlow: "Flujo de caja neto", thisMonth: "ESTE MES", currentMonth: "Mes actual", netCashFlowDescription: "Ingresos menos gastos del período seleccionado.", monthlyFlow: "Flujo mensual", addStartingBalance: "Añade un saldo inicial para ver este valor", balanceUnavailable: "Saldo no disponible", accountBalanceUnavailable: "Saldo de la cuenta no disponible", trendUnavailable: "Tendencia no disponible", historicalSeriesUnavailable: "Serie histórica no disponible", distributionUnavailable: "Distribución no disponible", valuesHidden: "Los valores financieros están ocultos.",
    noSpendingData: "Sin datos de gastos", noSpendingThisMonth: "Sin datos de gastos este mes", noSpendingRecorded: "No se registraron gastos", spendingCategoriesPlaceholder: "Las categorías de gastos aparecerán aquí.", largestExpense: "{category} es tu mayor gasto", expenseShare: "{percentage}% de los gastos de este mes.", other: "Otros", uncategorized: "Sin categoría",
    noGoalYet: "Aún no hay una meta", createGoalHelp: "Crea una meta financiera para empezar a seguir el progreso.", createGoal: "Crear meta", goalCompleted: "Meta completada", reviewTargetDate: "Revisar fecha de la meta", reviewNeeded: "Revisión necesaria", planActive: "Plan activo", onSchedule: "Dentro del plazo", saved: "Ahorrado", target: "Meta", remaining: "Restante", requiredPerMonth: "Necesario / mes", targetLabel: "Meta:", planTargetLabel: "Meta del plan:", active: "Activo",
    noScheduledBills: "No hay facturas programadas", scheduledBillsUnavailable: "Las facturas programadas aún no están disponibles.", noBudgetYet: "Aún no hay presupuesto", createBudget: "Crear presupuesto", onTrackStatus: "Por buen camino", withinBudgetProjection: "El gasto proyectado está dentro de tu presupuesto mensual.", withinBudgetActual: "El gasto real se mantuvo dentro del presupuesto de este período.", needsAttention: "Requiere atención", aboveBudgetProjection: "El gasto proyectado supera tu presupuesto mensual.", aboveBudgetActual: "El gasto real superó el presupuesto de este período.", createBudgetProjection: "Crea un presupuesto mensual para habilitar las proyecciones de gastos.", budgetLabel: "Presupuesto", projectedLabel: "Proyectado", actualLabel: "Real", moneyPilotInsight: "Insight de MoneyPilot", currentPeriod: "Actual · {period}",
    nextActions: {
      recoveryPlan: { title: "Plan de recuperación activo", description: "Tu objetivo de recuperación está activo. Revisa el progreso frente a la proyección actual.", cta: "Revisar presupuesto" }, reviewBudget: { title: "Revisa tu presupuesto mensual", description: "Tu proyección actual supera el presupuesto planificado.", cta: "Revisar presupuesto" }, updateGoalDate: { title: "Actualiza la fecha de tu meta", description: "Tu meta principal ha superado la fecha prevista y necesita revisión.", cta: "Revisar meta" }, reviewGoalPlan: { title: "Revisa tu plan de ahorro", description: "Tu presupuesto o meta cambió desde que se creó este plan.", cta: "Revisar plan" }, insufficientCurrentData: { title: "Añade movimientos de este mes", description: "Aún no hay suficiente actividad del mes actual para estimar una capacidad de ahorro segura.", cta: "Ver transacciones" }, createBudget: { title: "Crea un presupuesto mensual", description: "Un presupuesto permite a MoneyPilot proyectar gastos y encontrar una capacidad de ahorro segura.", cta: "Crear presupuesto" }, createGoal: { title: "Crea tu primera meta", description: "Convierte tu capacidad financiera disponible en una meta clara.", cta: "Crear meta" }, buildSavingsPlan: { title: "Aprovecha el margen de tu presupuesto", description: "MoneyPilot encontró una capacidad mensual conservadora que puede apoyar tu meta principal.", cta: "Revisar plan de ahorro" }, followSavingsPlan: { title: "Sigue tu plan de ahorro", description: "Tu objetivo mensual guardado está listo para orientar esta meta.", cta: "Ver meta" }, goalCompleted: { title: "Meta completada", description: "Tu meta principal ha alcanzado su objetivo.", cta: "Ver metas" }, noAction: { title: "Vas por buen camino este mes", description: "El gasto proyectado está dentro del presupuesto mensual configurado.", cta: "" },
    },
  },
  de: {
    incomeAveragePerDayHelp: "Gesamteinnahmen geteilt durch die vergangenen Tage: alle Tage eines abgeschlossenen Monats oder bis heute im aktuellen Monat. Zukünftige Monate sind nicht verfügbar.", incomeIndicatorUnavailable: "Nicht verfügbar", noIncomeRecorded: "Keine Einnahmen erfasst",
    budgetUsedLabel: "Budget verwendet", budgetSpentLabel: "Ausgegeben", budgetExceeded: "Budget überschritten", budgetExceededBy: "Um {percentage}% überschritten", budgetUsageUnavailable: "Die Budgetnutzung ist nicht verfügbar, weil sich konfigurierte Limits überschneiden oder ungültig sind.",
    dailyNetFlow: "Täglicher Netto-Cashflow", dailyIncome: "Tägliche Einnahmen", dailyExpenses: "Tägliche Ausgaben", cumulativeNetFlow: "Kumulierter Netto-Cashflow im Zeitraum", cumulativeIncome: "Kumulierte Einnahmen im Zeitraum", cumulativeExpenses: "Kumulierte Ausgaben im Zeitraum", noMovementsInPeriod: "Keine Bewegungen in diesem Zeitraum.",
    noBudgetRecorded: "Kein Budget erfasst", noBudgetRecordedDescription: "Für diesen Zeitraum wurde kein Budget erfasst.",
    netCashFlow: "Netto-Cashflow", thisMonth: "DIESEN MONAT", currentMonth: "Aktueller Monat", netCashFlowDescription: "Einnahmen abzüglich Ausgaben im ausgewählten Zeitraum.", monthlyFlow: "Monatlicher Cashflow", addStartingBalance: "Füge einen Anfangssaldo hinzu, um diesen Wert zu sehen", balanceUnavailable: "Saldo nicht verfügbar", accountBalanceUnavailable: "Kontostand nicht verfügbar", trendUnavailable: "Trend nicht verfügbar", historicalSeriesUnavailable: "Historische Datenreihe nicht verfügbar", distributionUnavailable: "Verteilung nicht verfügbar", valuesHidden: "Finanzwerte sind ausgeblendet.",
    noSpendingData: "Keine Ausgabendaten", noSpendingThisMonth: "Keine Ausgabendaten in diesem Monat", noSpendingRecorded: "Keine Ausgaben erfasst", spendingCategoriesPlaceholder: "Ausgabenkategorien werden hier angezeigt.", largestExpense: "{category} ist deine größte Ausgabe", expenseShare: "{percentage}% der Ausgaben dieses Monats.", other: "Sonstige", uncategorized: "Ohne Kategorie",
    noGoalYet: "Noch kein Ziel", createGoalHelp: "Erstelle ein Finanzziel, um den Fortschritt zu verfolgen.", createGoal: "Ziel erstellen", goalCompleted: "Ziel erreicht", reviewTargetDate: "Zieldatum prüfen", reviewNeeded: "Überprüfung nötig", planActive: "Plan aktiv", onSchedule: "Im Zeitplan", saved: "Gespart", target: "Ziel", remaining: "Verbleibend", requiredPerMonth: "Erforderlich / Monat", targetLabel: "Ziel:", planTargetLabel: "Planziel:", active: "Aktiv",
    noScheduledBills: "Keine geplanten Rechnungen", scheduledBillsUnavailable: "Geplante Rechnungen sind noch nicht verfügbar.", noBudgetYet: "Noch kein Budget", createBudget: "Budget erstellen", onTrackStatus: "Im Plan", withinBudgetProjection: "Die prognostizierten Ausgaben liegen innerhalb deines Monatsbudgets.", withinBudgetActual: "Die tatsächlichen Ausgaben blieben in diesem Zeitraum innerhalb des Budgets.", needsAttention: "Handlung nötig", aboveBudgetProjection: "Die prognostizierten Ausgaben liegen über deinem Monatsbudget.", aboveBudgetActual: "Die tatsächlichen Ausgaben überschritten das Budget dieses Zeitraums.", createBudgetProjection: "Erstelle ein Monatsbudget, um Ausgabenprognosen zu erhalten.", budgetLabel: "Budget", projectedLabel: "Prognose", actualLabel: "Tatsächlich", moneyPilotInsight: "MoneyPilot-Einblick", currentPeriod: "Aktuell · {period}",
    nextActions: {
      recoveryPlan: { title: "Erholungsplan aktiv", description: "Dein Erholungsziel ist aktiv. Prüfe den Fortschritt anhand der aktuellen Prognose.", cta: "Budget prüfen" }, reviewBudget: { title: "Prüfe dein Monatsbudget", description: "Deine aktuelle Prognose liegt über dem geplanten Budget.", cta: "Budget prüfen" }, updateGoalDate: { title: "Aktualisiere dein Zieldatum", description: "Das Datum deines Hauptziels ist überschritten und muss geprüft werden.", cta: "Ziel prüfen" }, reviewGoalPlan: { title: "Prüfe deinen Sparplan", description: "Dein Budget oder Ziel hat sich seit Erstellung dieses Plans geändert.", cta: "Plan prüfen" }, insufficientCurrentData: { title: "Aktuelle Monatsaktivität hinzufügen", description: "Es gibt noch nicht genügend Aktivität im aktuellen Monat, um eine sichere Sparmöglichkeit zu schätzen.", cta: "Transaktionen anzeigen" }, createBudget: { title: "Erstelle ein Monatsbudget", description: "Mit einem Budget kann MoneyPilot Ausgaben prognostizieren und sichere Sparmöglichkeiten ermitteln.", cta: "Budget erstellen" }, createGoal: { title: "Erstelle dein erstes Ziel", description: "Mache aus deinem verfügbaren finanziellen Spielraum ein klares Ziel.", cta: "Ziel erstellen" }, buildSavingsPlan: { title: "Nutze deinen Budgetspielraum", description: "MoneyPilot hat eine vorsichtige monatliche Kapazität gefunden, die dein Hauptziel unterstützen kann.", cta: "Sparplan prüfen" }, followSavingsPlan: { title: "Bleib bei deinem Sparplan", description: "Dein gespeichertes Monatsziel kann dich jetzt bei diesem Ziel leiten.", cta: "Ziel anzeigen" }, goalCompleted: { title: "Ziel erreicht", description: "Dein Hauptziel hat den Zielbetrag erreicht.", cta: "Ziele anzeigen" }, noAction: { title: "Du bist diesen Monat im Plan", description: "Die prognostizierten Ausgaben liegen innerhalb deines festgelegten Monatsbudgets.", cta: "" },
    },
  },
  fr: {
    incomeAveragePerDayHelp: "Revenus totaux divisés par les jours écoulés : tous les jours d’un mois terminé, ou jusqu’à aujourd’hui pour le mois en cours. Les mois futurs sont indisponibles.", incomeIndicatorUnavailable: "Indisponible", noIncomeRecorded: "Aucun revenu enregistré",
    budgetUsedLabel: "Budget utilisé", budgetSpentLabel: "Dépensé", budgetExceeded: "Budget dépassé", budgetExceededBy: "Dépassé de {percentage}%", budgetUsageUnavailable: "L’utilisation du budget est indisponible, car les limites configurées se chevauchent ou sont invalides.",
    dailyNetFlow: "Flux net quotidien", dailyIncome: "Revenus quotidiens", dailyExpenses: "Dépenses quotidiennes", cumulativeNetFlow: "Flux net cumulé sur la période", cumulativeIncome: "Revenus cumulés sur la période", cumulativeExpenses: "Dépenses cumulées sur la période", noMovementsInPeriod: "Aucun mouvement sur cette période.",
    noBudgetRecorded: "Aucun budget enregistré", noBudgetRecordedDescription: "Aucun budget n’a été enregistré pour cette période.",
    netCashFlow: "Flux de trésorerie net", thisMonth: "CE MOIS-CI", currentMonth: "Mois en cours", netCashFlowDescription: "Revenus moins dépenses sur la période sélectionnée.", monthlyFlow: "Flux mensuel", addStartingBalance: "Ajoutez un solde initial pour afficher cette valeur", balanceUnavailable: "Solde indisponible", accountBalanceUnavailable: "Solde du compte indisponible", trendUnavailable: "Tendance indisponible", historicalSeriesUnavailable: "Série historique indisponible", distributionUnavailable: "Distribution indisponible", valuesHidden: "Les valeurs financières sont masquées.",
    noSpendingData: "Aucune donnée de dépenses", noSpendingThisMonth: "Aucune donnée de dépenses ce mois-ci", noSpendingRecorded: "Aucune dépense enregistrée", spendingCategoriesPlaceholder: "Les catégories de dépenses apparaîtront ici.", largestExpense: "{category} est votre dépense principale", expenseShare: "{percentage}% des dépenses de ce mois.", other: "Autres", uncategorized: "Sans catégorie",
    noGoalYet: "Aucun objectif", createGoalHelp: "Créez un objectif financier pour commencer à suivre votre progression.", createGoal: "Créer un objectif", goalCompleted: "Objectif atteint", reviewTargetDate: "Vérifier la date cible", reviewNeeded: "Vérification requise", planActive: "Plan actif", onSchedule: "Dans les délais", saved: "Épargné", target: "Objectif", remaining: "Restant", requiredPerMonth: "Requis / mois", targetLabel: "Objectif :", planTargetLabel: "Objectif du plan :", active: "Actif",
    noScheduledBills: "Aucune facture planifiée", scheduledBillsUnavailable: "Les factures planifiées ne sont pas encore disponibles.", noBudgetYet: "Aucun budget", createBudget: "Créer un budget", onTrackStatus: "En bonne voie", withinBudgetProjection: "Les dépenses prévues respectent votre budget mensuel.", withinBudgetActual: "Les dépenses réelles sont restées dans le budget de cette période.", needsAttention: "Attention requise", aboveBudgetProjection: "Les dépenses prévues dépassent votre budget mensuel.", aboveBudgetActual: "Les dépenses réelles ont dépassé le budget de cette période.", createBudgetProjection: "Créez un budget mensuel pour activer les prévisions de dépenses.", budgetLabel: "Budget", projectedLabel: "Prévision", actualLabel: "Réel", moneyPilotInsight: "Analyse MoneyPilot", currentPeriod: "Actuel · {period}",
    nextActions: {
      recoveryPlan: { title: "Plan de redressement actif", description: "Votre objectif de redressement est actif. Vérifiez les progrès par rapport à la prévision actuelle.", cta: "Vérifier le budget" }, reviewBudget: { title: "Vérifiez votre budget mensuel", description: "Votre prévision actuelle dépasse le budget planifié.", cta: "Vérifier le budget" }, updateGoalDate: { title: "Mettez à jour la date de votre objectif", description: "La date cible de votre objectif principal est dépassée et doit être vérifiée.", cta: "Vérifier l’objectif" }, reviewGoalPlan: { title: "Vérifiez votre plan d’épargne", description: "Votre budget ou objectif a changé depuis la création de ce plan.", cta: "Vérifier le plan" }, insufficientCurrentData: { title: "Ajoutez des opérations ce mois-ci", description: "L’activité du mois en cours est encore insuffisante pour estimer une capacité d’épargne sûre.", cta: "Voir les transactions" }, createBudget: { title: "Créez un budget mensuel", description: "Un budget permet à MoneyPilot de prévoir les dépenses et d’identifier une capacité d’épargne sûre.", cta: "Créer un budget" }, createGoal: { title: "Créez votre premier objectif", description: "Transformez votre capacité financière disponible en un objectif clair.", cta: "Créer un objectif" }, buildSavingsPlan: { title: "Utilisez la marge de votre budget", description: "MoneyPilot a identifié une capacité mensuelle prudente pour soutenir votre objectif principal.", cta: "Vérifier le plan d’épargne" }, followSavingsPlan: { title: "Suivez votre plan d’épargne", description: "Votre objectif mensuel enregistré est prêt à guider cet objectif.", cta: "Voir l’objectif" }, goalCompleted: { title: "Objectif atteint", description: "Votre objectif principal a atteint sa cible.", cta: "Voir les objectifs" }, noAction: { title: "Vous êtes en bonne voie ce mois-ci", description: "Les dépenses prévues respectent votre budget mensuel configuré.", cta: "" },
    },
  },
  nl: {
    incomeAveragePerDayHelp: "Totale inkomsten gedeeld door de verstreken dagen: alle dagen van een afgesloten maand, of tot en met vandaag voor de huidige maand. Toekomstige maanden zijn niet beschikbaar.", incomeIndicatorUnavailable: "Niet beschikbaar", noIncomeRecorded: "Geen inkomsten geregistreerd",
    budgetUsedLabel: "Budget gebruikt", budgetSpentLabel: "Uitgegeven", budgetExceeded: "Budget overschreden", budgetExceededBy: "Met {percentage}% overschreden", budgetUsageUnavailable: "Budgetgebruik is niet beschikbaar omdat ingestelde limieten overlappen of ongeldig zijn.",
    dailyNetFlow: "Dagelijkse netto kasstroom", dailyIncome: "Dagelijkse inkomsten", dailyExpenses: "Dagelijkse uitgaven", cumulativeNetFlow: "Cumulatieve netto kasstroom in de periode", cumulativeIncome: "Cumulatieve inkomsten in de periode", cumulativeExpenses: "Cumulatieve uitgaven in de periode", noMovementsInPeriod: "Geen transacties in deze periode.",
    noBudgetRecorded: "Geen budget geregistreerd", noBudgetRecordedDescription: "Voor deze periode is geen budget geregistreerd.",
    netCashFlow: "Netto kasstroom", thisMonth: "DEZE MAAND", currentMonth: "Huidige maand", netCashFlowDescription: "Inkomsten min uitgaven over de geselecteerde periode.", monthlyFlow: "Maandelijkse kasstroom", addStartingBalance: "Voeg een beginsaldo toe om dit te bekijken", balanceUnavailable: "Saldo niet beschikbaar", accountBalanceUnavailable: "Rekeningsaldo niet beschikbaar", trendUnavailable: "Trend niet beschikbaar", historicalSeriesUnavailable: "Historische reeks niet beschikbaar", distributionUnavailable: "Verdeling niet beschikbaar", valuesHidden: "Financiële waarden zijn verborgen.",
    noSpendingData: "Geen uitgavengegevens", noSpendingThisMonth: "Geen uitgavengegevens deze maand", noSpendingRecorded: "Geen uitgaven geregistreerd", spendingCategoriesPlaceholder: "Uitgavencategorieën verschijnen hier.", largestExpense: "{category} is je grootste uitgave", expenseShare: "{percentage}% van de uitgaven van deze maand.", other: "Overig", uncategorized: "Zonder categorie",
    noGoalYet: "Nog geen doel", createGoalHelp: "Maak een financieel doel om de voortgang te gaan volgen.", createGoal: "Doel maken", goalCompleted: "Doel voltooid", reviewTargetDate: "Doeldatum controleren", reviewNeeded: "Controle nodig", planActive: "Plan actief", onSchedule: "Op schema", saved: "Gespaard", target: "Doel", remaining: "Resterend", requiredPerMonth: "Nodig / maand", targetLabel: "Doel:", planTargetLabel: "Planddoel:", active: "Actief",
    noScheduledBills: "Geen geplande rekeningen", scheduledBillsUnavailable: "Geplande rekeningen zijn nog niet beschikbaar.", noBudgetYet: "Nog geen budget", createBudget: "Budget maken", onTrackStatus: "Op schema", withinBudgetProjection: "De verwachte uitgaven vallen binnen je maandbudget.", withinBudgetActual: "De werkelijke uitgaven bleven binnen het budget voor deze periode.", needsAttention: "Aandacht nodig", aboveBudgetProjection: "De verwachte uitgaven liggen boven je maandbudget.", aboveBudgetActual: "De werkelijke uitgaven overschreden het budget voor deze periode.", createBudgetProjection: "Maak een maandbudget om uitgavenprognoses te activeren.", budgetLabel: "Budget", projectedLabel: "Verwacht", actualLabel: "Werkelijk", moneyPilotInsight: "MoneyPilot-inzicht", currentPeriod: "Actueel · {period}",
    nextActions: {
      recoveryPlan: { title: "Herstelplan actief", description: "Je hersteldoel is actief. Bekijk de voortgang ten opzichte van de huidige prognose.", cta: "Budget bekijken" }, reviewBudget: { title: "Bekijk je maandbudget", description: "Je huidige prognose ligt boven het geplande budget.", cta: "Budget bekijken" }, updateGoalDate: { title: "Werk de datum van je doel bij", description: "De streefdatum van je belangrijkste doel is verstreken en moet worden bekeken.", cta: "Doel bekijken" }, reviewGoalPlan: { title: "Bekijk je spaarplan", description: "Je budget of doel is veranderd sinds dit plan is gemaakt.", cta: "Plan bekijken" }, insufficientCurrentData: { title: "Voeg activiteit van deze maand toe", description: "Er is nog niet genoeg activiteit in de huidige maand om veilige spaarruimte te schatten.", cta: "Transacties bekijken" }, createBudget: { title: "Maak een maandbudget", description: "Met een budget kan MoneyPilot uitgaven voorspellen en veilige spaarruimte vinden.", cta: "Budget maken" }, createGoal: { title: "Maak je eerste doel", description: "Zet je beschikbare financiële ruimte om in een duidelijk doel.", cta: "Doel maken" }, buildSavingsPlan: { title: "Benut je budgetruimte", description: "MoneyPilot heeft een voorzichtige maandelijkse ruimte gevonden die je belangrijkste doel kan ondersteunen.", cta: "Spaarplan bekijken" }, followSavingsPlan: { title: "Volg je spaarplan", description: "Je opgeslagen maanddoel staat klaar om dit doel te sturen.", cta: "Doel bekijken" }, goalCompleted: { title: "Doel voltooid", description: "Je belangrijkste doel heeft het doelbedrag bereikt.", cta: "Doelen bekijken" }, noAction: { title: "Je ligt deze maand op schema", description: "De verwachte uitgaven vallen binnen je ingestelde maandbudget.", cta: "" },
    },
  },
  it: {
    incomeAveragePerDayHelp: "Entrate totali divise per i giorni trascorsi: tutti i giorni di un mese concluso oppure fino a oggi per il mese corrente. I mesi futuri non sono disponibili.", incomeIndicatorUnavailable: "Non disponibile", noIncomeRecorded: "Nessuna entrata registrata",
    budgetUsedLabel: "Budget utilizzato", budgetSpentLabel: "Speso", budgetExceeded: "Budget superato", budgetExceededBy: "Superato del {percentage}%", budgetUsageUnavailable: "L’utilizzo del budget non è disponibile perché i limiti configurati si sovrappongono o non sono validi.",
    dailyNetFlow: "Flusso netto giornaliero", dailyIncome: "Entrate giornaliere", dailyExpenses: "Spese giornaliere", cumulativeNetFlow: "Flusso netto cumulato nel periodo", cumulativeIncome: "Entrate cumulate nel periodo", cumulativeExpenses: "Spese cumulate nel periodo", noMovementsInPeriod: "Nessun movimento in questo periodo.",
    noBudgetRecorded: "Nessun budget registrato", noBudgetRecordedDescription: "Non è stato registrato alcun budget per questo periodo.",
    netCashFlow: "Flusso di cassa netto", thisMonth: "QUESTO MESE", currentMonth: "Mese corrente", netCashFlowDescription: "Entrate meno spese del periodo selezionato.", monthlyFlow: "Flusso mensile", addStartingBalance: "Aggiungi un saldo iniziale per visualizzare questo valore", balanceUnavailable: "Saldo non disponibile", accountBalanceUnavailable: "Saldo del conto non disponibile", trendUnavailable: "Andamento non disponibile", historicalSeriesUnavailable: "Serie storica non disponibile", distributionUnavailable: "Distribuzione non disponibile", valuesHidden: "I valori finanziari sono nascosti.",
    noSpendingData: "Nessun dato sulle spese", noSpendingThisMonth: "Nessun dato sulle spese questo mese", noSpendingRecorded: "Nessuna spesa registrata", spendingCategoriesPlaceholder: "Le categorie di spesa appariranno qui.", largestExpense: "{category} è la tua spesa principale", expenseShare: "{percentage}% delle spese di questo mese.", other: "Altro", uncategorized: "Senza categoria",
    noGoalYet: "Nessun obiettivo", createGoalHelp: "Crea un obiettivo finanziario per iniziare a monitorare i progressi.", createGoal: "Crea obiettivo", goalCompleted: "Obiettivo raggiunto", reviewTargetDate: "Rivedi la data obiettivo", reviewNeeded: "Revisione necessaria", planActive: "Piano attivo", onSchedule: "Nei tempi previsti", saved: "Risparmiato", target: "Obiettivo", remaining: "Rimanente", requiredPerMonth: "Necessario / mese", targetLabel: "Obiettivo:", planTargetLabel: "Obiettivo del piano:", active: "Attivo",
    noScheduledBills: "Nessuna fattura pianificata", scheduledBillsUnavailable: "Le fatture pianificate non sono ancora disponibili.", noBudgetYet: "Nessun budget", createBudget: "Crea budget", onTrackStatus: "In linea", withinBudgetProjection: "Le spese previste rientrano nel budget mensile.", withinBudgetActual: "Le spese effettive sono rimaste entro il budget di questo periodo.", needsAttention: "Richiede attenzione", aboveBudgetProjection: "Le spese previste superano il budget mensile.", aboveBudgetActual: "Le spese effettive hanno superato il budget di questo periodo.", createBudgetProjection: "Crea un budget mensile per attivare le previsioni di spesa.", budgetLabel: "Budget", projectedLabel: "Previsto", actualLabel: "Effettivo", moneyPilotInsight: "Analisi MoneyPilot", currentPeriod: "Attuale · {period}",
    nextActions: {
      recoveryPlan: { title: "Piano di recupero attivo", description: "Il tuo obiettivo di recupero è attivo. Verifica i progressi rispetto alla previsione attuale.", cta: "Rivedi budget" }, reviewBudget: { title: "Rivedi il budget mensile", description: "La previsione attuale supera il budget pianificato.", cta: "Rivedi budget" }, updateGoalDate: { title: "Aggiorna la data del tuo obiettivo", description: "La data del tuo obiettivo principale è trascorsa e deve essere rivista.", cta: "Rivedi obiettivo" }, reviewGoalPlan: { title: "Rivedi il tuo piano di risparmio", description: "Il budget o l’obiettivo è cambiato dalla creazione del piano.", cta: "Rivedi piano" }, insufficientCurrentData: { title: "Aggiungi movimenti del mese corrente", description: "Non ci sono ancora attività sufficienti nel mese corrente per stimare una capacità di risparmio sicura.", cta: "Vedi transazioni" }, createBudget: { title: "Crea un budget mensile", description: "Un budget consente a MoneyPilot di prevedere le spese e individuare una capacità di risparmio sicura.", cta: "Crea budget" }, createGoal: { title: "Crea il tuo primo obiettivo", description: "Trasforma la capacità finanziaria disponibile in un obiettivo chiaro.", cta: "Crea obiettivo" }, buildSavingsPlan: { title: "Metti a frutto il margine del budget", description: "MoneyPilot ha individuato una capacità mensile prudente che può sostenere il tuo obiettivo principale.", cta: "Rivedi piano di risparmio" }, followSavingsPlan: { title: "Segui il tuo piano di risparmio", description: "Il tuo obiettivo mensile salvato è pronto a guidare questo obiettivo.", cta: "Vedi obiettivo" }, goalCompleted: { title: "Obiettivo raggiunto", description: "Il tuo obiettivo principale ha raggiunto il traguardo.", cta: "Vedi obiettivi" }, noAction: { title: "Sei in linea questo mese", description: "Le spese previste rientrano nel budget mensile configurato.", cta: "" },
    },
  },
};
