import type { Language } from './config';
const keys = ['title', 'description', 'back', 'due', 'paidMonth', 'next', 'daily', 'total', 'upcomingTitle', 'impact', 'previous', 'following', 'emptyDay', 'emptyUpcoming', 'paid', 'upcoming', 'overdue', 'scheduled', 'insight', 'source'] as const;
type CalendarCopy = Record<typeof keys[number], string>;
const rows: Record<Language, string[]> = {
  en: ['Financial calendar', 'Your finances, day by day.', 'Back to dashboard', 'Due', 'Paid this month', 'Next payment', 'Daily commitments', 'Daily total', 'Upcoming payments', 'View budget impact', 'Previous month', 'Next month', 'No commitments for this day.', 'No scheduled payments available.', 'Paid', 'Upcoming', 'Overdue', 'Scheduled', 'Recorded expenses: {amount}. Review their impact on your monthly budget.', 'Based on recorded expenses. Due dates and unpaid bills are not available yet.'],
  pt: ['Calendário financeiro', 'Suas finanças, dia a dia.', 'Voltar ao Dashboard', 'A vencer', 'Pago neste mês', 'Próximo vencimento', 'Compromissos do dia', 'Total do dia', 'Próximos vencimentos', 'Ver impacto no orçamento', 'Mês anterior', 'Próximo mês', 'Nenhum compromisso neste dia.', 'Nenhum vencimento programado disponível.', 'Pago', 'Próximo', 'Atrasado', 'Programado', 'Despesas registradas: {amount}. Confira o impacto no orçamento do mês.', 'Baseado nas despesas registradas. Vencimentos e contas pendentes ainda não estão disponíveis.'],
  es: ['Calendario financiero', 'Tus finanzas, día a día.', 'Volver al panel', 'Por vencer', 'Pagado este mes', 'Próximo vencimiento', 'Compromisos del día', 'Total del día', 'Próximos vencimientos', 'Ver impacto en el presupuesto', 'Mes anterior', 'Mes siguiente', 'No hay compromisos para este día.', 'No hay pagos programados disponibles.', 'Pagado', 'Próximo', 'Vencido', 'Programado', 'Gastos registrados: {amount}. Revisa su impacto en el presupuesto mensual.', 'Basado en gastos registrados. Aún no hay vencimientos ni facturas pendientes disponibles.'],
  de: ['Finanzkalender', 'Deine Finanzen, Tag für Tag.', 'Zurück zur Übersicht', 'Fällig', 'Diesen Monat bezahlt', 'Nächste Fälligkeit', 'Tagestermine', 'Tagessumme', 'Anstehende Zahlungen', 'Budgetauswirkung ansehen', 'Vorheriger Monat', 'Nächster Monat', 'Keine Termine an diesem Tag.', 'Keine geplanten Zahlungen verfügbar.', 'Bezahlt', 'Demnächst', 'Überfällig', 'Geplant', 'Erfasste Ausgaben: {amount}. Prüfe die Auswirkungen auf dein Monatsbudget.', 'Basiert auf erfassten Ausgaben. Fälligkeiten und offene Rechnungen sind noch nicht verfügbar.'],
  fr: ['Calendrier financier', 'Vos finances, jour après jour.', 'Retour au tableau de bord', 'À payer', 'Payé ce mois-ci', 'Prochaine échéance', 'Engagements du jour', 'Total du jour', 'Prochaines échéances', 'Voir l’impact sur le budget', 'Mois précédent', 'Mois suivant', 'Aucun engagement ce jour.', 'Aucun paiement programmé disponible.', 'Payé', 'À venir', 'En retard', 'Programmé', 'Dépenses enregistrées : {amount}. Consultez leur impact sur votre budget mensuel.', 'Basé sur les dépenses enregistrées. Les échéances et factures impayées ne sont pas encore disponibles.'],
  nl: ['Financiële kalender', 'Je financiën, dag voor dag.', 'Terug naar dashboard', 'Te betalen', 'Deze maand betaald', 'Volgende vervaldatum', 'Afspraken van de dag', 'Dagtotaal', 'Komende betalingen', 'Bekijk budgetimpact', 'Vorige maand', 'Volgende maand', 'Geen afspraken op deze dag.', 'Geen geplande betalingen beschikbaar.', 'Betaald', 'Binnenkort', 'Achterstallig', 'Gepland', 'Geregistreerde uitgaven: {amount}. Bekijk de impact op je maandbudget.', 'Gebaseerd op geregistreerde uitgaven. Vervaldata en openstaande rekeningen zijn nog niet beschikbaar.'],
  it: ['Calendario finanziario', 'Le tue finanze, giorno per giorno.', 'Torna alla dashboard', 'Da pagare', 'Pagato questo mese', 'Prossima scadenza', 'Impegni del giorno', 'Totale del giorno', 'Prossime scadenze', 'Vedi impatto sul budget', 'Mese precedente', 'Mese successivo', 'Nessun impegno per questo giorno.', 'Nessun pagamento programmato disponibile.', 'Pagato', 'In arrivo', 'Scaduto', 'Programmato', 'Spese registrate: {amount}. Verifica il loro impatto sul budget mensile.', 'Basato sulle spese registrate. Scadenze e fatture non pagate non sono ancora disponibili.'],
};
export const financialCalendarCopy = Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(keys.map((key, index) => [key, row[index]]))])) as Record<Language, CalendarCopy>;
