import type { Language } from './config';

const keys = ['title', 'description', 'close', 'appearance', 'appearanceHelp', 'photo', 'initials', 'choosePhoto', 'changePhoto', 'removePhoto', 'formats', 'name', 'nameHelp', 'firstName', 'lastName', 'email', 'footer', 'cancel', 'saving', 'save', 'typeError', 'sizeError', 'nameError', 'photoError', 'saveError'] as const;
type ProfileIdentityCopy = Record<typeof keys[number], string>;
const rows: Record<Language, readonly string[]> = {
  en: ['Profile', 'Manage your name and how your profile appears across MoneyPilot.', 'Close', 'Profile appearance', 'Choose whether MoneyPilot shows your photo or initials.', 'Photo', 'Initials', 'Choose profile photo', 'Change photo', 'Remove photo', 'JPEG, PNG or WebP · Maximum 5 MB', 'Name', 'Your initials are generated from your first and last name.', 'First name', 'Last name', 'Account email', 'You can change this at any time.', 'Cancel', 'Saving…', 'Save changes', 'Choose a JPEG, PNG or WebP image.', 'Profile photos must be 5 MB or smaller.', 'First name is required.', 'Choose a profile photo before using photo mode.', 'Profile changes could not be saved. Please try again.'],
  pt: ['Perfil', 'Gerencie seu nome e a apresentação do perfil no MoneyPilot.', 'Fechar', 'Aparência do perfil', 'Escolha se o MoneyPilot mostra sua foto ou suas iniciais.', 'Foto', 'Iniciais', 'Escolher foto do perfil', 'Trocar foto', 'Remover foto', 'JPEG, PNG ou WebP · Máximo 5 MB', 'Nome', 'Suas iniciais são geradas a partir do nome e sobrenome.', 'Nome', 'Sobrenome', 'E-mail da conta', 'Você pode alterar isso a qualquer momento.', 'Cancelar', 'Salvando…', 'Salvar alterações', 'Escolha uma imagem JPEG, PNG ou WebP.', 'A foto do perfil deve ter até 5 MB.', 'O nome é obrigatório.', 'Escolha uma foto antes de usar o modo de foto.', 'Não foi possível salvar o perfil. Tente novamente.'],
  es: ['Perfil', 'Gestiona tu nombre y la presentación de tu perfil en MoneyPilot.', 'Cerrar', 'Apariencia del perfil', 'Elige si MoneyPilot muestra tu foto o tus iniciales.', 'Foto', 'Iniciales', 'Elegir foto de perfil', 'Cambiar foto', 'Eliminar foto', 'JPEG, PNG o WebP · Máximo 5 MB', 'Nombre', 'Tus iniciales se generan a partir del nombre y apellido.', 'Nombre', 'Apellido', 'Correo de la cuenta', 'Puedes cambiarlo en cualquier momento.', 'Cancelar', 'Guardando…', 'Guardar cambios', 'Elige una imagen JPEG, PNG o WebP.', 'La foto debe tener 5 MB o menos.', 'El nombre es obligatorio.', 'Elige una foto antes de usar el modo de foto.', 'No se pudo guardar el perfil. Inténtalo de nuevo.'],
  de: ['Profil', 'Verwalte deinen Namen und die Profildarstellung in MoneyPilot.', 'Schließen', 'Profildarstellung', 'Wähle, ob MoneyPilot dein Foto oder deine Initialen zeigt.', 'Foto', 'Initialen', 'Profilfoto auswählen', 'Foto ändern', 'Foto entfernen', 'JPEG, PNG oder WebP · Maximal 5 MB', 'Name', 'Die Initialen werden aus Vor- und Nachnamen gebildet.', 'Vorname', 'Nachname', 'Konto-E-Mail', 'Du kannst dies jederzeit ändern.', 'Abbrechen', 'Wird gespeichert…', 'Änderungen speichern', 'Wähle ein JPEG-, PNG- oder WebP-Bild.', 'Profilfotos dürfen höchstens 5 MB groß sein.', 'Der Vorname ist erforderlich.', 'Wähle ein Profilfoto, bevor du den Fotomodus verwendest.', 'Das Profil konnte nicht gespeichert werden. Versuche es erneut.'],
  fr: ['Profil', 'Gérez votre nom et l’apparence du profil dans MoneyPilot.', 'Fermer', 'Apparence du profil', 'Choisissez entre votre photo et vos initiales.', 'Photo', 'Initiales', 'Choisir une photo de profil', 'Changer la photo', 'Supprimer la photo', 'JPEG, PNG ou WebP · Maximum 5 Mo', 'Nom', 'Vos initiales sont générées à partir de votre prénom et de votre nom.', 'Prénom', 'Nom', 'E-mail du compte', 'Vous pouvez modifier cela à tout moment.', 'Annuler', 'Enregistrement…', 'Enregistrer', 'Choisissez une image JPEG, PNG ou WebP.', 'La photo doit faire 5 Mo maximum.', 'Le prénom est obligatoire.', 'Choisissez une photo avant d’utiliser le mode photo.', 'Impossible d’enregistrer le profil. Réessayez.'],
  nl: ['Profiel', 'Beheer je naam en profielweergave in MoneyPilot.', 'Sluiten', 'Profielweergave', 'Kies of MoneyPilot je foto of initialen toont.', 'Foto', 'Initialen', 'Profielfoto kiezen', 'Foto wijzigen', 'Foto verwijderen', 'JPEG, PNG of WebP · Maximaal 5 MB', 'Naam', 'Je initialen worden uit je voor- en achternaam gevormd.', 'Voornaam', 'Achternaam', 'E-mailadres van account', 'Je kunt dit op elk moment wijzigen.', 'Annuleren', 'Opslaan…', 'Wijzigingen opslaan', 'Kies een JPEG-, PNG- of WebP-afbeelding.', 'Profielfoto’s mogen maximaal 5 MB zijn.', 'Voornaam is verplicht.', 'Kies een profielfoto voordat je de fotomodus gebruikt.', 'Het profiel kon niet worden opgeslagen. Probeer opnieuw.'],
  it: ['Profilo', 'Gestisci il nome e l’aspetto del profilo in MoneyPilot.', 'Chiudi', 'Aspetto del profilo', 'Scegli se MoneyPilot mostra la foto o le iniziali.', 'Foto', 'Iniziali', 'Scegli foto del profilo', 'Cambia foto', 'Rimuovi foto', 'JPEG, PNG o WebP · Massimo 5 MB', 'Nome', 'Le iniziali sono generate dal nome e dal cognome.', 'Nome', 'Cognome', 'E-mail dell’account', 'Puoi modificarlo in qualsiasi momento.', 'Annulla', 'Salvataggio…', 'Salva modifiche', 'Scegli un’immagine JPEG, PNG o WebP.', 'La foto deve essere di massimo 5 MB.', 'Il nome è obbligatorio.', 'Scegli una foto prima di usare la modalità foto.', 'Impossibile salvare il profilo. Riprova.'],
};
export const profileIdentityCopy = Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(keys.map((key, index) => [key, row[index]]))])) as Record<Language, ProfileIdentityCopy>;
