import type { Language } from "@/i18n/config";
import type { CategoryCreateInput, CategoryType, CategoryUpdateInput } from "@/lib/domain/category";

export type CategoryDraft = Readonly<{ name: string; type: CategoryType; iconKey: string; colorToken: string }>;

export function buildCategoryCreateInput(draft: CategoryDraft): Omit<CategoryCreateInput, "id" | "userId"> {
  return { name: draft.name, type: draft.type, iconKey: draft.iconKey, colorToken: draft.colorToken };
}

export function buildCategoryUpdateInput(draft: CategoryDraft): CategoryUpdateInput {
  return { name: draft.name, iconKey: draft.iconKey, colorToken: draft.colorToken };
}

const en = { showActive: "Active", showArchived: "Archived", type: "Type / status", income: "Income", expense: "Expense", active: "Active", archived: "Archived", loading: "Loading categoriesâ€¦", emptyActive: "No active categories yet.", emptyArchived: "No archived categories.", loadError: "Some financial data could not be loaded. The available categories remain visible.", authError: "Sign in again to manage categories.", unavailableError: "Categories are temporarily unavailable. Try again.", genericError: "The category could not be saved. Try again.", duplicateError: "A category with this name and type already exists.", validationError: "Review the category name, icon and color.", ownershipError: "You do not have permission to change this category.", createTitle: "New category", editTitle: "Edit category", name: "Category name", icon: "Icon", color: "Color", categoryType: "Category type", cancel: "Cancel", create: "Create category", save: "Save changes", creating: "Creatingâ€¦", saving: "Savingâ€¦", close: "Close editor", edit: "Edit", archive: "Archive", restore: "Restore", archiveTitle: "Archive category?", restoreTitle: "Restore category?", archiveDescription: "The category will leave the active list and can be restored later.", restoreDescription: "The category will return to the active list.", confirmArchive: "Archive category", confirmRestore: "Restore category", archiving: "Archivingâ€¦", restoring: "Restoringâ€¦", successCreated: "Category created.", successUpdated: "Category updated.", successArchived: "Category archived.", successRestored: "Category restored.", formHint: "Name, icon and color can be changed later. Type is immutable after creation." };
type CategoryPageCopy = typeof en;
const copy: Record<Language, CategoryPageCopy> = {
  en,
  pt: { showActive: "Ativas", showArchived: "Arquivadas", type: "Tipo / estado", income: "Receita", expense: "Despesa", active: "Ativa", archived: "Arquivada", loading: "Carregando categoriasâ€¦", emptyActive: "Nenhuma categoria ativa ainda.", emptyArchived: "Nenhuma categoria arquivada.", loadError: "Alguns dados financeiros nÃ£o puderam ser carregados. As categorias disponÃ­veis continuam visÃ­veis.", authError: "Entre novamente para gerenciar categorias.", unavailableError: "As categorias estÃ£o temporariamente indisponÃ­veis. Tente novamente.", genericError: "NÃ£o foi possÃ­vel salvar a categoria. Tente novamente.", duplicateError: "JÃ¡ existe uma categoria com este nome e tipo.", validationError: "Revise o nome, o Ã­cone e a cor da categoria.", ownershipError: "VocÃª nÃ£o tem permissÃ£o para alterar esta categoria.", createTitle: "Nova categoria", editTitle: "Editar categoria", name: "Nome da categoria", icon: "Ãcone", color: "Cor", categoryType: "Tipo da categoria", cancel: "Cancelar", create: "Criar categoria", save: "Salvar alteraÃ§Ãµes", creating: "Criandoâ€¦", saving: "Salvandoâ€¦", close: "Fechar editor", edit: "Editar", archive: "Arquivar", restore: "Restaurar", archiveTitle: "Arquivar categoria?", restoreTitle: "Restaurar categoria?", archiveDescription: "A categoria sairÃ¡ da lista ativa e poderÃ¡ ser restaurada depois.", restoreDescription: "A categoria voltarÃ¡ para a lista ativa.", confirmArchive: "Arquivar categoria", confirmRestore: "Restaurar categoria", archiving: "Arquivandoâ€¦", restoring: "Restaurandoâ€¦", successCreated: "Categoria criada.", successUpdated: "Categoria atualizada.", successArchived: "Categoria arquivada.", successRestored: "Categoria restaurada.", formHint: "Nome, Ã­cone e cor podem ser alterados depois. O tipo Ã© imutÃ¡vel apÃ³s a criaÃ§Ã£o." },
  es: { showActive: "Activas", showArchived: "Archivadas", type: "Tipo / estado", income: "Ingreso", expense: "Gasto", active: "Activa", archived: "Archivada", loading: "Cargando categorÃ­asâ€¦", emptyActive: "AÃºn no hay categorÃ­as activas.", emptyArchived: "No hay categorÃ­as archivadas.", loadError: "No se pudieron cargar algunos datos financieros. Las categorÃ­as disponibles siguen visibles.", authError: "Inicia sesiÃ³n de nuevo para gestionar categorÃ­as.", unavailableError: "Las categorÃ­as no estÃ¡n disponibles temporalmente. IntÃ©ntalo de nuevo.", genericError: "No se pudo guardar la categorÃ­a. IntÃ©ntalo de nuevo.", duplicateError: "Ya existe una categorÃ­a con este nombre y tipo.", validationError: "Revisa el nombre, el icono y el color de la categorÃ­a.", ownershipError: "No tienes permiso para cambiar esta categorÃ­a.", createTitle: "Nueva categorÃ­a", editTitle: "Editar categorÃ­a", name: "Nombre de la categorÃ­a", icon: "Icono", color: "Color", categoryType: "Tipo de categorÃ­a", cancel: "Cancelar", create: "Crear categorÃ­a", save: "Guardar cambios", creating: "Creandoâ€¦", saving: "Guardandoâ€¦", close: "Cerrar editor", edit: "Editar", archive: "Archivar", restore: "Restaurar", archiveTitle: "Â¿Archivar categorÃ­a?", restoreTitle: "Â¿Restaurar categorÃ­a?", archiveDescription: "La categorÃ­a saldrÃ¡ de la lista activa y podrÃ¡ restaurarse despuÃ©s.", restoreDescription: "La categorÃ­a volverÃ¡ a la lista activa.", confirmArchive: "Archivar categorÃ­a", confirmRestore: "Restaurar categorÃ­a", archiving: "Archivandoâ€¦", restoring: "Restaurandoâ€¦", successCreated: "CategorÃ­a creada.", successUpdated: "CategorÃ­a actualizada.", successArchived: "CategorÃ­a archivada.", successRestored: "CategorÃ­a restaurada.", formHint: "El nombre, el icono y el color pueden cambiarse despuÃ©s. El tipo es inmutable tras la creaciÃ³n." },
  de: { showActive: "Aktiv", showArchived: "Archiviert", type: "Typ / Status", income: "Einnahme", expense: "Ausgabe", active: "Aktiv", archived: "Archiviert", loading: "Kategorien werden geladenâ€¦", emptyActive: "Noch keine aktiven Kategorien.", emptyArchived: "Keine archivierten Kategorien.", loadError: "Einige Finanzdaten konnten nicht geladen werden. VerfÃ¼gbare Kategorien bleiben sichtbar.", authError: "Melde dich erneut an, um Kategorien zu verwalten.", unavailableError: "Kategorien sind vorÃ¼bergehend nicht verfÃ¼gbar. Versuche es erneut.", genericError: "Die Kategorie konnte nicht gespeichert werden. Versuche es erneut.", duplicateError: "Eine Kategorie mit diesem Namen und Typ existiert bereits.", validationError: "PrÃ¼fe Name, Symbol und Farbe der Kategorie.", ownershipError: "Du darfst diese Kategorie nicht Ã¤ndern.", createTitle: "Neue Kategorie", editTitle: "Kategorie bearbeiten", name: "Kategoriename", icon: "Symbol", color: "Farbe", categoryType: "Kategorietyp", cancel: "Abbrechen", create: "Kategorie erstellen", save: "Ã„nderungen speichern", creating: "Erstellenâ€¦", saving: "Speichernâ€¦", close: "Editor schlieÃŸen", edit: "Bearbeiten", archive: "Archivieren", restore: "Wiederherstellen", archiveTitle: "Kategorie archivieren?", restoreTitle: "Kategorie wiederherstellen?", archiveDescription: "Die Kategorie verlÃ¤sst die aktive Liste und kann spÃ¤ter wiederhergestellt werden.", restoreDescription: "Die Kategorie kehrt in die aktive Liste zurÃ¼ck.", confirmArchive: "Kategorie archivieren", confirmRestore: "Kategorie wiederherstellen", archiving: "Archivierenâ€¦", restoring: "Wiederherstellenâ€¦", successCreated: "Kategorie erstellt.", successUpdated: "Kategorie aktualisiert.", successArchived: "Kategorie archiviert.", successRestored: "Kategorie wiederhergestellt.", formHint: "Name, Symbol und Farbe kÃ¶nnen spÃ¤ter geÃ¤ndert werden. Der Typ ist nach der Erstellung unverÃ¤nderlich." },
  fr: { showActive: "Actives", showArchived: "ArchivÃ©es", type: "Type / statut", income: "Revenu", expense: "DÃ©pense", active: "Active", archived: "ArchivÃ©e", loading: "Chargement des catÃ©goriesâ€¦", emptyActive: "Aucune catÃ©gorie active.", emptyArchived: "Aucune catÃ©gorie archivÃ©e.", loadError: "Certaines donnÃ©es financiÃ¨res nâ€™ont pas pu Ãªtre chargÃ©es. Les catÃ©gories disponibles restent visibles.", authError: "Reconnectez-vous pour gÃ©rer les catÃ©gories.", unavailableError: "Les catÃ©gories sont temporairement indisponibles. RÃ©essayez.", genericError: "Impossible dâ€™enregistrer la catÃ©gorie. RÃ©essayez.", duplicateError: "Une catÃ©gorie avec ce nom et ce type existe dÃ©jÃ .", validationError: "VÃ©rifiez le nom, lâ€™icÃ´ne et la couleur de la catÃ©gorie.", ownershipError: "Vous nâ€™Ãªtes pas autorisÃ© Ã  modifier cette catÃ©gorie.", createTitle: "Nouvelle catÃ©gorie", editTitle: "Modifier la catÃ©gorie", name: "Nom de la catÃ©gorie", icon: "IcÃ´ne", color: "Couleur", categoryType: "Type de catÃ©gorie", cancel: "Annuler", create: "CrÃ©er la catÃ©gorie", save: "Enregistrer", creating: "CrÃ©ationâ€¦", saving: "Enregistrementâ€¦", close: "Fermer lâ€™Ã©diteur", edit: "Modifier", archive: "Archiver", restore: "Restaurer", archiveTitle: "Archiver la catÃ©gorie ?", restoreTitle: "Restaurer la catÃ©gorie ?", archiveDescription: "La catÃ©gorie quittera la liste active et pourra Ãªtre restaurÃ©e plus tard.", restoreDescription: "La catÃ©gorie reviendra dans la liste active.", confirmArchive: "Archiver la catÃ©gorie", confirmRestore: "Restaurer la catÃ©gorie", archiving: "Archivageâ€¦", restoring: "Restaurationâ€¦", successCreated: "CatÃ©gorie crÃ©Ã©e.", successUpdated: "CatÃ©gorie mise Ã  jour.", successArchived: "CatÃ©gorie archivÃ©e.", successRestored: "CatÃ©gorie restaurÃ©e.", formHint: "Le nom, lâ€™icÃ´ne et la couleur peuvent Ãªtre modifiÃ©s ensuite. Le type est immuable aprÃ¨s la crÃ©ation." },
  nl: { showActive: "Actief", showArchived: "Gearchiveerd", type: "Type / status", income: "Inkomst", expense: "Uitgave", active: "Actief", archived: "Gearchiveerd", loading: "CategorieÃ«n ladenâ€¦", emptyActive: "Nog geen actieve categorieÃ«n.", emptyArchived: "Geen gearchiveerde categorieÃ«n.", loadError: "Sommige financiÃ«le gegevens konden niet worden geladen. Beschikbare categorieÃ«n blijven zichtbaar.", authError: "Meld je opnieuw aan om categorieÃ«n te beheren.", unavailableError: "CategorieÃ«n zijn tijdelijk niet beschikbaar. Probeer opnieuw.", genericError: "De categorie kon niet worden opgeslagen. Probeer opnieuw.", duplicateError: "Er bestaat al een categorie met deze naam en dit type.", validationError: "Controleer de naam, het pictogram en de kleur van de categorie.", ownershipError: "Je hebt geen toestemming om deze categorie te wijzigen.", createTitle: "Nieuwe categorie", editTitle: "Categorie bewerken", name: "Categorienaam", icon: "Pictogram", color: "Kleur", categoryType: "Categorietype", cancel: "Annuleren", create: "Categorie maken", save: "Wijzigingen opslaan", creating: "Makenâ€¦", saving: "Opslaanâ€¦", close: "Editor sluiten", edit: "Bewerken", archive: "Archiveren", restore: "Herstellen", archiveTitle: "Categorie archiveren?", restoreTitle: "Categorie herstellen?", archiveDescription: "De categorie verdwijnt uit de actieve lijst en kan later worden hersteld.", restoreDescription: "De categorie keert terug naar de actieve lijst.", confirmArchive: "Categorie archiveren", confirmRestore: "Categorie herstellen", archiving: "Archiverenâ€¦", restoring: "Herstellenâ€¦", successCreated: "Categorie gemaakt.", successUpdated: "Categorie bijgewerkt.", successArchived: "Categorie gearchiveerd.", successRestored: "Categorie hersteld.", formHint: "Naam, pictogram en kleur kunnen later worden gewijzigd. Het type kan na het maken niet worden aangepast." },
  it: { showActive: "Attive", showArchived: "Archiviate", type: "Tipo / stato", income: "Entrata", expense: "Spesa", active: "Attiva", archived: "Archiviata", loading: "Caricamento categorieâ€¦", emptyActive: "Non ci sono ancora categorie attive.", emptyArchived: "Nessuna categoria archiviata.", loadError: "Alcuni dati finanziari non sono stati caricati. Le categorie disponibili restano visibili.", authError: "Accedi di nuovo per gestire le categorie.", unavailableError: "Le categorie non sono temporaneamente disponibili. Riprova.", genericError: "Impossibile salvare la categoria. Riprova.", duplicateError: "Esiste giÃ  una categoria con questo nome e tipo.", validationError: "Controlla il nome, lâ€™icona e il colore della categoria.", ownershipError: "Non hai il permesso di modificare questa categoria.", createTitle: "Nuova categoria", editTitle: "Modifica categoria", name: "Nome categoria", icon: "Icona", color: "Colore", categoryType: "Tipo di categoria", cancel: "Annulla", create: "Crea categoria", save: "Salva modifiche", creating: "Creazioneâ€¦", saving: "Salvataggioâ€¦", close: "Chiudi editor", edit: "Modifica", archive: "Archivia", restore: "Ripristina", archiveTitle: "Archiviare la categoria?", restoreTitle: "Ripristinare la categoria?", archiveDescription: "La categoria uscirÃ  dallâ€™elenco attivo e potrÃ  essere ripristinata in seguito.", restoreDescription: "La categoria tornerÃ  nellâ€™elenco attivo.", confirmArchive: "Archivia categoria", confirmRestore: "Ripristina categoria", archiving: "Archiviazioneâ€¦", restoring: "Ripristinoâ€¦", successCreated: "Categoria creata.", successUpdated: "Categoria aggiornata.", successArchived: "Categoria archiviata.", successRestored: "Categoria ripristinata.", formHint: "Nome, icona e colore possono essere modificati in seguito. Il tipo Ã¨ immutabile dopo la creazione." },
};
export function getCategoryPageCopy(language: Language) { return copy[language] ?? copy.en; }

const categoryFutureCopy = {
  en: { activeMetricLabel: "Active categories", activeMetricDetail: "Custom active categories", rulesMetricLabel: "Automatic rules", merchantsMetricLabel: "Mapped merchants", classificationMetricLabel: "Automatic classification", unavailableDetail: "Not available yet", comingSoon: "Coming soon", rulesSectionTitle: "Automatic rules", rulesEmptyTitle: "Rules are not available yet", rulesEmptyDescription: "Automatic merchant mapping will be available in a future update.", actions: "Actions" },
  pt: { activeMetricLabel: "Categorias ativas", activeMetricDetail: "Categorias personalizadas ativas", rulesMetricLabel: "Regras automáticas", merchantsMetricLabel: "Comerciantes mapeados", classificationMetricLabel: "Classificação automática", unavailableDetail: "Ainda não disponível", comingSoon: "Em breve", rulesSectionTitle: "Regras automáticas", rulesEmptyTitle: "As regras ainda não estão disponíveis", rulesEmptyDescription: "O mapeamento automático de comerciantes estará disponível em uma atualização futura.", actions: "Ações" },
  es: { activeMetricLabel: "Categorías activas", activeMetricDetail: "Categorías personalizadas activas", rulesMetricLabel: "Reglas automáticas", merchantsMetricLabel: "Comercios asignados", classificationMetricLabel: "Clasificación automática", unavailableDetail: "Aún no disponible", comingSoon: "Próximamente", rulesSectionTitle: "Reglas automáticas", rulesEmptyTitle: "Las reglas aún no están disponibles", rulesEmptyDescription: "La asignación automática de comercios estará disponible en una futura actualización.", actions: "Acciones" },
  de: { activeMetricLabel: "Aktive Kategorien", activeMetricDetail: "Aktive benutzerdefinierte Kategorien", rulesMetricLabel: "Automatische Regeln", merchantsMetricLabel: "Zugeordnete Händler", classificationMetricLabel: "Automatische Klassifizierung", unavailableDetail: "Noch nicht verfügbar", comingSoon: "Demnächst", rulesSectionTitle: "Automatische Regeln", rulesEmptyTitle: "Regeln sind noch nicht verfügbar", rulesEmptyDescription: "Die automatische Händlerzuordnung wird in einem zukünftigen Update verfügbar sein.", actions: "Aktionen" },
  fr: { activeMetricLabel: "Catégories actives", activeMetricDetail: "Catégories personnalisées actives", rulesMetricLabel: "Règles automatiques", merchantsMetricLabel: "Commerçants associés", classificationMetricLabel: "Classification automatique", unavailableDetail: "Pas encore disponible", comingSoon: "Bientôt disponible", rulesSectionTitle: "Règles automatiques", rulesEmptyTitle: "Les règles ne sont pas encore disponibles", rulesEmptyDescription: "L'association automatique des commerçants sera disponible dans une prochaine mise à jour.", actions: "Actions" },
  nl: { activeMetricLabel: "Actieve categorieën", activeMetricDetail: "Actieve aangepaste categorieën", rulesMetricLabel: "Automatische regels", merchantsMetricLabel: "Gekoppelde verkopers", classificationMetricLabel: "Automatische classificatie", unavailableDetail: "Nog niet beschikbaar", comingSoon: "Binnenkort", rulesSectionTitle: "Automatische regels", rulesEmptyTitle: "Regels zijn nog niet beschikbaar", rulesEmptyDescription: "Automatische verkoperskoppeling wordt beschikbaar in een toekomstige update.", actions: "Acties" },
  it: { activeMetricLabel: "Categorie attive", activeMetricDetail: "Categorie personalizzate attive", rulesMetricLabel: "Regole automatiche", merchantsMetricLabel: "Commercianti associati", classificationMetricLabel: "Classificazione automatica", unavailableDetail: "Non ancora disponibile", comingSoon: "Prossimamente", rulesSectionTitle: "Regole automatiche", rulesEmptyTitle: "Le regole non sono ancora disponibili", rulesEmptyDescription: "L'associazione automatica dei commercianti sarà disponibile in un aggiornamento futuro.", actions: "Azioni" },
} satisfies Record<Language, Record<string, string>>;
export function getCategoryFutureCopy(language: Language) { return categoryFutureCopy[language] ?? categoryFutureCopy.en; }

const categoryBenefits = {
  en: [{ title: "Automatic classification", copy: "In the future, rules will be able to organize transactions.", icon: "automation" }, { title: "Consistent reports", copy: "Categories help compare periods.", icon: "report" }, { title: "Less manual work", copy: "Future rules will be able to reduce adjustments.", icon: "time" }, { title: "More accurate insights", copy: "Organized categories help with analysis.", icon: "analytics" }],
  pt: [{ title: "Classificação automática", copy: "No futuro, regras poderão organizar transações.", icon: "automation" }, { title: "Relatórios consistentes", copy: "Categorias ajudam a comparar períodos.", icon: "report" }, { title: "Menos trabalho manual", copy: "Regras futuras poderão reduzir ajustes.", icon: "time" }, { title: "Insights mais precisos", copy: "Categorias organizadas ajudam nas análises.", icon: "analytics" }],
  es: [{ title: "Clasificación automática", copy: "En el futuro, las reglas podrán organizar transacciones.", icon: "automation" }, { title: "Informes consistentes", copy: "Las categorías ayudan a comparar periodos.", icon: "report" }, { title: "Menos trabajo manual", copy: "Las reglas futuras podrán reducir ajustes.", icon: "time" }, { title: "Análisis más precisos", copy: "Las categorías organizadas ayudan al análisis.", icon: "analytics" }],
  de: [{ title: "Automatische Klassifizierung", copy: "Künftig können Regeln Transaktionen organisieren.", icon: "automation" }, { title: "Einheitliche Berichte", copy: "Kategorien helfen beim Vergleich von Zeiträumen.", icon: "report" }, { title: "Weniger manuelle Arbeit", copy: "Künftige Regeln können Anpassungen reduzieren.", icon: "time" }, { title: "Genauere Einblicke", copy: "Geordnete Kategorien unterstützen die Analyse.", icon: "analytics" }],
  fr: [{ title: "Classification automatique", copy: "À l'avenir, des règles pourront organiser les transactions.", icon: "automation" }, { title: "Rapports cohérents", copy: "Les catégories facilitent la comparaison des périodes.", icon: "report" }, { title: "Moins de travail manuel", copy: "Les futures règles pourront réduire les ajustements.", icon: "time" }, { title: "Analyses plus précises", copy: "Des catégories organisées facilitent l'analyse.", icon: "analytics" }],
  nl: [{ title: "Automatische classificatie", copy: "In de toekomst kunnen regels transacties organiseren.", icon: "automation" }, { title: "Consistente rapporten", copy: "Categorieën helpen periodes te vergelijken.", icon: "report" }, { title: "Minder handmatig werk", copy: "Toekomstige regels kunnen aanpassingen beperken.", icon: "time" }, { title: "Nauwkeurigere inzichten", copy: "Geordende categorieën ondersteunen analyses.", icon: "analytics" }],
  it: [{ title: "Classificazione automatica", copy: "In futuro, le regole potranno organizzare le transazioni.", icon: "automation" }, { title: "Report coerenti", copy: "Le categorie aiutano a confrontare i periodi.", icon: "report" }, { title: "Meno lavoro manuale", copy: "Le regole future potranno ridurre le modifiche.", icon: "time" }, { title: "Analisi più precise", copy: "Le categorie organizzate aiutano l'analisi.", icon: "analytics" }],
} satisfies Record<Language, readonly { title: string; copy: string; icon: string }[]>;
export function getCategoryBenefits(language: Language) { return categoryBenefits[language] ?? categoryBenefits.en; }

export type CategoryFriendlyOption = Readonly<{ value: string; label: string }>;
const iconValues = ["tag", "home", "cart", "delivery", "transport", "health", "leisure", "subscription", "shopping", "more"] as const;
const colorValues = ["blue-500", "green-500", "amber-500", "violet-500", "teal-500", "rose-500", "slate-400"] as const;
const iconLabels: Record<Language, readonly string[]> = {
  en: ["Tag", "Home", "Cart", "Delivery", "Transport", "Health", "Leisure", "Subscription", "Shopping", "Other"],
  pt: ["Etiqueta", "Casa", "Carrinho", "Entrega", "Transporte", "Saúde", "Lazer", "Assinatura", "Compras", "Outro"],
  es: ["Etiqueta", "Casa", "Carrito", "Entrega", "Transporte", "Salud", "Ocio", "Suscripción", "Compras", "Otro"],
  de: ["Etikett", "Wohnen", "Warenkorb", "Lieferung", "Transport", "Gesundheit", "Freizeit", "Abonnement", "Einkäufe", "Sonstiges"],
  fr: ["Étiquette", "Maison", "Panier", "Livraison", "Transport", "Santé", "Loisirs", "Abonnement", "Achats", "Autre"],
  nl: ["Label", "Wonen", "Winkelwagen", "Bezorging", "Vervoer", "Gezondheid", "Vrije tijd", "Abonnement", "Winkelen", "Overig"],
  it: ["Etichetta", "Casa", "Carrello", "Consegna", "Trasporti", "Salute", "Tempo libero", "Abbonamento", "Acquisti", "Altro"],
};
const colorLabels: Record<Language, readonly string[]> = {
  en: ["Blue", "Green", "Amber", "Violet", "Teal", "Rose", "Slate"],
  pt: ["Azul", "Verde", "Âmbar", "Violeta", "Turquesa", "Rosa", "Cinza"],
  es: ["Azul", "Verde", "Ámbar", "Violeta", "Turquesa", "Rosa", "Gris"],
  de: ["Blau", "Grün", "Bernstein", "Violett", "Türkis", "Rosa", "Grau"],
  fr: ["Bleu", "Vert", "Ambre", "Violet", "Turquoise", "Rose", "Gris"],
  nl: ["Blauw", "Groen", "Amber", "Violet", "Turkoois", "Roze", "Grijs"],
  it: ["Blu", "Verde", "Ambra", "Viola", "Turchese", "Rosa", "Grigio"],
};
function friendlyOptions(values: readonly string[], labels: readonly string[]): CategoryFriendlyOption[] { return values.map((value, index) => ({ value, label: labels[index] })); }
export function getCategoryIconOptions(language: Language) { return friendlyOptions(iconValues, iconLabels[language] ?? iconLabels.en); }
export function getCategoryColorOptions(language: Language) { return friendlyOptions(colorValues, colorLabels[language] ?? colorLabels.en); }
