"use client";

import { useCurrency } from "@/components/CurrencyProvider";

import { useEffect } from "react";
import { IconEdit, IconGauge, IconX } from "@tabler/icons-react";

import type { BudgetAdjustment } from "@/components/budgets/budget-model";
import type { BudgetProjection } from "@/components/budgets/budget-projection";
import { canApplyBudgetAdjustment, createBudgetAdjustment } from "@/components/budgets/budget-projection";
import { useLanguage, type Language } from "@/components/LanguageProvider";

export type ProjectionModalView = "projection" | "adjustment";

type BudgetProjectionModalProps = {
  view: ProjectionModalView;
  month: string;
  projection: BudgetProjection;
  adjustment?: BudgetAdjustment;
  onClose: () => void;
  onBack: () => void;
  onReview: () => void;
  onApply: (adjustment: BudgetAdjustment) => void;
};

export function BudgetProjectionModal({ view, month, projection, adjustment, onClose, onBack, onReview, onApply }: BudgetProjectionModalProps) {
  const { language } = useLanguage();
  const { formatMoney: money } = useCurrency();
  const locale = language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-IE";
  const percent = (value: number) => `${value.toLocaleString(locale, { maximumFractionDigits: 1 })}%`;
  const canAdjust = canApplyBudgetAdjustment(projection);
  const monthLabel = formatMonth(month, locale);
  const copy = getCopy(language);
  const displayedTarget = adjustment?.targetRemainingSpend ?? projection.remainingSpendTarget;
  const displayedAdjustment = adjustment?.adjustmentNeeded ?? projection.adjustmentNeeded;
  const displayedWeeklyReduction = adjustment?.suggestedWeeklyReduction ?? projection.suggestedWeeklyReduction;

  useEffect(() => {
    function closeOnEscape(event: KeyboardEvent) {
      if (event.key === "Escape") onClose();
    }
    window.addEventListener("keydown", closeOnEscape);
    return () => window.removeEventListener("keydown", closeOnEscape);
  }, [onClose]);

  const differenceLabel = projection.projectedDifference > 0
    ? `+ ${money(projection.projectedDifference)} ${copy.abovePlan}`
    : projection.projectedDifference < 0
      ? `${money(Math.abs(projection.projectedDifference))} ${copy.belowPlan}`
      : copy.onTrack;

  function applyAdjustment() {
    const adjustment = createBudgetAdjustment(month, projection);
    if (adjustment) onApply(adjustment);
  }

  return (
    <div className="absolute inset-0 z-[70] flex items-center justify-center bg-[#02060A]/68 backdrop-blur-[2px]" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
      {view === "projection" ? (
        <section role="dialog" aria-modal="true" aria-labelledby="budget-projection-title" className="relative h-[648px] w-[720px] overflow-hidden rounded-[24px] border border-[var(--border-default)] bg-[var(--background-elevated)] text-[var(--text-primary)] shadow-[0_24px_24px_rgba(0,0,0,0.5)]">
          <ModalHeader icon={<IconGauge size={20} />} titleId="budget-projection-title" title={copy.projectionTitle} description={copy.projectionDescription} month={monthLabel} onClose={onClose} />
          <div className="absolute left-[27px] top-[95px] grid w-[666px] grid-cols-3 gap-[16px]">
            <MetricCard label={copy.planned} value={money(projection.plannedTotal)} />
            <MetricCard label={copy.spent} value={money(projection.spentTotal)} />
            <MetricCard label={copy.elapsed} value={percent(projection.monthElapsedPercent)} />
          </div>
          <div className="absolute left-[27px] top-[203px] h-[126px] w-[666px] rounded-[16px] border border-[#1E427A] bg-[var(--surface-blue-medium)] p-[15px]">
            <p className="text-[9px] font-semibold text-[#3B82F6]">{copy.projectedClose}</p>
            <strong className="mt-[6px] block text-[25px] leading-[30px]">{money(projection.projectedTotal)}</strong>
            <span className={`absolute right-[18px] top-[19px] rounded-[14px] border px-[14px] py-[7px] text-[9px] font-semibold ${projection.projectedDifference > 0 ? "border-[#6B4A0E] bg-[var(--surface-warning-subtle)] text-[#F59E0B]" : "border-[#174D32] bg-[var(--surface-green-subtle)] text-[#22C55E]"}`}>{differenceLabel}</span>
            <p className="mt-[3px] text-[10px] text-[var(--text-tertiary)]">{copy.projectionNarrative(differenceLabel)}</p>
            <p className="mt-[8px] text-[9px] text-[var(--text-tertiary)]">{copy.formula}</p>
          </div>
          <div className="absolute left-[27px] top-[345px] grid h-[126px] w-[666px] grid-cols-2 gap-[16px]">
            <ProgressPanel projection={projection} percent={percent} copy={copy} />
            <div className="rounded-[16px] border border-[var(--border-default)] bg-[var(--background-secondary)] p-[15px]">
              <p className="text-[10px] font-semibold">{copy.recovery}</p>
              <p className="mt-[11px] text-[9px] text-[var(--text-tertiary)]">{copy.weeklyReduction}</p>
              <strong className="mt-[3px] block text-[18px] text-[#3B82F6]">{money(projection.suggestedWeeklyReduction)}</strong>
              <p className="mt-[7px] text-[9px] text-[var(--text-tertiary)]">{copy.remainingDays(projection.remainingDays)}</p>
            </div>
          </div>
          <div className="absolute left-[27px] top-[487px] h-[62px] w-[666px] rounded-[14px] border border-[var(--border-default)] bg-[var(--background-secondary)] px-[13px] py-[11px]"><p className="text-[10px] font-semibold">{projection.canProject ? copy.liveProjection : copy.unavailable}</p><p className="mt-[5px] text-[9px] text-[var(--text-tertiary)]">{copy.noMoneyMoved}</p></div>
          <div className="absolute bottom-[27px] right-[27px] flex gap-[10px]"><SecondaryButton onClick={onClose}>{copy.close}</SecondaryButton><PrimaryButton onClick={onReview} disabled={!canAdjust}>{projection.adjustmentNeeded > 0 ? copy.review : copy.onTrack}</PrimaryButton></div>
        </section>
      ) : (
        <section role="dialog" aria-modal="true" aria-labelledby="budget-adjustment-title" className="relative h-[650px] w-[680px] overflow-hidden rounded-[24px] border border-[var(--border-default)] bg-[var(--background-elevated)] text-[var(--text-primary)] shadow-[0_24px_24px_rgba(0,0,0,0.5)]">
          <ModalHeader icon={<IconEdit size={20} />} titleId="budget-adjustment-title" title={copy.reviewTitle} description={copy.reviewDescription} month={monthLabel} onClose={onClose} />
          <div className="absolute left-[27px] top-[95px] h-[92px] w-[626px] rounded-[14px] border border-[var(--border-default)] bg-[var(--background-secondary)] p-[13px]"><p className="text-[10px] font-semibold">{copy.currentProjection}</p><strong className="mt-[5px] block text-[19px]">{money(projection.projectedTotal)}</strong><p className="mt-[5px] text-[9px] text-[var(--text-tertiary)]">{copy.currentPace}: {money(projection.currentRemainingProjectedSpend)}</p></div>
          <p className="absolute left-[27px] top-[202px] text-[12px] font-semibold">{copy.suggestedTarget}</p>
          <div className="absolute left-[27px] top-[231px] grid h-[120px] w-[626px] grid-cols-2 gap-[24px]">
            <TargetCard label={copy.remainingTarget} value={money(displayedTarget)} detail={displayedTarget === 0 ? copy.noAdditionalSpend : copy.maxAdditionalSpend} primary />
            <TargetCard label={copy.reductionNeeded} value={money(displayedAdjustment)} detail={`${money(displayedWeeklyReduction)} ${copy.perWeek}`} />
          </div>
          <div className="absolute left-[27px] top-[369px] grid h-[86px] w-[626px] grid-cols-[1fr_1px_220px] items-center rounded-[16px] border border-[var(--border-default)] bg-[var(--background-secondary)] px-[13px]"><div><p className="text-[10px] font-semibold">{copy.beforeTarget}</p><Line label={copy.projectedRemaining} value={money(projection.currentRemainingProjectedSpend)} /><Line label={copy.newTarget} value={money(displayedTarget)} blue /></div><div className="h-[50px] bg-[var(--border-default)]" /><div className="pl-[20px]"><p className="text-[9px] text-[var(--text-tertiary)]">{copy.targetClose}</p><strong className="mt-[5px] block text-[16px] text-[#22C55E]">{money(projection.plannedTotal)}</strong></div></div>
          <div className="absolute left-[27px] top-[471px] h-[60px] w-[626px] rounded-[14px] border border-[#174D32] bg-[var(--surface-green-subtle)] px-[13px] py-[9px]"><p className="text-[10px] font-semibold text-[#22C55E]">{copy.targetOutcome}</p><p className="mt-[5px] text-[9px] text-[var(--text-tertiary)]">{copy.outcome(money(projection.plannedTotal))}</p></div>
          <div className="absolute left-[27px] top-[545px] h-[38px] w-[626px] rounded-[12px] border border-[var(--border-default)] bg-[var(--background-secondary)] px-[11px] py-[10px] text-[9px] text-[var(--text-tertiary)]">{copy.planningOnly}</div>
          <div className="absolute bottom-[17px] right-[27px] flex gap-[10px]"><SecondaryButton onClick={onBack}>{copy.back}</SecondaryButton><PrimaryButton onClick={applyAdjustment} disabled={!canAdjust}>{copy.apply}</PrimaryButton></div>
        </section>
      )}
    </div>
  );
}

function ModalHeader({ icon, titleId, title, description, month, onClose }: { icon: React.ReactNode; titleId: string; title: string; description: string; month: string; onClose: () => void }) { return <><div className="absolute left-[27px] top-[25px] flex size-[44px] items-center justify-center rounded-[22px] border border-[#1E427A] bg-[var(--surface-blue-subtle)] text-[#3B82F6]">{icon}</div><h2 id={titleId} className="absolute left-[87px] top-[24px] text-[20px] font-semibold">{title}</h2><p className="absolute left-[87px] top-[51px] text-[10px] text-[var(--text-tertiary)]">{description}</p><span className="absolute right-[59px] top-[29px] rounded-[13px] bg-[var(--surface-blue-subtle)] px-[13px] py-[6px] text-[9px] font-semibold text-[#3B82F6]">{month}</span><button type="button" onClick={onClose} aria-label="Close" className="absolute right-[25px] top-[31px] text-[var(--text-tertiary)]"><IconX size={18} /></button></>; }
function MetricCard({ label, value }: { label: string; value: string }) { return <div className="h-[92px] rounded-[14px] border border-[var(--border-default)] bg-[var(--background-secondary)] p-[13px]"><p className="text-[10px] font-semibold text-[var(--text-tertiary)]">{label}</p><strong className="mt-[8px] block text-[19px]">{value}</strong></div>; }
function ProgressPanel({ projection, percent, copy }: { projection: BudgetProjection; percent: (value: number) => string; copy: ReturnType<typeof getCopy> }) { return <div className="rounded-[16px] border border-[var(--border-default)] bg-[var(--background-secondary)] p-[15px]"><p className="text-[10px] font-semibold">{copy.pace}</p><Bar label={copy.budgetUsed} value={percent(projection.budgetUsedPercent)} width={projection.budgetUsedPercent} color="#3B82F6" /><Bar label={copy.elapsed} value={percent(projection.monthElapsedPercent)} width={projection.monthElapsedPercent} color="#38BDF8" /></div>; }
function Bar({ label, value, width, color }: { label: string; value: string; width: number; color: string }) { return <div className="mt-[10px]"><div className="flex justify-between text-[9px] text-[var(--text-tertiary)]"><span>{label}</span><strong style={{ color }}>{value}</strong></div><div className="mt-[4px] h-[6px] overflow-hidden rounded-full bg-[var(--background-disabled)]"><div className="h-full rounded-full" style={{ width: `${Math.min(width, 100)}%`, backgroundColor: color }} /></div></div>; }
function TargetCard({ label, value, detail, primary = false }: { label: string; value: string; detail: string; primary?: boolean }) { return <div className={`rounded-[16px] border p-[13px] ${primary ? "border-[#1E427A] bg-[var(--surface-blue-medium)]" : "border-[var(--border-default)] bg-[var(--background-secondary)]"}`}><p className={`text-[9px] font-semibold ${primary ? "text-[#3B82F6]" : "text-[var(--text-tertiary)]"}`}>{label}</p><strong className="mt-[7px] block text-[24px]">{value}</strong><p className="mt-[8px] text-[9px] text-[var(--text-tertiary)]">{detail}</p></div>; }
function Line({ label, value, blue = false }: { label: string; value: string; blue?: boolean }) { return <div className="mt-[6px] flex w-[320px] justify-between text-[9px]"><span className="text-[var(--text-tertiary)]">{label}</span><strong className={blue ? "text-[#3B82F6]" : ""}>{value}</strong></div>; }
function SecondaryButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <button type="button" onClick={onClick} className="h-[40px] min-w-[112px] rounded-[20px] border border-[var(--border-default)] bg-[var(--background-secondary)] px-[18px] text-[11px] font-semibold text-[var(--text-tertiary)]">{children}</button>; }
function PrimaryButton({ children, onClick, disabled }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled} className="h-[40px] min-w-[130px] rounded-[20px] bg-[#3B82F6] px-[18px] text-[11px] font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{children}</button>; }
function formatMonth(month: string, locale: string) { const [year, monthNumber] = month.split("-").map(Number); return new Intl.DateTimeFormat(locale, { month: "long", year: "numeric" }).format(new Date(year, monthNumber - 1, 1)); }

function getCopy(language: Language) {
  if (language === "de") return { projectionTitle: "Budgetprognose", projectionDescription: "Sieh, wie der Monat beim aktuellen Tempo abschließen könnte.", reviewTitle: "Anpassung prüfen", reviewDescription: "Lege ein Wiederherstellungsziel für den restlichen Monat fest.", planned: "Geplantes Budget", spent: "Bisher ausgegeben", elapsed: "Monat vergangen", projectedClose: "PROGNOSTIZIERTER ABSCHLUSS", abovePlan: "über dem Plan", belowPlan: "unter dem Plan", onTrack: "Im Plan", projectionNarrative: (value: string) => `Beim aktuellen Tempo liegt die Prognose ${value}.`, formula: "Prognose = aktuelle Ausgaben ÷ vergangener Monat", pace: "Budgettempo", budgetUsed: "Budget verwendet", recovery: "Empfohlene Erholung", weeklyReduction: "Empfohlene wöchentliche Reduzierung", remainingDays: (days: number) => `${days} Tage verbleiben`, liveProjection: "Live-Prognose", unavailable: "Die Prognose ist nach Monatsbeginn verfügbar.", noMoneyMoved: "Es wird kein Geld bewegt. Die Prognose folgt Transaktionen und Budgets.", close: "Schließen", review: "Anpassung prüfen", currentProjection: "Aktuelle Prognose", currentPace: "Aktuelles Resttempo", suggestedTarget: "Empfohlenes Wiederherstellungsziel", remainingTarget: "VERBLEIBENDES AUSGABENZIEL", maxAdditionalSpend: "maximale Zusatzausgabe, um im Plan zu bleiben", noAdditionalSpend: "Im aktuellen Plan sind keine weiteren Ausgaben verfügbar", reductionNeeded: "ERFORDERLICHE REDUZIERUNG", perWeek: "pro Woche", beforeTarget: "Vorher → Ziel", projectedRemaining: "Prognostizierte Restausgaben", newTarget: "Neues Restziel", targetClose: "Ziel für Monatsabschluss", targetOutcome: "Ergebnis: zurück zum Monatsplan", outcome: (total: string) => `Wenn dieses Ziel eingehalten wird, kehrt der prognostizierte Abschluss zum geplanten Wert von ${total} zurück.`, planningOnly: "Nur Planung — speichert ein Ausgabenziel in MoneyPilot. Es wird kein Geld bewegt und keine frühere Transaktion geändert.", back: "Zurück", apply: "Anpassung anwenden" };
  if (language === "fr") return { projectionTitle: "Prévision du budget", projectionDescription: "Voyez comment le mois pourrait se terminer au rythme actuel.", reviewTitle: "Réviser l’ajustement", reviewDescription: "Définissez un objectif de reprise pour le reste du mois.", planned: "Budget prévu", spent: "Dépensé à ce jour", elapsed: "Mois écoulé", projectedClose: "CLÔTURE PRÉVUE", abovePlan: "au-dessus du plan", belowPlan: "en dessous du plan", onTrack: "En bonne voie", projectionNarrative: (value: string) => `Au rythme actuel, la prévision est ${value}.`, formula: "Prévision = dépenses actuelles ÷ mois écoulé", pace: "Rythme du budget", budgetUsed: "Budget utilisé", recovery: "Reprise suggérée", weeklyReduction: "Réduction hebdomadaire suggérée", remainingDays: (days: number) => `${days} jours restants`, liveProjection: "Prévision en temps réel", unavailable: "La prévision sera disponible au début du mois.", noMoneyMoved: "Aucun argent n’est déplacé. La prévision suit Transactions et Budgets.", close: "Fermer", review: "Réviser l’ajustement", currentProjection: "Prévision actuelle", currentPace: "Rythme restant actuel", suggestedTarget: "Objectif de reprise suggéré", remainingTarget: "OBJECTIF DE DÉPENSE RESTANT", maxAdditionalSpend: "dépense supplémentaire maximale pour rester dans le plan", noAdditionalSpend: "Aucune dépense supplémentaire disponible dans le plan actuel", reductionNeeded: "RÉDUCTION NÉCESSAIRE", perWeek: "par semaine", beforeTarget: "Avant → objectif", projectedRemaining: "Dépenses restantes prévues", newTarget: "Nouvel objectif restant", targetClose: "Objectif de clôture", targetOutcome: "Résultat : retour au plan mensuel", outcome: (total: string) => `En suivant cet objectif, la clôture prévue revient au montant planifié de ${total}.`, planningOnly: "Planification uniquement — enregistre un objectif de dépenses dans MoneyPilot. Aucun argent n’est déplacé et aucune transaction passée n’est modifiée.", back: "Retour", apply: "Appliquer l’ajustement" };
  if (language === "nl") return { projectionTitle: "Budgetverwachting", projectionDescription: "Bekijk hoe de maand bij het huidige tempo kan eindigen.", reviewTitle: "Aanpassing bekijken", reviewDescription: "Stel een hersteldoel in voor de rest van de maand.", planned: "Gepland budget", spent: "Tot nu toe uitgegeven", elapsed: "Maand verstreken", projectedClose: "VERWACHTE AFSLUITING", abovePlan: "boven plan", belowPlan: "onder plan", onTrack: "Op schema", projectionNarrative: (value: string) => `Bij het huidige tempo is de verwachting ${value}.`, formula: "Verwachting = huidige uitgaven ÷ verstreken maand", pace: "Budgettempo", budgetUsed: "Budget gebruikt", recovery: "Voorgesteld herstel", weeklyReduction: "Voorgestelde wekelijkse vermindering", remainingDays: (days: number) => `${days} dagen resterend`, liveProjection: "Actuele verwachting", unavailable: "De verwachting is beschikbaar zodra de maand begint.", noMoneyMoved: "Er wordt geen geld verplaatst. De verwachting volgt Transacties en Budgetten.", close: "Sluiten", review: "Aanpassing bekijken", currentProjection: "Huidige verwachting", currentPace: "Huidig resterend tempo", suggestedTarget: "Voorgesteld hersteldoel", remainingTarget: "RESTEREND UITGAVENDOEL", maxAdditionalSpend: "maximale extra uitgaven om op schema te blijven", noAdditionalSpend: "Geen extra uitgaven beschikbaar binnen het huidige plan", reductionNeeded: "BENODIGDE VERMINDERING", perWeek: "per week", beforeTarget: "Voor → doel", projectedRemaining: "Verwachte resterende uitgaven", newTarget: "Nieuw resterend doel", targetClose: "Doel voor maandeinde", targetOutcome: "Resultaat: terug naar het maandplan", outcome: (total: string) => `Als dit doel wordt gevolgd, keert de verwachte afsluiting terug naar het geplande bedrag van ${total}.`, planningOnly: "Alleen planning — slaat een uitgavendoel op in MoneyPilot. Er wordt geen geld verplaatst en eerdere transacties worden niet gewijzigd.", back: "Terug", apply: "Aanpassing toepassen" };
  if (language === "it") return { projectionTitle: "Previsione del budget", projectionDescription: "Scopri come può chiudersi il mese al ritmo attuale.", reviewTitle: "Rivedi modifica", reviewDescription: "Imposta un obiettivo di recupero per il resto del mese.", planned: "Budget pianificato", spent: "Speso finora", elapsed: "Mese trascorso", projectedClose: "CHIUSURA PREVISTA", abovePlan: "sopra il piano", belowPlan: "sotto il piano", onTrack: "In linea", projectionNarrative: (value: string) => `Al ritmo attuale, la previsione è ${value}.`, formula: "Previsione = spesa attuale ÷ mese trascorso", pace: "Ritmo del budget", budgetUsed: "Budget utilizzato", recovery: "Recupero suggerito", weeklyReduction: "Riduzione settimanale suggerita", remainingDays: (days: number) => `${days} giorni rimanenti`, liveProjection: "Previsione in tempo reale", unavailable: "La previsione sarà disponibile all’inizio del mese.", noMoneyMoved: "Non viene spostato denaro. La previsione segue Transazioni e Budget.", close: "Chiudi", review: "Rivedi modifica", currentProjection: "Previsione attuale", currentPace: "Ritmo rimanente attuale", suggestedTarget: "Obiettivo di recupero suggerito", remainingTarget: "OBIETTIVO DI SPESA RIMANENTE", maxAdditionalSpend: "spesa aggiuntiva massima per restare nel piano", noAdditionalSpend: "Nessuna spesa aggiuntiva disponibile nel piano attuale", reductionNeeded: "RIDUZIONE NECESSARIA", perWeek: "a settimana", beforeTarget: "Prima → obiettivo", projectedRemaining: "Spesa rimanente prevista", newTarget: "Nuovo obiettivo rimanente", targetClose: "Obiettivo di chiusura", targetOutcome: "Risultato: ritorno al piano mensile", outcome: (total: string) => `Seguendo questo obiettivo, la chiusura prevista torna al valore pianificato di ${total}.`, planningOnly: "Solo pianificazione — salva un obiettivo di spesa in MoneyPilot. Non sposta denaro né modifica transazioni passate.", back: "Indietro", apply: "Applica modifica" };
  if (language === "pt") return { projectionTitle: "Projeção do orçamento", projectionDescription: "Veja como o mês pode fechar no ritmo atual.", reviewTitle: "Revisar ajuste", reviewDescription: "Defina uma meta de recuperação para o restante do mês.", planned: "Orçamento planejado", spent: "Gasto até agora", elapsed: "Mês transcorrido", projectedClose: "FECHAMENTO PROJETADO", abovePlan: "acima do plano", belowPlan: "abaixo do plano", onTrack: "No caminho certo", projectionNarrative: (value: string) => `No ritmo atual, a projeção está ${value}.`, formula: "Projeção = gasto atual ÷ mês transcorrido", pace: "Ritmo do orçamento", budgetUsed: "Orçamento usado", recovery: "Recuperação sugerida", weeklyReduction: "Redução semanal sugerida", remainingDays: (days: number) => `${days} dias restantes`, liveProjection: "Projeção atualizada em tempo real", unavailable: "A projeção estará disponível quando o mês começar.", noMoneyMoved: "Nenhum dinheiro é movimentado. A projeção acompanha Transactions e Budgets.", close: "Fechar", review: "Revisar ajuste", currentProjection: "Projeção atual", currentPace: "Ritmo restante atual", suggestedTarget: "Meta de recuperação sugerida", remainingTarget: "META DE GASTO RESTANTE", maxAdditionalSpend: "máximo adicional para permanecer no plano", noAdditionalSpend: "Nenhum gasto adicional disponível no plano atual", reductionNeeded: "REDUÇÃO NECESSÁRIA", perWeek: "por semana", beforeTarget: "Antes → meta", projectedRemaining: "Gasto restante projetado", newTarget: "Nova meta restante", targetClose: "Meta de fechamento", targetOutcome: "Resultado: voltar ao plano mensal", outcome: (total: string) => `Seguindo esta meta, o fechamento retorna ao planejado de ${total}.`, planningOnly: "Somente planejamento — salva uma meta no MoneyPilot. Não movimenta dinheiro nem edita transações passadas.", back: "Voltar", apply: "Aplicar ajuste" };
  if (language === "es") return { projectionTitle: "Proyección del presupuesto", projectionDescription: "Consulta cómo puede cerrar el mes al ritmo actual.", reviewTitle: "Revisar ajuste", reviewDescription: "Define un objetivo de recuperación para el resto del mes.", planned: "Presupuesto planificado", spent: "Gastado hasta ahora", elapsed: "Mes transcurrido", projectedClose: "CIERRE PROYECTADO", abovePlan: "por encima del plan", belowPlan: "por debajo del plan", onTrack: "Bien encaminado", projectionNarrative: (value: string) => `Al ritmo actual, la proyección está ${value}.`, formula: "Proyección = gasto actual ÷ mes transcurrido", pace: "Ritmo del presupuesto", budgetUsed: "Presupuesto usado", recovery: "Recuperación sugerida", weeklyReduction: "Reducción semanal sugerida", remainingDays: (days: number) => `${days} días restantes`, liveProjection: "Proyección actualizada en tiempo real", unavailable: "La proyección estará disponible cuando comience el mes.", noMoneyMoved: "No se mueve dinero. La proyección sigue Transactions y Budgets.", close: "Cerrar", review: "Revisar ajuste", currentProjection: "Proyección actual", currentPace: "Ritmo restante actual", suggestedTarget: "Objetivo de recuperación sugerido", remainingTarget: "OBJETIVO DE GASTO RESTANTE", maxAdditionalSpend: "máximo adicional para permanecer en el plan", noAdditionalSpend: "No hay gasto adicional disponible en el plan actual", reductionNeeded: "REDUCCIÓN NECESARIA", perWeek: "por semana", beforeTarget: "Antes → objetivo", projectedRemaining: "Gasto restante proyectado", newTarget: "Nuevo objetivo restante", targetClose: "Objetivo de cierre", targetOutcome: "Resultado: volver al plan mensual", outcome: (total: string) => `Siguiendo este objetivo, el cierre vuelve al planificado de ${total}.`, planningOnly: "Solo planificación: guarda un objetivo en MoneyPilot. No mueve dinero ni edita transacciones pasadas.", back: "Volver", apply: "Aplicar ajuste" };
  return { projectionTitle: "Budget projection", projectionDescription: "See how the month may close at the current pace.", reviewTitle: "Review adjustment", reviewDescription: "Set a recovery target for the rest of the month.", planned: "Planned budget", spent: "Spent so far", elapsed: "Month elapsed", projectedClose: "PROJECTED CLOSE", abovePlan: "above plan", belowPlan: "below plan", onTrack: "On track", projectionNarrative: (value: string) => `At the current pace, the projection is ${value}.`, formula: "Projection = current spend ÷ month elapsed", pace: "Budget pace", budgetUsed: "Budget used", recovery: "Suggested recovery", weeklyReduction: "Suggested weekly reduction", remainingDays: (days: number) => `${days} days remaining`, liveProjection: "Live projection", unavailable: "Projection available when the month starts.", noMoneyMoved: "No money is moved. The projection follows Transactions and Budgets.", close: "Close", review: "Review adjustment", currentProjection: "Current projection", currentPace: "Current remaining pace", suggestedTarget: "Suggested recovery target", remainingTarget: "REMAINING SPEND TARGET", maxAdditionalSpend: "maximum additional spend to stay on plan", noAdditionalSpend: "No additional spending available under the current plan", reductionNeeded: "REDUCTION NEEDED", perWeek: "per week", beforeTarget: "Before → target", projectedRemaining: "Projected remaining spend", newTarget: "New remaining target", targetClose: "Target month close", targetOutcome: "Target outcome: back on the monthly plan", outcome: (total: string) => `If this target is followed, the projected close returns to the planned ${total}.`, planningOnly: "Planning only — this saves a MoneyPilot spending target. It does not move money or edit past transactions.", back: "Back", apply: "Apply adjustment" };
}
