"use client";

import { useCurrency } from "@/components/CurrencyProvider";

import Image from "next/image";
import { useMemo, useState } from "react";
import { DesktopScaleCanvas } from "@/components/DesktopScaleCanvas";
import { DeleteGoalModal } from "@/components/goals/DeleteGoalModal";
import { GoalModal } from "@/components/goals/GoalModal";
import { GoalSavingsPlanModal } from "@/components/goals/GoalSavingsPlanModal";
import { calculateGoal } from "@/components/goals/goal-calculations";
import { calculateGoalPlanImpact, isGoalContributionPlanStale } from "@/components/goals/goal-contribution-plan";
import { calculateGoalSavingsCapacity, getCurrentFinancialMonth } from "@/components/goals/goal-savings-capacity";
import type { Goal } from "@/components/goals/goal-model";
import { formatGoalTargetDate, selectPrimaryGoal } from "@/components/goals/goal-model";
import { useFinanceData } from "@/components/FinanceDataProvider";
import { useLanguage } from "@/components/LanguageProvider";
import { translations } from "@/i18n/translations";

const iconRoot = "/moneypilot/goals/icons";
const cardClass = "overflow-hidden rounded-[20px] border border-[#28313B] bg-[#080B0F]/20";

const metricSpecs = [
  { icon: "accent-primary.svg" }, { icon: "accent-contribution.svg" }, { icon: "accent-progress.svg", progress: true }, { icon: "accent-savings.svg" },
];
const actionIcons = ["insight-blue.svg", "insight-green.svg", "insight-teal.svg"];

export default function GoalsPage() {
  const { language } = useLanguage();
  const { formatMoney: money } = useCurrency();
  const { goals, setGoals, goalContributionPlans, setGoalContributionPlans, budgets, transactions, budgetAdjustments } = useFinanceData();
  const [selectedGoalId, setSelectedGoalId] = useState<string | null>(null);
  const [modal, setModal] = useState<{ mode: "create" } | { mode: "edit"; goalId: string } | null>(null);
  const [deleteGoalId, setDeleteGoalId] = useState<string | null>(null);
  const [planGoalId, setPlanGoalId] = useState<string | null>(null);
  const [feedback, setFeedback] = useState("");
  const t = translations[language].appGoals;
  const emptyCopy = language === "pt"
    ? { createFirst: "Crie sua primeira meta", chooseGoal: "Escolha para o que está economizando e o MoneyPilot calculará o aporte necessário.", noProgress: "Ainda não existe progresso de meta", noSavingsPlan: "Ainda não existe plano de economia", savingsPlan: "Plano de economia", unavailable: "Ainda não disponível", createForSavings: "Crie uma meta para calcular um plano de economia.", estimatedCost: "Custo estimado da meta", addTarget: "Adicione um valor-alvo para calcular o custo da meta.", target: "Valor-alvo", saved: "Guardado", remaining: "Restante", actionPlan: "Plano de ação", noActionPlan: "Ainda não existe plano de ação", createForActions: "Crie uma meta para gerar os próximos passos.", planUnavailable: "As sugestões por categoria ainda não estão disponíveis.", actionsUnavailable: "As próximas etapas ainda não estão disponíveis." }
    : language === "es"
      ? { createFirst: "Crea tu primer objetivo", chooseGoal: "Elige para qué estás ahorrando y MoneyPilot calculará la aportación necesaria.", noProgress: "Aún no hay progreso del objetivo", noSavingsPlan: "Aún no hay plan de ahorro", savingsPlan: "Plan de ahorro", unavailable: "Aún no disponible", createForSavings: "Crea un objetivo para calcular un plan de ahorro.", estimatedCost: "Coste estimado del objetivo", addTarget: "Añade un importe objetivo para calcular el coste.", target: "Importe objetivo", saved: "Ahorrado", remaining: "Restante", actionPlan: "Plan de acción", noActionPlan: "Aún no hay plan de acción", createForActions: "Crea un objetivo para generar los próximos pasos.", planUnavailable: "Las sugerencias por categoría aún no están disponibles.", actionsUnavailable: "Los próximos pasos aún no están disponibles." }
      : language === "de" ? { createFirst: "Erstelle dein erstes Ziel", chooseGoal: "Wähle, wofür du sparst, und MoneyPilot berechnet den nötigen Beitrag.", noProgress: "Noch kein Zielfortschritt", noSavingsPlan: "Noch kein Sparplan", savingsPlan: "Sparplan", unavailable: "Noch nicht verfügbar", createForSavings: "Erstelle ein Ziel, um einen Sparplan zu berechnen.", estimatedCost: "Geschätzte Zielkosten", addTarget: "Füge einen Zielbetrag hinzu, um die Kosten zu berechnen.", target: "Zielbetrag", saved: "Gespart", remaining: "Verbleibend", actionPlan: "Aktionsplan", noActionPlan: "Noch kein Aktionsplan", createForActions: "Erstelle ein Ziel, um die nächsten Schritte zu erhalten.", planUnavailable: "Vorschläge nach Kategorie sind noch nicht verfügbar.", actionsUnavailable: "Die nächsten Schritte sind noch nicht verfügbar." }
      : language === "fr" ? { createFirst: "Créez votre premier objectif", chooseGoal: "Choisissez ce pour quoi vous épargnez et MoneyPilot calculera le versement requis.", noProgress: "Aucune progression pour le moment", noSavingsPlan: "Aucun plan d’épargne", savingsPlan: "Plan d’épargne", unavailable: "Pas encore disponible", createForSavings: "Créez un objectif pour calculer un plan d’épargne.", estimatedCost: "Coût estimé de l’objectif", addTarget: "Ajoutez un montant cible pour calculer le coût.", target: "Montant cible", saved: "Épargné", remaining: "Restant", actionPlan: "Plan d’action", noActionPlan: "Aucun plan d’action", createForActions: "Créez un objectif pour générer les prochaines étapes.", planUnavailable: "Les suggestions par catégorie ne sont pas encore disponibles.", actionsUnavailable: "Les prochaines étapes ne sont pas encore disponibles." }
      : language === "nl" ? { createFirst: "Maak je eerste doel", chooseGoal: "Kies waarvoor je spaart en MoneyPilot berekent de benodigde inleg.", noProgress: "Nog geen voortgang", noSavingsPlan: "Nog geen spaarplan", savingsPlan: "Spaarplan", unavailable: "Nog niet beschikbaar", createForSavings: "Maak een doel om een spaarplan te berekenen.", estimatedCost: "Geschatte kosten van doel", addTarget: "Voeg een doelbedrag toe om de kosten te berekenen.", target: "Doelbedrag", saved: "Gespaard", remaining: "Resterend", actionPlan: "Actieplan", noActionPlan: "Nog geen actieplan", createForActions: "Maak een doel om de volgende stappen te ontvangen.", planUnavailable: "Suggesties per categorie zijn nog niet beschikbaar.", actionsUnavailable: "De volgende stappen zijn nog niet beschikbaar." }
      : language === "it" ? { createFirst: "Crea il tuo primo obiettivo", chooseGoal: "Scegli per cosa risparmiare e MoneyPilot calcolerà il contributo necessario.", noProgress: "Nessun progresso per ora", noSavingsPlan: "Nessun piano di risparmio", savingsPlan: "Piano di risparmio", unavailable: "Non ancora disponibile", createForSavings: "Crea un obiettivo per calcolare un piano di risparmio.", estimatedCost: "Costo stimato dell’obiettivo", addTarget: "Aggiungi un importo obiettivo per calcolare il costo.", target: "Importo obiettivo", saved: "Risparmiato", remaining: "Rimanente", actionPlan: "Piano d’azione", noActionPlan: "Nessun piano d’azione", createForActions: "Crea un obiettivo per generare i prossimi passi.", planUnavailable: "I suggerimenti per categoria non sono ancora disponibili.", actionsUnavailable: "I prossimi passi non sono ancora disponibili." }
      : { createFirst: "Create your first goal", chooseGoal: "Choose what you're saving for and MoneyPilot will calculate the contribution required.", noProgress: "No goal progress yet", noSavingsPlan: "No savings plan yet", savingsPlan: "Savings plan", unavailable: "Not available yet", createForSavings: "Create a goal to calculate a savings plan.", estimatedCost: "Estimated goal cost", addTarget: "Add a target amount to calculate your goal cost.", target: "Target amount", saved: "Saved", remaining: "Remaining", actionPlan: "Action plan", noActionPlan: "No action plan yet", createForActions: "Create a goal to generate the next steps.", planUnavailable: "Category-level suggestions are not available yet.", actionsUnavailable: "The next steps are not available yet." };
  const dynamic = {
    en: { month: "month", noGoals: "No goals yet", goal: "goal", complete: "complete", remaining: "remaining", room: "Current budget room", earlier: "months earlier", noCapacity: "No extra savings capacity found this month", completed: "Goal completed", passed: "Target date passed", due: "Amount needed to complete this month", until: "months until", planActive: "Savings plan active", review: "review needed", found: "MoneyPilot found", roomInBudget: "of conservative room in the current budget.", attention: "Budget needs attention before increasing your goal contribution.", adjustment: "An active budget adjustment is noted, but capacity still uses the current projection only.", headroom: "Projected budget headroom is", buffer: "50% is kept as a safety buffer.", directing: "Directing the safe capacity to this goal could reduce its estimate by", noImpact: "No additional goal impact is estimated from the current budget.", createTracking: "Create a goal to start tracking your progress.", of: "of", active: "Active", pastDue: "Past due", dueMonth: "Due this month", reviewPlan: "Review plan", apply: "Apply", noCapacityButton: "No capacity this month" },
    pt: { month: "mês", noGoals: "Ainda não há metas", goal: "meta", complete: "concluído", remaining: "restantes", room: "Margem atual do orçamento", earlier: "meses antes", noCapacity: "Nenhuma capacidade extra encontrada neste mês", completed: "Meta concluída", passed: "A data da meta passou", due: "Valor necessário para concluir este mês", until: "meses até", planActive: "Plano de economia ativo", review: "revisão necessária", found: "O MoneyPilot encontrou", roomInBudget: "de margem conservadora no orçamento atual.", attention: "O orçamento precisa de atenção antes de aumentar o aporte da meta.", adjustment: "Existe um ajuste ativo, mas a capacidade ainda usa somente a projeção atual.", headroom: "A margem projetada do orçamento é", buffer: "50% é mantido como reserva de segurança.", directing: "Direcionar a capacidade segura para esta meta pode reduzir a estimativa em", noImpact: "Nenhum impacto adicional na meta é estimado pelo orçamento atual.", createTracking: "Crie uma meta para começar a acompanhar seu progresso.", of: "de", active: "Ativa", pastDue: "Atrasada", dueMonth: "Vence este mês", reviewPlan: "Revisar plano", apply: "Aplicar", noCapacityButton: "Sem capacidade neste mês" },
    es: { month: "mes", noGoals: "Aún no hay objetivos", goal: "objetivo", complete: "completado", remaining: "restantes", room: "Margen actual del presupuesto", earlier: "meses antes", noCapacity: "No se encontró capacidad adicional este mes", completed: "Objetivo completado", passed: "La fecha del objetivo ha pasado", due: "Importe necesario para completar este mes", until: "meses hasta", planActive: "Plan de ahorro activo", review: "revisión necesaria", found: "MoneyPilot encontró", roomInBudget: "de margen conservador en el presupuesto actual.", attention: "El presupuesto requiere atención antes de aumentar la aportación.", adjustment: "Hay un ajuste activo, pero la capacidad solo usa la proyección actual.", headroom: "El margen presupuestario previsto es", buffer: "El 50% se mantiene como reserva de seguridad.", directing: "Destinar la capacidad segura a este objetivo puede reducir la estimación en", noImpact: "No se estima un impacto adicional con el presupuesto actual.", createTracking: "Crea un objetivo para empezar a seguir tu progreso.", of: "de", active: "Activo", pastDue: "Atrasado", dueMonth: "Vence este mes", reviewPlan: "Revisar plan", apply: "Aplicar", noCapacityButton: "Sin capacidad este mes" },
    de: { month: "Monat", noGoals: "Noch keine Ziele", goal: "Ziel", complete: "erreicht", remaining: "verbleibend", room: "Aktueller Budgetspielraum", earlier: "Monate früher", noCapacity: "Diesen Monat keine zusätzliche Sparkapazität", completed: "Ziel erreicht", passed: "Zieldatum überschritten", due: "Diesen Monat benötigter Betrag", until: "Monate bis", planActive: "Sparplan aktiv", review: "Prüfung erforderlich", found: "MoneyPilot hat", roomInBudget: "konservativen Spielraum im aktuellen Budget gefunden.", attention: "Das Budget braucht Aufmerksamkeit, bevor der Zielbeitrag erhöht wird.", adjustment: "Eine aktive Budgetanpassung ist vermerkt; die Kapazität basiert nur auf der aktuellen Prognose.", headroom: "Der prognostizierte Budgetspielraum beträgt", buffer: "50 % bleiben als Sicherheitspuffer.", directing: "Die sichere Kapazität kann die Schätzung für dieses Ziel reduzieren um", noImpact: "Aus dem aktuellen Budget ergibt sich keine zusätzliche Zielauswirkung.", createTracking: "Erstelle ein Ziel, um deinen Fortschritt zu verfolgen.", of: "von", active: "Aktiv", pastDue: "Überfällig", dueMonth: "Diesen Monat fällig", reviewPlan: "Plan prüfen", apply: "Anwenden", noCapacityButton: "Diesen Monat keine Kapazität" },
    fr: { month: "mois", noGoals: "Aucun objectif", goal: "objectif", complete: "réalisé", remaining: "restants", room: "Marge actuelle du budget", earlier: "mois plus tôt", noCapacity: "Aucune capacité supplémentaire ce mois-ci", completed: "Objectif atteint", passed: "Date cible dépassée", due: "Montant requis ce mois-ci", until: "mois avant", planActive: "Plan d’épargne actif", review: "révision nécessaire", found: "MoneyPilot a trouvé", roomInBudget: "de marge prudente dans le budget actuel.", attention: "Le budget nécessite votre attention avant d’augmenter le versement.", adjustment: "Un ajustement actif est enregistré, mais la capacité repose uniquement sur la prévision actuelle.", headroom: "La marge budgétaire prévue est de", buffer: "50 % sont conservés comme marge de sécurité.", directing: "Affecter la capacité sûre à cet objectif peut réduire l’estimation de", noImpact: "Aucun impact supplémentaire n’est estimé avec le budget actuel.", createTracking: "Créez un objectif pour commencer à suivre votre progression.", of: "sur", active: "Actif", pastDue: "En retard", dueMonth: "À réaliser ce mois-ci", reviewPlan: "Réviser le plan", apply: "Appliquer", noCapacityButton: "Aucune capacité ce mois-ci" },
    nl: { month: "maand", noGoals: "Nog geen doelen", goal: "doel", complete: "voltooid", remaining: "resterend", room: "Huidige budgetruimte", earlier: "maanden eerder", noCapacity: "Deze maand geen extra spaarruimte", completed: "Doel voltooid", passed: "Doeldatum verstreken", due: "Deze maand benodigd bedrag", until: "maanden tot", planActive: "Spaarplan actief", review: "controle nodig", found: "MoneyPilot vond", roomInBudget: "voorzichtige ruimte in het huidige budget.", attention: "Het budget vraagt aandacht voordat je de doelinleg verhoogt.", adjustment: "Er is een actieve budgetaanpassing, maar de ruimte gebruikt alleen de huidige verwachting.", headroom: "De verwachte budgetruimte is", buffer: "50% blijft als veiligheidsmarge.", directing: "De veilige ruimte kan de schatting voor dit doel verminderen met", noImpact: "Het huidige budget geeft geen extra effect op het doel.", createTracking: "Maak een doel om je voortgang te volgen.", of: "van", active: "Actief", pastDue: "Verlopen", dueMonth: "Deze maand verschuldigd", reviewPlan: "Plan bekijken", apply: "Toepassen", noCapacityButton: "Deze maand geen ruimte" },
    it: { month: "mese", noGoals: "Nessun obiettivo", goal: "obiettivo", complete: "completato", remaining: "rimanenti", room: "Margine attuale del budget", earlier: "mesi prima", noCapacity: "Nessuna capacità aggiuntiva questo mese", completed: "Obiettivo completato", passed: "Data obiettivo superata", due: "Importo necessario questo mese", until: "mesi fino a", planActive: "Piano di risparmio attivo", review: "revisione necessaria", found: "MoneyPilot ha trovato", roomInBudget: "di margine prudenziale nel budget attuale.", attention: "Il budget richiede attenzione prima di aumentare il contributo.", adjustment: "È presente una modifica attiva, ma la capacità usa solo la previsione attuale.", headroom: "Il margine previsto del budget è", buffer: "Il 50% viene mantenuto come riserva di sicurezza.", directing: "Destinare la capacità sicura può ridurre la stima di", noImpact: "Il budget attuale non produce un impatto aggiuntivo.", createTracking: "Crea un obiettivo per iniziare a seguire i progressi.", of: "su", active: "Attivo", pastDue: "Scaduto", dueMonth: "In scadenza questo mese", reviewPlan: "Rivedi piano", apply: "Applica", noCapacityButton: "Nessuna capacità questo mese" },
  }[language];
  const primaryGoal = selectPrimaryGoal(goals);
  const selectedGoal = goals.find((goal) => goal.id === selectedGoalId) ?? primaryGoal;
  const editedGoal = modal?.mode === "edit" ? goals.find((goal) => goal.id === modal.goalId) : undefined;
  const deleteGoal = goals.find((goal) => goal.id === deleteGoalId);
  const planGoal = goals.find((goal) => goal.id === planGoalId);
  const planCalculation = planGoal ? calculateGoal(planGoal) : null;
  const primaryCalculation = primaryGoal ? calculateGoal(primaryGoal) : null;
  const selectedCalculation = selectedGoal ? calculateGoal(selectedGoal) : null;
  const currentMonth = getCurrentFinancialMonth();
  const savingsCapacity = useMemo(() => calculateGoalSavingsCapacity({ budgets, transactions, month: currentMonth, adjustment: budgetAdjustments[currentMonth] }), [budgetAdjustments, budgets, currentMonth, transactions]);
  const selectedPlan = selectedGoal ? goalContributionPlans[selectedGoal.id] : undefined;
  const selectedPlanImpact = selectedPlan && selectedCalculation ? calculateGoalPlanImpact(selectedCalculation.remainingAmount, selectedPlan.baselineRequiredMonthlyContribution, selectedPlan.monthlyTarget) : null;
  const availableCapacity = primaryCalculation?.isCompleted ? 0 : savingsCapacity.safeMonthlyCapacity;
  const availableImpact = primaryCalculation && primaryCalculation.requiredMonthlyContribution !== null ? calculateGoalPlanImpact(primaryCalculation.remainingAmount, primaryCalculation.requiredMonthlyContribution, primaryCalculation.requiredMonthlyContribution + availableCapacity) : null;
  const percentage = (ratio: number) => `${new Intl.NumberFormat(language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-IE", { maximumFractionDigits: 1 }).format(ratio * 100)}%`;
  const contributionValue = (calculation: ReturnType<typeof calculateGoal> | null) => calculation?.requiredMonthlyContribution === null || calculation?.requiredMonthlyContribution === undefined ? "—" : `${money(calculation.requiredMonthlyContribution)} / ${dynamic.month}`;
  const contributionDetail = (calculation: ReturnType<typeof calculateGoal> | null, targetDate?: string) => !calculation || !targetDate ? emptyCopy.createFirst : calculation.isCompleted ? dynamic.completed : calculation.isPastDue ? dynamic.passed : calculation.isDueThisMonth ? dynamic.due : `${calculation.monthsRemaining} ${dynamic.until} ${formatGoalTargetDate(targetDate, language)}`;
  const goalSummaryMetrics = t.metrics.map((item, index) => ({
    ...item,
    ...metricSpecs[index],
    value: index === 0 ? primaryGoal?.name ?? dynamic.noGoals : index === 1 ? contributionValue(primaryCalculation) : index === 2 ? money(primaryGoal?.savedAmount ?? 0) : `${money(availableCapacity)} / ${dynamic.month}`,
    detail: index === 0 ? primaryGoal ? `${formatGoalTargetDate(primaryGoal.targetDate, language)} · ${primaryGoal.priority} ${dynamic.goal}` : emptyCopy.createFirst : index === 1 ? contributionDetail(primaryCalculation, primaryGoal?.targetDate) : index === 2 ? primaryCalculation ? `${percentage(primaryCalculation.progressRatio)} ${dynamic.complete} · ${money(primaryCalculation.remainingAmount)} ${dynamic.remaining}` : emptyCopy.noProgress : !primaryGoal ? emptyCopy.noSavingsPlan : availableCapacity > 0 ? `${dynamic.room} · ≈ ${new Intl.NumberFormat(language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-IE", { maximumFractionDigits: 1 }).format(availableImpact?.estimatedMonthsEarlier ?? 0)} ${dynamic.earlier}` : dynamic.noCapacity,
  }));
  const liveContributionCopy = selectedPlan && selectedPlanImpact ? `${dynamic.planActive} · ${money(selectedPlan.monthlyTarget)}/${dynamic.month} · ≈ ${new Intl.NumberFormat(language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-IE", { maximumFractionDigits: 1 }).format(selectedPlanImpact.estimatedMonthsEarlier)} ${dynamic.earlier}${selectedCalculation && isGoalContributionPlanStale(selectedPlan, selectedCalculation.requiredMonthlyContribution, savingsCapacity.safeMonthlyCapacity) ? ` · ${dynamic.review}` : ""}.` : savingsCapacity.canContribute ? `${dynamic.found} ${money(savingsCapacity.safeMonthlyCapacity)}/${dynamic.month} ${dynamic.roomInBudget}` : dynamic.attention;
  const capacityContextCopy = savingsCapacity.source === "active_adjustment" ? dynamic.adjustment : `${dynamic.headroom} ${money(savingsCapacity.rawCapacity)}; ${dynamic.buffer}`;
  const impactCopy = availableCapacity > 0 ? `${dynamic.directing} ≈ ${new Intl.NumberFormat(language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-IE", { maximumFractionDigits: 1 }).format(availableImpact?.estimatedMonthsEarlier ?? 0)} ${dynamic.earlier}.` : dynamic.noImpact;
  const nextBestActions = primaryGoal ? actionIcons.map((icon, index) => ({ text: [liveContributionCopy, capacityContextCopy, impactCopy][index], icon })) : [];

  function createGoal(values: Omit<Goal, "id">) {
    const goal = { ...values, id: crypto.randomUUID() };
    setGoals((current) => [...current, goal]);
    setSelectedGoalId(goal.id);
    setModal(null);
  }

  function editGoal(values: Omit<Goal, "id">) {
    if (!editedGoal) return;
    setGoals((current) => current.map((goal) => goal.id === editedGoal.id ? { ...values, id: goal.id } : goal));
    setModal(null);
  }

  function confirmDelete() {
    if (!deleteGoalId) return;
    setGoals((current) => current.filter((goal) => goal.id !== deleteGoalId));
    setGoalContributionPlans((current) => { const next = { ...current }; delete next[deleteGoalId]; return next; });
    if (selectedGoalId === deleteGoalId) setSelectedGoalId(null);
    setDeleteGoalId(null);
  }

  function applySavingsPlan() {
    if (!planGoal || !planCalculation || planCalculation.isCompleted || planCalculation.isPastDue || planCalculation.requiredMonthlyContribution === null || planCalculation.requiredMonthlyContribution <= 0 || savingsCapacity.safeMonthlyCapacity <= 0) return;
    const monthlyTarget = planCalculation.requiredMonthlyContribution + savingsCapacity.safeMonthlyCapacity;
    if (!Number.isFinite(monthlyTarget) || monthlyTarget <= 0) return;
    setGoalContributionPlans((current) => ({ ...current, [planGoal.id]: { goalId: planGoal.id, monthlyTarget, baselineRequiredMonthlyContribution: planCalculation.requiredMonthlyContribution as number, savingsBoost: savingsCapacity.safeMonthlyCapacity, createdAt: new Date().toISOString() } }));
    setFeedback(`Savings plan applied · ${money(monthlyTarget)}/month target`);
    setPlanGoalId(null);
  }
  return (
    <main className="min-h-screen overflow-hidden bg-[#080B0F] text-[#F5F7FA]">
      <DesktopScaleCanvas>
        <div className="relative h-[1024px] w-[1536px] overflow-hidden">
          <section className="absolute left-[231px] top-[107px] flex h-[810px] w-[1164px] items-center justify-center overflow-hidden rounded-[38px] border border-[#28313B]/16 bg-[#0D1117]/50 px-[32px] py-[16px] shadow-[0_22px_42px_rgba(0,0,0,0.45)] backdrop-blur-[20px]">
            <div className="flex h-[779.67px] w-[1098px] shrink-0 flex-col gap-[12px]">
              <div className="flex h-[36.75px] shrink-0 items-center gap-[18.375px]"><span className="h-[36.75px] w-[36.75px] shrink-0 overflow-hidden"><Image src="/moneypilot/moneypilot-logo.svg" alt="" width={180} height={40} priority className="h-[36.75px] w-auto max-w-none" /></span><span className="money-pilot-wordmark font-brand text-[21.44px] font-medium leading-[26.031px] tracking-[0.4288px]">MoneyPilot</span></div>

              <header className="flex h-[57.92px] shrink-0 items-center justify-between"><div className="flex h-[52px] w-[520px] flex-col justify-center gap-[4px]"><h1 className="text-[23.168px] font-semibold leading-none">{t.title}</h1><p className="text-[13.2px] text-[#9CA6B2]">{t.description}</p></div><div className="flex h-[52px] w-[220px] items-center justify-end gap-[16px]"><button type="button" onClick={() => setModal({ mode: "create" })} className="h-[38px] w-[132px] rounded-[19px] bg-[#3B82F6] text-[12.5px] font-semibold">{t.newGoal}</button><Image src="/moneypilot/dashboard-avatar.png" alt={t.userAvatar} width={52} height={52} className="size-[52.128px] rounded-full" /></div></header>

              <section aria-label={t.summaryAria} className="flex h-[115px] shrink-0 gap-[12px]">{goalSummaryMetrics.map((metric) => <article key={metric.label} className={`${cardClass} flex h-[115px] w-[265.5px] shrink-0 flex-col gap-[6px] p-[12px]`}><div className="flex h-[24px] items-center gap-[8px] text-[11.5px] font-medium text-[#9CA6B2]"><Image src={`${iconRoot}/${metric.icon}`} alt="" width={24} height={24} className="size-[24px]" />{metric.label}</div><strong className="truncate text-[20px] font-semibold leading-none">{metric.value}</strong><span className="truncate text-[10.5px] text-[#9CA6B2]">{metric.detail}</span>{metric.progress && <div className="h-[5px] w-[241.5px] rounded-[2.5px] bg-[#28313B]/90"><div className="h-[5px] rounded-[2.5px] bg-[#22C55E]" style={{ width: `${primaryCalculation?.progressPercent ?? 0}%` }} /></div>}</article>)}</section>

              <section className="flex h-[210px] shrink-0 gap-[12px]">
                <article className={`${cardClass} flex h-[210px] w-[677px] shrink-0 flex-col items-center justify-between p-[14px]`}>
                  <div className="flex h-[28px] w-[649px] items-center justify-between"><div className="flex items-center gap-[10px]"><h2 className="text-[16px] font-semibold">{t.yourGoal}</h2>{goals.length > 1 && <select aria-label="Select goal" value={selectedGoal?.id ?? ""} onChange={(event) => setSelectedGoalId(event.target.value)} className="h-[26px] max-w-[210px] rounded-[14px] border border-[#28313B] bg-[#1A2129]/78 px-[10px] text-[10.5px] text-[#9CA6B2]">{goals.map((goal) => <option key={goal.id} value={goal.id}>{goal.name}</option>)}</select>}</div>{selectedGoal && <button type="button" onClick={() => setModal({ mode: "edit", goalId: selectedGoal.id })} className="flex h-[26px] w-[116px] items-center justify-center gap-[5px] rounded-[14px] border border-[#28313B] bg-[#1A2129]/78 text-[10.5px] font-medium text-[#9CA6B2]">{t.editGoal}<Image src={`${iconRoot}/pencil-alt.svg`} alt="" width={19.33} height={19.33} className="size-[19.33px]" /></button>}</div>
                  {selectedGoal && selectedCalculation ? <><div className="flex h-[126px] w-[649px] items-center gap-[14px]"><Image src="/moneypilot/goal-italy-rome.png" alt={t.tripImageAlt} width={140} height={112} className="h-[112px] w-[140px] rounded-[14px] object-cover" /><div className="flex h-[126px] w-[495px] flex-col justify-center gap-[7px]"><h3 className="truncate text-[16px] font-semibold">{selectedGoal.name}</h3><div className="flex h-[26px] gap-[8px]"><span className="flex h-[26px] items-center rounded-[14px] border border-[#28313B] bg-[#1A2129]/78 px-[16px] text-[10.5px] font-medium capitalize text-[#9CA6B2]">{selectedGoal.priority}</span><span className="flex h-[26px] items-center rounded-[14px] border border-[#28313B] bg-[#1A2129]/78 px-[16px] text-[10.5px] font-medium text-[#9CA6B2]">{money(selectedGoal.targetAmount)}</span></div><div className="flex h-[16px] w-[440px] items-center justify-between text-[10.5px] font-medium text-[#9CA6B2]"><span>{t.goalProgress}</span><strong className="text-[#22C55E]">{percentage(selectedCalculation.progressRatio)}</strong></div><div className="h-[8px] w-[440px] rounded-[4px] bg-[#28313B]/90"><div className="h-[8px] rounded-[4px] bg-[#3B82F6]" style={{ width: `${selectedCalculation.progressPercent}%` }} /></div><div className="flex h-[18px] w-[440px] items-center justify-between text-[11px]"><strong>{money(selectedGoal.savedAmount)} {dynamic.of} {money(selectedGoal.targetAmount)}</strong><span className="text-[#9CA6B2]">{money(selectedCalculation.remainingAmount)} {dynamic.remaining} · {contributionValue(selectedCalculation)}</span></div></div></div><div className="flex h-[30px] w-[649px] items-center justify-between"><div className="flex h-[28px] w-[220px] items-start gap-[7px]"><Image src={`${iconRoot}/next-action.svg`} alt="" width={8} height={28} className="h-[28px] w-[8px] shrink-0" /><div className="flex flex-col gap-[2px]"><span className="text-[9.5px] leading-none text-[#9CA6B2]">{t.goalDate}</span><strong className="text-[11px] leading-none">{formatGoalTargetDate(selectedGoal.targetDate, language)}</strong></div></div><span className="flex h-[24px] w-[104px] items-center justify-center rounded-[14px] bg-[#3B82F6] text-[10.5px] font-semibold">{selectedCalculation.isCompleted ? dynamic.completed : selectedCalculation.isPastDue ? dynamic.pastDue : selectedCalculation.isDueThisMonth ? dynamic.dueMonth : dynamic.active}</span></div></> : <div className="flex h-[160px] w-[649px] flex-col items-center justify-center gap-[10px] text-center"><strong className="text-[16px]">{dynamic.noGoals}</strong><span className="text-[10.5px] text-[#9CA6B2]">{dynamic.createTracking}</span><button type="button" onClick={() => setModal({ mode: "create" })} className="h-[32px] rounded-[16px] bg-[#3B82F6] px-[20px] text-[11px] font-semibold">{t.newGoal}</button></div>}
                </article>

                <article className={`${cardClass} flex h-[210px] w-[409px] shrink-0 flex-col gap-[7px] p-[14px]`}><h2 className="flex h-[24px] items-center gap-[8px] text-[15.5px] font-semibold"><Image src={`${iconRoot}/action-cta.svg`} alt="" width={23} height={24} className="h-[24px] w-[23px]" />{t.nextBestAction}</h2>{primaryGoal ? <>{nextBestActions.map((item) => <div key={`${item.icon}-${item.text}`} className="flex h-[34px] w-[381px] items-center gap-[9px]"><Image src={`${iconRoot}/${item.icon}`} alt="" width={24} height={24} className="size-[24px]" /><p className="text-[10.2px] leading-[14px] text-[#9CA6B2]">{item.text}</p></div>)}<button type="button" disabled={!selectedGoal || !selectedCalculation || selectedCalculation.isCompleted || selectedCalculation.isPastDue || selectedCalculation.requiredMonthlyContribution === null || !savingsCapacity.canContribute} onClick={() => selectedGoal && setPlanGoalId(selectedGoal.id)} className="flex h-[30px] w-[381px] items-center justify-center gap-[6px] rounded-[10px] bg-[#3B82F6] text-[10.5px] font-semibold disabled:cursor-not-allowed disabled:opacity-45"><span className="size-[5px] rounded-full bg-white" />{selectedPlan ? dynamic.reviewPlan : savingsCapacity.canContribute ? `${dynamic.apply} ${money(savingsCapacity.safeMonthlyCapacity)}/${dynamic.month}` : dynamic.noCapacityButton}</button></> : <div className="flex flex-1 flex-col items-center justify-center gap-[12px] text-center"><strong className="text-[16px]">{emptyCopy.createFirst}</strong><p className="max-w-[330px] text-[10.2px] leading-[14px] text-[#9CA6B2]">{emptyCopy.chooseGoal}</p><button type="button" onClick={() => setModal({ mode: "create" })} className="h-[30px] rounded-[15px] bg-[#3B82F6] px-[24px] text-[10.5px] font-semibold">{t.newGoal}</button></div>}</article>
              </section>

              <section className="flex h-[222px] shrink-0 gap-[12px]">
                <article className={`${cardClass} flex h-[222px] w-[677px] shrink-0 flex-col p-[14px]`}><h2 className="h-[20px] text-[15.5px] font-semibold">{emptyCopy.savingsPlan}</h2><div className="flex flex-1 flex-col items-center justify-center gap-[10px] text-center"><strong className="text-[15px]">{emptyCopy.unavailable}</strong><p className="text-[10.5px] text-[#9CA6B2]">{primaryGoal ? emptyCopy.planUnavailable : emptyCopy.createForSavings}</p></div></article>

                <article className={`${cardClass} flex h-[222px] w-[409px] shrink-0 flex-col gap-[10px] p-[14px]`}><h2 className="h-[20px] text-[15px] font-semibold">{emptyCopy.estimatedCost}</h2>{selectedGoal && selectedCalculation ? <dl className="mt-[14px] grid gap-[10px] rounded-[12px] border border-[#28313B] bg-[#1A2129]/45 p-[14px] text-[10.5px]"><div className="flex justify-between"><dt className="text-[#9CA6B2]">{emptyCopy.target}</dt><dd className="font-semibold">{money(selectedGoal.targetAmount)}</dd></div><div className="flex justify-between"><dt className="text-[#9CA6B2]">{emptyCopy.saved}</dt><dd className="font-semibold">{money(selectedGoal.savedAmount)}</dd></div><div className="flex justify-between"><dt className="text-[#9CA6B2]">{emptyCopy.remaining}</dt><dd className="font-semibold">{money(selectedCalculation.remainingAmount)}</dd></div></dl> : <div className="flex flex-1 flex-col items-center justify-center gap-[10px] text-center"><strong className="text-[15px]">{emptyCopy.unavailable}</strong><p className="text-[10.5px] text-[#9CA6B2]">{emptyCopy.addTarget}</p></div>}</article>
              </section>

              <section className={`${cardClass} flex h-[78px] w-[1098px] shrink-0 items-center gap-[18px] p-[12px]`}><div className="flex h-[54px] w-[160px] shrink-0 flex-col justify-center gap-[4px]"><h2 className="text-[14.5px] font-semibold">{emptyCopy.actionPlan}</h2><p className="text-[9.5px] text-[#9CA6B2]">{primaryGoal ? emptyCopy.unavailable : emptyCopy.noActionPlan}</p></div><p className="flex-1 text-[10.5px] text-[#9CA6B2]">{primaryGoal ? emptyCopy.actionsUnavailable : emptyCopy.createForActions}</p>{!primaryGoal && <button type="button" onClick={() => setModal({ mode: "create" })} className="h-[30px] rounded-[15px] bg-[#3B82F6] px-[24px] text-[10.5px] font-semibold">{t.newGoal}</button>}</section>
            </div>
          </section>
        </div>
      </DesktopScaleCanvas>
      {modal?.mode === "create" && <GoalModal mode="create" goals={goals} onClose={() => setModal(null)} onSubmit={createGoal} />}
      {modal?.mode === "edit" && editedGoal && <GoalModal mode="edit" goal={editedGoal} goals={goals} onClose={() => setModal(null)} onSubmit={editGoal} onRequestDelete={() => { setDeleteGoalId(editedGoal.id); setModal(null); }} />}
      {deleteGoal && <DeleteGoalModal goal={deleteGoal} language={language} onClose={() => setDeleteGoalId(null)} onConfirm={confirmDelete} />}
      {planGoal && planCalculation && <GoalSavingsPlanModal goal={planGoal} calculation={planCalculation} savingsBoost={savingsCapacity.safeMonthlyCapacity} existingPlan={goalContributionPlans[planGoal.id]} language={language} onClose={() => setPlanGoalId(null)} onApply={applySavingsPlan} />}
      {feedback && <div role="status" className="fixed bottom-[28px] left-1/2 z-[70] -translate-x-1/2 rounded-[18px] border border-[#22C55E]/30 bg-[var(--background-elevated)] px-[22px] py-[10px] text-[10px] font-semibold text-[#22C55E] shadow-lg">{feedback}</div>}
    </main>
  );
}
