"use client";

import Image from "next/image";
import { useState } from "react";
import { DesktopScaleCanvas } from "@/components/DesktopScaleCanvas";
import { useLanguage } from "@/components/LanguageProvider";
import { InvestmentPerformanceChart, type InvestmentRange } from "@/components/investments/InvestmentPerformanceChart";
import { PortfolioAllocationChart } from "@/components/investments/PortfolioAllocationChart";

const iconRoot = "/moneypilot/investments/icons";
const card = "overflow-hidden rounded-[18px] border border-[#28313B] bg-[#080B0F]/20 shadow-[0_6px_14px_rgba(0,0,0,0.2)]";
const summaryStyles = [{ icon: "wallet-outline", color: "#3B82F6" }, { icon: "trending-up-outline", color: "#22C55E" }, { icon: "pulse-outline", color: "#22C55E" }, { icon: "shield-checkmark-outline", color: "#F59E0B" }];

const copy = {
  en: { title: "Investments", description: "Understand risk, protect your goals and decide your next contribution with more context.", filters: ["All", "Stocks", "Crypto"], summary: "Investment summary", metrics: [{ label: "Invested assets", value: "—", detail: "No investment data yet" }, { label: "Total return", value: "—", detail: "Not calculated yet" }, { label: "Available cash", value: "—", detail: "No investment cash data" }, { label: "Portfolio risk", value: "Not available", detail: "Add investment data to assess portfolio risk." }], performance: "Portfolio performance", noPerformance: "No performance data yet", performanceHelp: "Performance will appear when investment data is available.", allocation: "Portfolio allocation", noAllocation: "No allocation data yet", allocationHelp: "Add assets to see your portfolio allocation.", assets: "Your assets", noAssets: "No investment assets yet", assetsHelp: "Add investment data to build your portfolio.", contribution: "Before the next contribution", noContribution: "No contribution review yet", contributionHelp: "Investment guidance will appear when portfolio data is available.", criteria: "View criteria →", insight: "Investment insight", noInsights: "No insights yet", insightsHelp: "Add investment data to start analysis.", decisions: "Priority decisions", noDecisions: "No decisions yet", decisionsHelp: "Decisions will appear when MoneyPilot has enough investment data.", avatar: "User avatar" },
  pt: { title: "Investimentos", description: "Entenda o risco, proteja suas metas e decida o próximo aporte com mais contexto.", filters: ["Todos", "Ações", "Cripto"], summary: "Resumo dos investimentos", metrics: [{ label: "Patrimônio investido", value: "—", detail: "Ainda não há dados de investimentos" }, { label: "Resultado total", value: "—", detail: "Ainda não calculado" }, { label: "Caixa disponível", value: "—", detail: "Ainda não há dados de caixa de investimentos" }, { label: "Risco da carteira", value: "Indisponível", detail: "Adicione dados de investimentos para avaliar o risco da carteira." }], performance: "Evolução da carteira", noPerformance: "Ainda não há dados de desempenho", performanceHelp: "O desempenho aparecerá quando houver dados de investimentos.", allocation: "Alocação da carteira", noAllocation: "Ainda não há dados de alocação", allocationHelp: "Adicione ativos para ver a alocação da carteira.", assets: "Seus ativos", noAssets: "Ainda não há ativos de investimento", assetsHelp: "Adicione dados de investimentos para montar sua carteira.", contribution: "Antes do próximo aporte", noContribution: "Ainda não há revisão de aporte", contributionHelp: "As orientações aparecerão quando houver dados da carteira.", criteria: "Ver critérios →", insight: "Insight de investimentos", noInsights: "Ainda não há insights", insightsHelp: "Adicione dados de investimentos para iniciar a análise.", decisions: "Decisões prioritárias", noDecisions: "Ainda não há decisões", decisionsHelp: "As decisões aparecerão quando o MoneyPilot tiver dados de investimentos suficientes.", avatar: "Avatar do usuário" },
  es: { title: "Inversiones", description: "Comprende el riesgo, protege tus objetivos y decide la próxima aportación con más contexto.", filters: ["Todos", "Acciones", "Cripto"], summary: "Resumen de inversiones", metrics: [{ label: "Patrimonio invertido", value: "—", detail: "Aún no hay datos de inversiones" }, { label: "Resultado total", value: "—", detail: "Aún no calculado" }, { label: "Efectivo disponible", value: "—", detail: "Aún no hay datos de efectivo de inversiones" }, { label: "Riesgo de la cartera", value: "No disponible", detail: "Añade datos de inversiones para evaluar el riesgo de la cartera." }], performance: "Evolución de la cartera", noPerformance: "Aún no hay datos de rendimiento", performanceHelp: "El rendimiento aparecerá cuando haya datos de inversiones.", allocation: "Distribución de la cartera", noAllocation: "Aún no hay datos de distribución", allocationHelp: "Añade activos para ver la distribución de la cartera.", assets: "Tus activos", noAssets: "Aún no hay activos de inversión", assetsHelp: "Añade datos de inversiones para crear tu cartera.", contribution: "Antes de la próxima aportación", noContribution: "Aún no hay revisión de aportación", contributionHelp: "La orientación aparecerá cuando haya datos de la cartera.", criteria: "Ver criterios →", insight: "Insight de inversiones", noInsights: "Aún no hay insights", insightsHelp: "Añade datos de inversiones para iniciar el análisis.", decisions: "Decisiones prioritarias", noDecisions: "Aún no hay decisiones", decisionsHelp: "Las decisiones aparecerán cuando MoneyPilot tenga suficientes datos de inversiones.", avatar: "Avatar del usuario" },
};
const extendedCopy = {
  ...copy,
  de: { ...copy.en, title: "Investitionen", description: "Behalte Risiken, Ziele und künftige Einzahlungen im Blick.", filters: ["Alle", "Aktien", "Krypto"], summary: "Investitionsübersicht", metrics: [{ label: "Investiertes Vermögen", value: "—", detail: "Noch keine Investitionsdaten" }, { label: "Gesamtrendite", value: "—", detail: "Noch nicht berechnet" }, { label: "Verfügbares Guthaben", value: "—", detail: "Noch keine Guthabendaten" }, { label: "Portfoliorisiko", value: "Nicht verfügbar", detail: "Füge Investitionsdaten hinzu, um das Risiko zu bewerten." }], performance: "Portfolioentwicklung", noPerformance: "Noch keine Performancedaten", performanceHelp: "Die Entwicklung erscheint, sobald Investitionsdaten verfügbar sind.", allocation: "Portfolioaufteilung", noAllocation: "Noch keine Aufteilungsdaten", allocationHelp: "Füge Anlagen hinzu, um die Portfolioaufteilung zu sehen.", assets: "Deine Anlagen", noAssets: "Noch keine Anlagen", assetsHelp: "Füge Investitionsdaten hinzu, um dein Portfolio aufzubauen.", contribution: "Vor der nächsten Einzahlung", noContribution: "Noch keine Prüfung verfügbar", contributionHelp: "Hinweise erscheinen, sobald Portfoliodaten verfügbar sind.", criteria: "Kriterien anzeigen →", insight: "Investitionseinblick", noInsights: "Noch keine Einblicke", insightsHelp: "Füge Investitionsdaten hinzu, um die Analyse zu starten.", decisions: "Wichtige Entscheidungen", noDecisions: "Noch keine Entscheidungen", decisionsHelp: "Entscheidungen erscheinen bei ausreichenden Investitionsdaten.", avatar: "Benutzeravatar" },
  fr: { ...copy.en, title: "Investissements", description: "Comprenez le risque, protégez vos objectifs et préparez votre prochain versement.", filters: ["Tous", "Actions", "Crypto"], summary: "Résumé des investissements", metrics: [{ label: "Actifs investis", value: "—", detail: "Aucune donnée d’investissement" }, { label: "Rendement total", value: "—", detail: "Pas encore calculé" }, { label: "Liquidités disponibles", value: "—", detail: "Aucune donnée de liquidités" }, { label: "Risque du portefeuille", value: "Indisponible", detail: "Ajoutez des données pour évaluer le risque du portefeuille." }], performance: "Performance du portefeuille", noPerformance: "Aucune donnée de performance", performanceHelp: "La performance apparaîtra lorsque des données seront disponibles.", allocation: "Répartition du portefeuille", noAllocation: "Aucune donnée de répartition", allocationHelp: "Ajoutez des actifs pour voir la répartition du portefeuille.", assets: "Vos actifs", noAssets: "Aucun actif d’investissement", assetsHelp: "Ajoutez des données pour constituer votre portefeuille.", contribution: "Avant le prochain versement", noContribution: "Aucune analyse de versement", contributionHelp: "Les conseils apparaîtront lorsque les données seront disponibles.", criteria: "Voir les critères →", insight: "Analyse des investissements", noInsights: "Aucune analyse", insightsHelp: "Ajoutez des données d’investissement pour commencer l’analyse.", decisions: "Décisions prioritaires", noDecisions: "Aucune décision", decisionsHelp: "Les décisions apparaîtront avec suffisamment de données.", avatar: "Avatar utilisateur" },
  nl: { ...copy.en, title: "Beleggingen", description: "Begrijp risico’s, bescherm je doelen en bereid je volgende inleg voor.", filters: ["Alle", "Aandelen", "Crypto"], summary: "Beleggingsoverzicht", metrics: [{ label: "Belegd vermogen", value: "—", detail: "Nog geen beleggingsgegevens" }, { label: "Totaalrendement", value: "—", detail: "Nog niet berekend" }, { label: "Beschikbaar saldo", value: "—", detail: "Nog geen beleggingssaldo" }, { label: "Portefeuillerisico", value: "Niet beschikbaar", detail: "Voeg beleggingsgegevens toe om het risico te beoordelen." }], performance: "Portefeuilleprestaties", noPerformance: "Nog geen prestatiegegevens", performanceHelp: "Prestaties verschijnen zodra beleggingsgegevens beschikbaar zijn.", allocation: "Portefeuilleverdeling", noAllocation: "Nog geen verdelingsgegevens", allocationHelp: "Voeg beleggingen toe om de verdeling te zien.", assets: "Je beleggingen", noAssets: "Nog geen beleggingen", assetsHelp: "Voeg beleggingsgegevens toe om je portefeuille op te bouwen.", contribution: "Voor de volgende inleg", noContribution: "Nog geen beoordeling", contributionHelp: "Advies verschijnt zodra portefeuillegegevens beschikbaar zijn.", criteria: "Criteria bekijken →", insight: "Beleggingsinzicht", noInsights: "Nog geen inzichten", insightsHelp: "Voeg beleggingsgegevens toe om de analyse te starten.", decisions: "Belangrijkste beslissingen", noDecisions: "Nog geen beslissingen", decisionsHelp: "Beslissingen verschijnen bij voldoende beleggingsgegevens.", avatar: "Gebruikersavatar" },
  it: { ...copy.en, title: "Investimenti", description: "Comprendi il rischio, proteggi i tuoi obiettivi e prepara il prossimo versamento.", filters: ["Tutti", "Azioni", "Cripto"], summary: "Riepilogo investimenti", metrics: [{ label: "Patrimonio investito", value: "—", detail: "Nessun dato sugli investimenti" }, { label: "Rendimento totale", value: "—", detail: "Non ancora calcolato" }, { label: "Liquidità disponibile", value: "—", detail: "Nessun dato sulla liquidità" }, { label: "Rischio del portafoglio", value: "Non disponibile", detail: "Aggiungi dati per valutare il rischio del portafoglio." }], performance: "Andamento del portafoglio", noPerformance: "Nessun dato sull’andamento", performanceHelp: "L’andamento apparirà quando saranno disponibili dati.", allocation: "Allocazione del portafoglio", noAllocation: "Nessun dato sull’allocazione", allocationHelp: "Aggiungi asset per vedere l’allocazione del portafoglio.", assets: "I tuoi asset", noAssets: "Nessun asset di investimento", assetsHelp: "Aggiungi dati per creare il tuo portafoglio.", contribution: "Prima del prossimo versamento", noContribution: "Nessuna revisione disponibile", contributionHelp: "Le indicazioni appariranno quando saranno disponibili dati.", criteria: "Vedi criteri →", insight: "Analisi degli investimenti", noInsights: "Nessuna analisi", insightsHelp: "Aggiungi dati sugli investimenti per iniziare l’analisi.", decisions: "Decisioni prioritarie", noDecisions: "Nessuna decisione", decisionsHelp: "Le decisioni appariranno con dati sufficienti.", avatar: "Avatar utente" },
};

function Glyph({ name, color }: { name: string; color: string }) { return <span aria-hidden className="block size-[18px] shrink-0" style={{ backgroundColor: color, WebkitMask: `url(${iconRoot}/${name}.svg) center/contain no-repeat`, mask: `url(${iconRoot}/${name}.svg) center/contain no-repeat` }} />; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="flex h-full flex-col items-center justify-center px-[16px] text-center"><strong className="text-[10px]">{title}</strong><p className="mt-[5px] text-[8.5px] text-[#9CA6B2]">{detail}</p></div>; }

export default function InvestmentsPage() {
  const { language } = useLanguage();
  const t = extendedCopy[language];
  const [filter, setFilter] = useState(0);
  const ranges: InvestmentRange[] = ["7D", "1M", "3M", "1A"];
  return <main className="min-h-screen bg-[#080B0F] font-[Inter] text-[#F5F7FA]"><DesktopScaleCanvas><div className="relative h-[1024px] w-[1536px] overflow-hidden"><section className="absolute left-[231px] top-[107px] h-[810px] w-[1164px] overflow-hidden rounded-[38px] border border-[#28313B]/16 bg-[#0D1117]/50 px-[32px] py-[16px] shadow-[0_22px_42px_rgba(0,0,0,0.45)] backdrop-blur-[20px]"><div className="flex h-[767.623px] w-[1098px] flex-col gap-[12px]">
    <div className="flex h-[36.75px] shrink-0 items-center gap-[18.375px]"><span className="h-[36.75px] w-[36.75px] shrink-0 overflow-hidden"><Image src="/moneypilot/moneypilot-logo.svg" alt="" width={180} height={40} priority className="h-[36.75px] w-auto max-w-none" /></span><span className="money-pilot-wordmark font-brand text-[21.44px] font-medium tracking-[0.4288px]">MoneyPilot</span></div>
    <header className="flex h-[57.92px] shrink-0 items-center justify-between"><div className="flex h-[52px] w-[610px] flex-col justify-center gap-[4px]"><h1 className="text-[23.168px] font-semibold leading-none">{t.title}</h1><p className="text-[13.2px] text-[#9CA6B2]">{t.description}</p></div><div className="flex h-[52px] items-center gap-[16px]"><div className="flex h-[46px] w-[252px] items-center justify-center rounded-[23px] border border-[#28313B] bg-[#080B0F]/34 p-[4px]">{t.filters.map((item, index) => <button key={item} type="button" onClick={() => setFilter(index)} className={`h-[38px] w-[80px] rounded-[19px] text-[10.5px] font-medium ${filter === index ? "bg-[#3B82F6] text-[#F5F7FA]" : "text-[#9CA6B2]"}`}>{item}</button>)}</div><Image src="/moneypilot/dashboard-avatar.png" alt={t.avatar} width={52} height={52} className="size-[52px] rounded-full" /></div></header>
    <section aria-label={t.summary} className="flex h-[100px] shrink-0 gap-[12px]">{t.metrics.map((metric, index) => <article key={metric.label} className={`${card} flex h-[100px] w-[265.5px] shrink-0 flex-col gap-[6px] px-[12px] py-[10px]`}><div className="flex h-[30px] items-center gap-[8px]"><span className="flex size-[30px] items-center justify-center rounded-[9px] border" style={{ borderColor: summaryStyles[index].color, backgroundColor: `${summaryStyles[index].color}24` }}><Glyph name={summaryStyles[index].icon} color={summaryStyles[index].color} /></span><h2 className="text-[11px] font-semibold">{metric.label}</h2></div><strong className="text-[18px] font-semibold leading-none">{metric.value}</strong><p className="truncate text-[9px] text-[#9CA6B2]">{metric.detail}</p></article>)}</section>
    <section className="flex h-[185px] shrink-0 gap-[12px]"><article className={`${card} h-[185px] w-[677px] shrink-0 px-[12px] py-[10px]`}><div className="flex h-[24px] items-center justify-between"><h2 className="text-[14px] font-semibold">{t.performance}</h2><div className="flex gap-[4px]">{ranges.map((item) => <button key={item} type="button" disabled className={`h-[24px] rounded-[12px] border border-[#28313B] bg-[#080B0F]/24 text-[8px] text-[#64707D] disabled:cursor-not-allowed ${item === "1A" ? "w-[48px]" : "w-[40px]"}`}>{item}</button>)}</div></div><InvestmentPerformanceChart title={t.noPerformance} detail={t.performanceHelp} /></article><article className={`${card} h-[185px] w-[409px] px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{t.allocation}</h2><PortfolioAllocationChart title={t.noAllocation} detail={t.allocationHelp} /></article></section>
    <section className="flex h-[185px] shrink-0 gap-[12px]"><article className={`${card} h-[185px] w-[677px] px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{t.assets}</h2><div className="h-[145px]"><Empty title={t.noAssets} detail={t.assetsHelp} /></div></article><article className={`${card} h-[185px] w-[409px] px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{t.contribution}</h2><div className="h-[125px]"><Empty title={t.noContribution} detail={t.contributionHelp} /></div><button type="button" disabled className="flex h-[18px] w-full cursor-not-allowed items-center justify-end text-[8.5px] font-semibold text-[#64707D]">{t.criteria}</button></article></section>
    <section className="flex h-[143px] shrink-0 gap-[12px]"><article className={`${card} h-[143px] w-[409px] px-[12px] py-[10px]`}><h2 className="flex h-[24px] items-center gap-[7px] text-[14px] font-semibold"><Glyph name="sparkles-outline" color="#3B82F6" />{t.insight}</h2><div className="h-[99px]"><Empty title={t.noInsights} detail={t.insightsHelp} /></div></article><article className={`${card} h-[143px] w-[677px] px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{t.decisions}</h2><div className="h-[103px]"><Empty title={t.noDecisions} detail={t.decisionsHelp} /></div></article></section>
  </div></section></div></DesktopScaleCanvas></main>;
}
