"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { type Language, useLanguage } from "../LanguageProvider";

const skeleton = "animate-pulse rounded-[6px] bg-[color-mix(in_srgb,var(--text-secondary)_12%,transparent)]";

const systemCopy: Record<Language, {
  loading: [string, string, string, string];
  empty: [string, string, string, string, string, string, string];
  steps: [string, string][];
  error: [string, string, string, string, string, string, string, string];
  help: [string, string][];
}> = {
  en: { loading: ["Loading your financial overview", "MoneyPilot is preparing your latest transactions, budgets and goals.", "SYNCING", "Your data stays in this session while MoneyPilot calculates the current view."], empty: ["Build your financial overview with real data","Add transactions manually or import a CSV. MoneyPilot uses your data to calculate income, expenses and spending patterns.","Add transaction","Import CSV","Why start with CSV?","CSV import is available now. The complete PDF import flow is not available yet.","Start with a manual transaction or import a CSV."], steps: [["No bank connection required","You never need to share your banking login."],["A clearer starting point","Import recent CSV transactions to build your financial overview."],["You stay in control","Review transactions before they are imported."]], error: ["ERROR", "We couldn’t load your financial overview", "Your data is safe. MoneyPilot couldn’t complete this request right now. Try again, or return to the previous screen.", "Try again", "Go back", "If the problem continues", "YOUR DATA IS SAFE", "Retrying only reloads this view. It does not create, delete, or move financial data."], help: [["Check your connection", "Make sure your internet connection is available."], ["Try once more", "Retry the action. Your saved data will not be duplicated."], ["Get help", "Open Support if the same error keeps appearing."]] },
  pt: { loading: ["A carregar a sua visão financeira", "O MoneyPilot está a preparar as suas transações, orçamentos e objetivos mais recentes.", "A SINCRONIZAR", "Os seus dados permanecem nesta sessão enquanto o MoneyPilot calcula a vista atual."], empty: ["Construa sua visão financeira com dados reais","Adicione transações manualmente ou importe um CSV. O MoneyPilot usa seus dados para calcular receitas, despesas e padrões de gastos.","Adicionar transação","Importar CSV","Por que começar com CSV?","A importação CSV já está disponível. O fluxo completo de importação PDF ainda não está disponível.","Comece com uma transação manual ou importe um CSV."], steps: [["Nenhuma conexão bancária necessária","Você não precisa compartilhar suas credenciais bancárias."],["Um ponto de partida mais claro","Importe transações recentes em CSV para construir sua visão financeira."],["Você está no controle","Revise as transações antes da importação."]], error: ["ERRO", "Não foi possível carregar a sua visão financeira", "Os seus dados estão seguros. O MoneyPilot não conseguiu concluir este pedido agora. Tente novamente ou volte ao ecrã anterior.", "Tentar novamente", "Voltar", "Se o problema continuar", "OS SEUS DADOS ESTÃO SEGUROS", "Tentar novamente apenas recarrega esta vista. Não cria, elimina nem move dados financeiros."], help: [["Verifique a ligação", "Certifique-se de que a ligação à internet está disponível."], ["Tente mais uma vez", "Repita a ação. Os dados guardados não serão duplicados."], ["Obtenha ajuda", "Abra o Suporte se o mesmo erro continuar a aparecer."]] },
  es: { loading: ["Cargando tu resumen financiero", "MoneyPilot está preparando tus transacciones, presupuestos y objetivos más recientes.", "SINCRONIZANDO", "Tus datos permanecen en esta sesión mientras MoneyPilot calcula la vista actual."], empty: ["Construye tu resumen financiero con datos reales","Añade transacciones manualmente o importa un CSV. MoneyPilot usa tus datos para calcular ingresos, gastos y patrones de consumo.","Añadir transacción","Importar CSV","¿Por qué empezar con CSV?","La importación CSV está disponible. El flujo completo de importación PDF aún no está disponible.","Empieza con una transacción manual o importa un CSV."], steps: [["Sin conexión bancaria","No necesitas compartir tus credenciales bancarias."],["Un punto de partida más claro","Importa transacciones CSV recientes para crear tu resumen financiero."],["Tú tienes el control","Revisa las transacciones antes de importarlas."]], error: ["ERROR", "No pudimos cargar tu resumen financiero", "Tus datos están seguros. MoneyPilot no pudo completar esta solicitud ahora. Inténtalo de nuevo o vuelve a la pantalla anterior.", "Intentar de nuevo", "Volver", "Si el problema continúa", "TUS DATOS ESTÁN SEGUROS", "Reintentar solo recarga esta vista. No crea, elimina ni mueve datos financieros."], help: [["Comprueba tu conexión", "Asegúrate de que tu conexión a internet está disponible."], ["Inténtalo otra vez", "Repite la acción. Tus datos guardados no se duplicarán."], ["Obtén ayuda", "Abre Soporte si el mismo error sigue apareciendo."]] },
  de: { loading: ["Ihre Finanzübersicht wird geladen", "MoneyPilot bereitet Ihre neuesten Transaktionen, Budgets und Ziele vor.", "SYNCHRONISIERUNG", "Ihre Daten bleiben in dieser Sitzung, während MoneyPilot die aktuelle Ansicht berechnet."], empty: ["Erstellen Sie Ihre Finanzübersicht mit echten Daten","Fügen Sie Transaktionen manuell hinzu oder importieren Sie CSV. MoneyPilot berechnet Einnahmen, Ausgaben und Ausgabenmuster aus Ihren Daten.","Transaktion hinzufügen","CSV importieren","Warum mit CSV beginnen?","CSV-Import ist verfügbar. Der vollständige PDF-Import ist noch nicht verfügbar.","Beginnen Sie mit einer manuellen Transaktion oder einer CSV-Datei."], steps: [["Keine Bankverbindung erforderlich","Sie müssen keine Bankzugangsdaten teilen."],["Ein klarerer Ausgangspunkt","Importieren Sie aktuelle CSV-Transaktionen für Ihre Finanzübersicht."],["Sie behalten die Kontrolle","Prüfen Sie die Transaktionen vor dem Import."]], error: ["FEHLER", "Ihre Finanzübersicht konnte nicht geladen werden", "Ihre Daten sind sicher. MoneyPilot konnte diese Anfrage gerade nicht abschließen. Versuchen Sie es erneut oder kehren Sie zum vorherigen Bildschirm zurück.", "Erneut versuchen", "Zurück", "Falls das Problem weiterhin besteht", "IHRE DATEN SIND SICHER", "Ein erneuter Versuch lädt nur diese Ansicht neu. Finanzdaten werden weder erstellt noch gelöscht oder verschoben."], help: [["Verbindung prüfen", "Stellen Sie sicher, dass Ihre Internetverbindung verfügbar ist."], ["Erneut versuchen", "Wiederholen Sie die Aktion. Ihre gespeicherten Daten werden nicht dupliziert."], ["Hilfe erhalten", "Öffnen Sie den Support, wenn derselbe Fehler erneut auftritt."]] },
  fr: { loading: ["Chargement de votre vue financière", "MoneyPilot prépare vos dernières transactions, vos budgets et vos objectifs.", "SYNCHRONISATION", "Vos données restent dans cette session pendant que MoneyPilot calcule la vue actuelle."], empty: ["Créez votre vue financière avec des données réelles","Ajoutez des transactions manuellement ou importez un CSV. MoneyPilot utilise vos données pour calculer revenus, dépenses et habitudes.","Ajouter une transaction","Importer un CSV","Pourquoi commencer avec CSV ?","L’import CSV est disponible. Le parcours complet d’import PDF n’est pas encore disponible.","Commencez par une transaction manuelle ou importez un CSV."], steps: [["Aucune connexion bancaire requise","Vous ne partagez jamais vos identifiants bancaires."],["Un point de départ plus clair","Importez des transactions CSV récentes pour créer votre vue financière."],["Vous gardez le contrôle","Vérifiez les transactions avant de les importer."]], error: ["ERREUR", "Impossible de charger votre vue financière", "Vos données sont en sécurité. MoneyPilot n’a pas pu traiter cette demande pour le moment. Réessayez ou revenez à l’écran précédent.", "Réessayer", "Retour", "Si le problème persiste", "VOS DONNÉES SONT EN SÉCURITÉ", "Réessayer recharge uniquement cette vue. Aucune donnée financière n’est créée, supprimée ou déplacée."], help: [["Vérifiez votre connexion", "Assurez-vous que votre connexion Internet est disponible."], ["Réessayez", "Relancez l’action. Vos données enregistrées ne seront pas dupliquées."], ["Obtenir de l’aide", "Ouvrez l’assistance si la même erreur persiste."]] },
  nl: { loading: ["Je financiële overzicht wordt geladen", "MoneyPilot bereidt je nieuwste transacties, budgetten en doelen voor.", "SYNCHRONISEREN", "Je gegevens blijven in deze sessie terwijl MoneyPilot de huidige weergave berekent."], empty: ["Bouw je financiële overzicht met echte gegevens","Voeg handmatig transacties toe of importeer een CSV. MoneyPilot gebruikt jouw gegevens om inkomsten, uitgaven en bestedingspatronen te berekenen.","Transactie toevoegen","CSV importeren","Waarom beginnen met CSV?","CSV-import is beschikbaar. De volledige PDF-import is nog niet beschikbaar.","Begin met een handmatige transactie of importeer een CSV."], steps: [["Geen bankverbinding nodig","Je hoeft geen bankinloggegevens te delen."],["Een duidelijker startpunt","Importeer recente CSV-transacties voor je financiële overzicht."],["Jij houdt de controle","Controleer transacties voordat je ze importeert."]], error: ["FOUT", "We konden je financiële overzicht niet laden", "Je gegevens zijn veilig. MoneyPilot kon dit verzoek nu niet voltooien. Probeer het opnieuw of ga terug naar het vorige scherm.", "Opnieuw proberen", "Terug", "Als het probleem aanhoudt", "JE GEGEVENS ZIJN VEILIG", "Opnieuw proberen herlaadt alleen deze weergave. Financiële gegevens worden niet aangemaakt, verwijderd of verplaatst."], help: [["Controleer je verbinding", "Controleer of je internetverbinding beschikbaar is."], ["Probeer het nogmaals", "Herhaal de actie. Je opgeslagen gegevens worden niet gedupliceerd."], ["Hulp krijgen", "Open Ondersteuning als dezelfde fout blijft verschijnen."]] },
  it: { loading: ["Caricamento della panoramica finanziaria", "MoneyPilot sta preparando le transazioni, i budget e gli obiettivi più recenti.", "SINCRONIZZAZIONE", "I tuoi dati restano in questa sessione mentre MoneyPilot calcola la vista attuale."], empty: ["Crea la tua panoramica finanziaria con dati reali","Aggiungi transazioni manualmente o importa un CSV. MoneyPilot usa i tuoi dati per calcolare entrate, uscite e abitudini di spesa.","Aggiungi transazione","Importa CSV","Perché iniziare con CSV?","L’importazione CSV è disponibile. Il flusso completo di importazione PDF non è ancora disponibile.","Inizia con una transazione manuale o importa un CSV."], steps: [["Nessun collegamento bancario necessario","Non devi condividere le credenziali bancarie."],["Un punto di partenza più chiaro","Importa transazioni CSV recenti per creare la tua panoramica finanziaria."],["Mantieni il controllo","Controlla le transazioni prima di importarle."]], error: ["ERRORE", "Non è stato possibile caricare la panoramica finanziaria", "I tuoi dati sono al sicuro. MoneyPilot non ha potuto completare la richiesta ora. Riprova o torna alla schermata precedente.", "Riprova", "Indietro", "Se il problema persiste", "I TUOI DATI SONO AL SICURO", "Riprova ricarica solo questa vista. Non crea, elimina o sposta dati finanziari."], help: [["Controlla la connessione", "Assicurati che la connessione Internet sia disponibile."], ["Prova ancora", "Ripeti l’azione. I dati salvati non verranno duplicati."], ["Ottieni assistenza", "Apri l’Assistenza se lo stesso errore continua a comparire."]] },
};

export function DashboardLoadingState() {
  const { language } = useLanguage(); const t = systemCopy[language].loading;
  return <div role="status" aria-live="polite" aria-busy="true" className="flex h-[725px] flex-col gap-[12px] pt-[12px]">
    <div className="flex h-[54px] items-center justify-between rounded-[14px] border border-[var(--border-default)] bg-[var(--background-card)] px-[14px]"><div><strong className="block text-[14px] text-[var(--text-primary)]">{t[0]}</strong><span className="text-[9px] text-[var(--text-secondary)]">{t[1]}</span></div><span className="rounded-full border border-[var(--dashboard-brand-border)] bg-[var(--dashboard-brand-soft)] px-[28px] py-[5px] text-[8px] font-semibold text-[var(--dashboard-brand-primary)]">{t[2]}</span></div>
    <div className="grid h-[90px] grid-cols-4 gap-[12px]">{[0,1,2,3].map((item) => <SkeletonCard key={item} />)}</div>
    <div className="grid h-[184px] grid-cols-[1.8fr_1fr] gap-[12px]"><div className="rounded-[14px] border border-[var(--border-default)] bg-[var(--background-card)] p-[14px]"><div className={`${skeleton} h-[11px] w-[125px]`} /><div className="mt-[42px] flex h-[90px] items-end justify-center gap-[30px]">{[42,66,52,82,59,74,48].map((height, index) => <div key={index} className="flex items-end gap-[4px]"><span className={`${skeleton} w-[15px]`} style={{ height }} /><span className={`${skeleton} w-[8px] opacity-70`} style={{ height: height * .65 }} /></div>)}</div></div><div className="flex items-center gap-[22px] rounded-[14px] border border-[var(--border-default)] bg-[var(--background-card)] p-[18px]"><div className="size-[82px] rounded-full border-[14px] border-[color-mix(in_srgb,var(--text-secondary)_12%,transparent)]" /><div className="flex-1 space-y-[13px]"><div className={`${skeleton} h-[10px] w-full`} /><div className={`${skeleton} h-[10px] w-full`} /><div className={`${skeleton} h-[10px] w-4/5`} /></div></div></div>
    <div className="grid h-[180px] grid-cols-4 gap-[12px]">{[0,1,2,3].map((item) => <SkeletonCard key={item} tall />)}</div>
    <p className="mt-auto text-[9px] text-[var(--text-secondary)]">{t[3]}</p>
  </div>;
}

function SkeletonCard({ tall = false }: { tall?: boolean }) {
  return <div className="rounded-[14px] border border-[var(--border-default)] bg-[var(--background-card)] p-[12px]"><div className={`${skeleton} h-[10px] w-[64px]`} /><div className={`${skeleton} mt-[13px] h-[16px] w-[92px]`} /><div className={`${skeleton} mt-[12px] h-[8px] w-3/4`} /><div className={`${skeleton} mt-[12px] ${tall ? "h-[34px]" : "h-[10px]"} w-full`} />{tall && <div className={`${skeleton} mt-[12px] h-[18px] w-full`} />}</div>;
}

export function DashboardEmptyState() {
  const { language } = useLanguage();
  const t = systemCopy[language].empty;
  const steps = systemCopy[language].steps;

  return (
    <div className="relative flex h-[724px] w-full items-start justify-center px-4 pt-[48px] sm:pt-[60px]">
      <section aria-labelledby="dashboard-first-access-title" className="w-full min-w-0 max-w-[654px] rounded-[24px] border border-[var(--border-default)] bg-[var(--background-elevated)] p-5 text-center text-[var(--text-primary)] shadow-[var(--shadow-card)] sm:p-7">
        <p className="text-[16px] font-semibold">MoneyPilot</p>
        <p className="mt-2 text-[12px] font-medium">{t[6]}</p>
        <div className="mx-auto mt-4 grid size-[48px] place-items-center rounded-full border border-[var(--dashboard-brand-border)] bg-[var(--dashboard-brand-soft)]">
          <Image src="/moneypilot/transactions/import/upload.svg" alt="" width={24} height={24} />
        </div>
        <h1 id="dashboard-first-access-title" className="mx-auto mt-4 max-w-[510px] text-[24px] font-semibold leading-tight">{t[0]}</h1>
        <p className="mx-auto mt-3 max-w-[510px] text-[11px] leading-relaxed text-[var(--text-secondary)]">{t[1]}</p>
        <Link href="/transactions?import=csv" className="mt-5 flex min-h-11 w-full items-center justify-center rounded-[12px] bg-[var(--dashboard-brand-primary)] px-4 py-3 text-[12px] font-semibold text-[var(--text-inverse)] transition-colors hover:bg-[var(--dashboard-brand-primary-hover)] active:bg-[var(--dashboard-brand-primary-active)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--dashboard-focus)]">{t[3]}</Link>
        <Link href="/transactions" className="mt-2 inline-flex min-h-11 items-center justify-center rounded-[12px] px-4 text-[11px] font-medium text-[var(--text-secondary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--dashboard-focus)]">{t[2]}</Link>
        <p className="mt-1 text-[10px] leading-relaxed text-[var(--text-tertiary)]">{t[5]}</p>
        <div className="mt-4 rounded-[14px] border border-[var(--border-default)] bg-[var(--background-card)] p-4 text-left">
          <h2 className="text-[10px] font-semibold uppercase tracking-wide text-[var(--dashboard-brand-primary)]">{t[4]}</h2>
          <ul className="mt-3 grid gap-3">
            {steps.map(([title, detail]) => (
              <li key={title} className="flex min-w-0 gap-2">
                <span aria-hidden="true" className="text-[var(--dashboard-brand-primary)]">&#10003;</span>
                <div className="min-w-0 text-[10px] leading-relaxed"><h3 className="font-medium">{title}</h3><p className="text-[var(--text-secondary)]">{detail}</p></div>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}

export function DashboardErrorState({ error, onRetry }: { error: Error | string; onRetry?: () => void }) {
  const router = useRouter();
  const { language } = useLanguage(); const t = systemCopy[language].error; const help = systemCopy[language].help;
  return <div className="absolute inset-0 z-30 flex items-center justify-center bg-[color-mix(in_srgb,var(--background-app)_66%,transparent)] backdrop-blur-[5px]"><section role="alert" className="relative flex h-[420px] w-[660px] flex-col items-center rounded-[24px] border border-[var(--border-default)] bg-[var(--background-elevated)] px-[30px] py-[24px] text-center shadow-[0_22px_60px_rgba(0,0,0,0.32)]"><span className="absolute right-[24px] top-[20px] rounded-full border border-[#EF4444]/50 bg-[#EF4444]/10 px-[24px] py-[4px] text-[8px] font-semibold text-[#EF4444]">{t[0]}</span><div className="grid size-[54px] place-items-center rounded-full border border-[#EF4444]/55 bg-[#EF4444]/10 text-[24px] text-[#EF4444]" aria-hidden="true">!</div><h1 className="mt-[20px] text-[20px] font-semibold text-[var(--text-primary)]">{t[1]}</h1><p className="mt-[10px] max-w-[520px] text-[10px] leading-[14px] text-[var(--text-secondary)]">{t[2]}</p><div className="mt-[18px] flex gap-[12px]"><button type="button" onClick={onRetry} disabled={!onRetry} className="h-[34px] min-w-[120px] rounded-full bg-[var(--dashboard-brand-primary)] px-[22px] text-[10px] font-semibold text-white transition-colors hover:bg-[var(--dashboard-brand-primary-hover)] active:bg-[var(--dashboard-brand-primary-active)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--dashboard-focus)] disabled:cursor-not-allowed disabled:bg-[var(--dashboard-brand-soft)]">{t[3]}</button><button type="button" onClick={() => router.back()} className="h-[34px] min-w-[120px] rounded-full border border-[var(--border-default)] px-[22px] text-[10px] font-medium text-[var(--text-primary)]">{t[4]}</button></div><strong className="mt-[22px] text-[9px] text-[var(--text-primary)]">{t[5]}</strong><div className="mt-[12px] grid w-full grid-cols-3 gap-[8px] text-left">{help.map(([title, text]) => <div key={title} className="h-[76px] rounded-[12px] border border-[var(--border-default)] bg-[var(--background-card)] p-[11px]"><strong className="text-[9px] text-[var(--text-primary)]">{title}</strong><p className="mt-[10px] text-[8px] leading-[11px] text-[var(--text-secondary)]">{text}</p></div>)}</div><div className="mt-[10px] w-full rounded-[10px] border border-[#22C55E]/45 bg-[#22C55E]/10 px-[12px] py-[8px] text-left"><strong className="block text-[8px] text-[#22C55E]">{t[6]}</strong><span className="text-[8px] text-[var(--text-secondary)]">{t[7]}</span></div><span className="sr-only">{error instanceof Error ? error.message : error}</span></section></div>;
}

// Section feedback reuses Dashboard copy without a page-wide overlay.
export function DashboardSectionState({ status, className = "flex h-full min-h-[112px] w-full items-center justify-center px-[14px] text-center text-[10px] text-[var(--text-secondary)]" }: { status: "loading" | "error"; className?: string }) {
  const { language } = useLanguage();
  return <div role={status === "loading" ? "status" : "alert"} aria-busy={status === "loading" || undefined} className={className}>{systemCopy[language][status][status === "loading" ? 0 : 1]}</div>;
}
