"use client";

import Image from "next/image";
import { useMemo } from "react";
import { DesktopScaleCanvas } from "@/components/DesktopScaleCanvas";
import { calculateDashboardFinancialSummary, getDashboardMonth } from "@/components/dashboard/dashboard-financial-summary";
import { calculateNextBestAction } from "@/components/dashboard/next-best-action";
import { useFinanceData } from "@/components/FinanceDataProvider";
import { InsightsSpendingChart } from "@/components/insights/InsightsSpendingChart";
import { useLanguage } from "@/components/LanguageProvider";
import { useCurrency } from "@/components/CurrencyProvider";

const iconRoot = "/moneypilot/insights/icons";
const styles = [{ color: "#8B5CF6", icon: "pricetag-outline.svg" }, { color: "#F43F5E", icon: "receipt-refund.svg" }, { color: "#22C55E", icon: "currency-dollar.svg" }, { color: "#3B82F6", icon: "target.svg" }];
const card = "overflow-hidden rounded-[18px] border border-[#28313B] bg-[rgba(8,11,15,0.20)] shadow-[0_6px_14px_rgba(0,0,0,0.20)]";

const translations = {
  en: { title: "AI Insights", description: "Understand your finances through real data and deterministic analysis.", analysis: "Financial insights", comparison: "Comparison with previous month", spending: "Where your money weighs most", patterns: "Detected patterns", plan: "Recommended plan", opportunities: "Priority opportunities", total: "Total", labels: ["Monthly priority", "Income usage", "Potential savings", "Goal impact"], noPriority: "No priority yet", priorityHelp: "Add transactions and budgets to identify what needs attention.", noIncome: "No income data yet", notCalculated: "Not calculated yet", noGoal: "No goal yet", goalHelp: "Create a goal to measure potential impact.", noInsights: "No insights yet", insightsHelp: "Add transactions or import a statement to start building your analysis.", notEnough: "Not enough data yet", comparisonHelp: "Add transactions across multiple months to see changes over time.", noSpending: "No spending data yet", spendingHelp: "Add expenses to see your category breakdown.", noPatterns: "No patterns yet", patternsHelp: "Patterns will appear after MoneyPilot has enough transaction history.", noRecommendation: "No recommendation yet", recommendationHelp: "Add financial data to receive the next deterministic action.", noOpportunities: "No opportunities detected yet", opportunitiesHelp: "Opportunities will appear when financial data needs attention.", loading: "Loading financial data…", ofIncome: "of income used", perMonth: "/month", remaining: "remaining" },
  pt: { title: "Insights IA", description: "Entenda suas finanças com dados reais e análise determinística.", analysis: "Insights financeiros", comparison: "Comparação com o mês anterior", spending: "Onde seu dinheiro mais pesa", patterns: "Padrões detectados", plan: "Plano recomendado", opportunities: "Oportunidades prioritárias", total: "Total", labels: ["Prioridade do mês", "Uso da renda", "Economia possível", "Impacto na meta"], noPriority: "Nenhuma prioridade ainda", priorityHelp: "Adicione transações e orçamentos para identificar o que precisa de atenção.", noIncome: "Ainda não há dados de renda", notCalculated: "Ainda não calculado", noGoal: "Nenhuma meta ainda", goalHelp: "Crie uma meta para medir o impacto potencial.", noInsights: "Ainda não há insights", insightsHelp: "Adicione transações ou importe um extrato para começar sua análise.", notEnough: "Ainda não há dados suficientes", comparisonHelp: "Adicione transações em vários meses para ver mudanças ao longo do tempo.", noSpending: "Ainda não há dados de despesas", spendingHelp: "Adicione despesas para ver a distribuição por categoria.", noPatterns: "Ainda não há padrões", patternsHelp: "Os padrões aparecerão quando o MoneyPilot tiver histórico suficiente.", noRecommendation: "Ainda não há recomendação", recommendationHelp: "Adicione dados financeiros para receber a próxima ação determinística.", noOpportunities: "Nenhuma oportunidade detectada", opportunitiesHelp: "As oportunidades aparecerão quando os dados financeiros precisarem de atenção.", loading: "Carregando dados financeiros…", ofIncome: "da renda usada", perMonth: "/mês", remaining: "restantes" },
  es: { title: "Insights de IA", description: "Entiende tus finanzas con datos reales y análisis determinista.", analysis: "Insights financieros", comparison: "Comparación con el mes anterior", spending: "Dónde pesa más tu dinero", patterns: "Patrones detectados", plan: "Plan recomendado", opportunities: "Oportunidades prioritarias", total: "Total", labels: ["Prioridad del mes", "Uso de los ingresos", "Ahorro posible", "Impacto en el objetivo"], noPriority: "Aún no hay prioridad", priorityHelp: "Añade transacciones y presupuestos para identificar qué necesita atención.", noIncome: "Aún no hay datos de ingresos", notCalculated: "Aún no calculado", noGoal: "Aún no hay objetivo", goalHelp: "Crea un objetivo para medir el impacto potencial.", noInsights: "Aún no hay insights", insightsHelp: "Añade transacciones o importa un extracto para comenzar tu análisis.", notEnough: "Aún no hay datos suficientes", comparisonHelp: "Añade transacciones de varios meses para ver cambios en el tiempo.", noSpending: "Aún no hay datos de gastos", spendingHelp: "Añade gastos para ver la distribución por categoría.", noPatterns: "Aún no hay patrones", patternsHelp: "Los patrones aparecerán cuando MoneyPilot tenga suficiente historial.", noRecommendation: "Aún no hay recomendación", recommendationHelp: "Añade datos financieros para recibir la siguiente acción determinista.", noOpportunities: "Aún no se detectaron oportunidades", opportunitiesHelp: "Las oportunidades aparecerán cuando los datos financieros necesiten atención.", loading: "Cargando datos financieros…", ofIncome: "de los ingresos usados", perMonth: "/mes", remaining: "restantes" },
};
const extendedTranslations = {
  ...translations,
  de: { ...translations.en, title: "Finanzielle Einblicke", description: "Verstehe deine Finanzen anhand echter Daten und nachvollziehbarer Analysen.", analysis: "Finanzielle Einblicke", comparison: "Vergleich mit dem Vormonat", spending: "Wofür du am meisten ausgibst", patterns: "Erkannte Muster", plan: "Empfohlener Plan", opportunities: "Wichtige Möglichkeiten", labels: ["Priorität des Monats", "Einkommensnutzung", "Mögliches Sparpotenzial", "Auswirkung auf das Ziel"], noPriority: "Noch keine Priorität", priorityHelp: "Füge Transaktionen und Budgets hinzu, um Handlungsbedarf zu erkennen.", noIncome: "Noch keine Einkommensdaten", notCalculated: "Noch nicht berechnet", noGoal: "Noch kein Ziel", goalHelp: "Erstelle ein Ziel, um mögliche Auswirkungen zu messen.", noInsights: "Noch keine Einblicke", insightsHelp: "Füge Transaktionen hinzu oder importiere einen Kontoauszug.", notEnough: "Noch nicht genügend Daten", comparisonHelp: "Füge Transaktionen aus mehreren Monaten hinzu.", noSpending: "Noch keine Ausgabendaten", spendingHelp: "Füge Ausgaben hinzu, um die Verteilung nach Kategorien zu sehen.", noPatterns: "Noch keine Muster", patternsHelp: "Muster erscheinen, sobald genügend Transaktionsverlauf vorhanden ist.", noRecommendation: "Noch keine Empfehlung", recommendationHelp: "Füge Finanzdaten hinzu, um eine Empfehlung zu erhalten.", noOpportunities: "Noch keine Möglichkeiten erkannt", opportunitiesHelp: "Möglichkeiten erscheinen, wenn Finanzdaten Aufmerksamkeit erfordern.", loading: "Finanzdaten werden geladen…", ofIncome: "des Einkommens verwendet", perMonth: "/Monat", remaining: "verbleibend" },
  fr: { ...translations.en, title: "Analyses financières", description: "Comprenez vos finances à partir de données réelles et d’analyses déterministes.", analysis: "Analyses financières", comparison: "Comparaison avec le mois précédent", spending: "Vos principales dépenses", patterns: "Tendances détectées", plan: "Plan recommandé", opportunities: "Opportunités prioritaires", labels: ["Priorité du mois", "Utilisation des revenus", "Épargne potentielle", "Impact sur l’objectif"], noPriority: "Aucune priorité pour le moment", priorityHelp: "Ajoutez des transactions et des budgets pour identifier les points d’attention.", noIncome: "Aucune donnée de revenus", notCalculated: "Pas encore calculé", noGoal: "Aucun objectif", goalHelp: "Créez un objectif pour mesurer l’impact potentiel.", noInsights: "Aucune analyse pour le moment", insightsHelp: "Ajoutez des transactions ou importez un relevé.", notEnough: "Données insuffisantes", comparisonHelp: "Ajoutez des transactions sur plusieurs mois.", noSpending: "Aucune donnée de dépenses", spendingHelp: "Ajoutez des dépenses pour voir la répartition par catégorie.", noPatterns: "Aucune tendance pour le moment", patternsHelp: "Les tendances apparaîtront avec un historique suffisant.", noRecommendation: "Aucune recommandation", recommendationHelp: "Ajoutez des données financières pour recevoir une recommandation.", noOpportunities: "Aucune opportunité détectée", opportunitiesHelp: "Les opportunités apparaîtront lorsque vos données nécessiteront votre attention.", loading: "Chargement des données financières…", ofIncome: "des revenus utilisés", perMonth: "/mois", remaining: "restants" },
  nl: { ...translations.en, title: "Financiële inzichten", description: "Krijg inzicht in je financiën met echte gegevens en vaste analyses.", analysis: "Financiële inzichten", comparison: "Vergelijking met vorige maand", spending: "Waar je geld het meest naartoe gaat", patterns: "Gedetecteerde patronen", plan: "Aanbevolen plan", opportunities: "Belangrijkste kansen", labels: ["Prioriteit van de maand", "Gebruik van inkomen", "Mogelijke besparing", "Effect op doel"], noPriority: "Nog geen prioriteit", priorityHelp: "Voeg transacties en budgetten toe om aandachtspunten te vinden.", noIncome: "Nog geen inkomensgegevens", notCalculated: "Nog niet berekend", noGoal: "Nog geen doel", goalHelp: "Maak een doel om het mogelijke effect te meten.", noInsights: "Nog geen inzichten", insightsHelp: "Voeg transacties toe of importeer een afschrift.", notEnough: "Nog niet genoeg gegevens", comparisonHelp: "Voeg transacties uit meerdere maanden toe.", noSpending: "Nog geen uitgavengegevens", spendingHelp: "Voeg uitgaven toe om de verdeling per categorie te zien.", noPatterns: "Nog geen patronen", patternsHelp: "Patronen verschijnen zodra er genoeg transactiehistorie is.", noRecommendation: "Nog geen aanbeveling", recommendationHelp: "Voeg financiële gegevens toe om een aanbeveling te ontvangen.", noOpportunities: "Nog geen kansen gevonden", opportunitiesHelp: "Kansen verschijnen wanneer financiële gegevens aandacht vragen.", loading: "Financiële gegevens laden…", ofIncome: "van inkomen gebruikt", perMonth: "/maand", remaining: "resterend" },
  it: { ...translations.en, title: "Analisi finanziarie", description: "Comprendi le tue finanze con dati reali e analisi deterministiche.", analysis: "Analisi finanziarie", comparison: "Confronto con il mese precedente", spending: "Dove spendi di più", patterns: "Modelli rilevati", plan: "Piano consigliato", opportunities: "Opportunità prioritarie", labels: ["Priorità del mese", "Utilizzo delle entrate", "Risparmio potenziale", "Impatto sull’obiettivo"], noPriority: "Nessuna priorità per ora", priorityHelp: "Aggiungi transazioni e budget per individuare ciò che richiede attenzione.", noIncome: "Nessun dato sulle entrate", notCalculated: "Non ancora calcolato", noGoal: "Nessun obiettivo", goalHelp: "Crea un obiettivo per misurare il potenziale impatto.", noInsights: "Nessuna analisi per ora", insightsHelp: "Aggiungi transazioni o importa un estratto conto.", notEnough: "Dati non ancora sufficienti", comparisonHelp: "Aggiungi transazioni di più mesi.", noSpending: "Nessun dato sulle spese", spendingHelp: "Aggiungi spese per vedere la distribuzione per categoria.", noPatterns: "Nessun modello per ora", patternsHelp: "I modelli appariranno quando ci sarà uno storico sufficiente.", noRecommendation: "Nessun consiglio per ora", recommendationHelp: "Aggiungi dati finanziari per ricevere un consiglio.", noOpportunities: "Nessuna opportunità rilevata", opportunitiesHelp: "Le opportunità appariranno quando i dati richiederanno attenzione.", loading: "Caricamento dei dati finanziari…", ofIncome: "delle entrate utilizzato", perMonth: "/mese", remaining: "rimanenti" },
};

function Neutral({ title, detail }: { title: string; detail: string }) { return <div className="flex h-full flex-col items-center justify-center px-[18px] text-center"><strong className="text-[10px]">{title}</strong>{detail && <p className="mt-[5px] max-w-[420px] text-[8.5px] leading-[12px] text-[#9CA6B2]">{detail}</p>}</div>; }

export default function InsightsPage() {
  const { language } = useLanguage();
  const { formatMoney: money } = useCurrency();
  const t = extendedTranslations[language];
  const data = useFinanceData();
  const month = getDashboardMonth();
  const summary = useMemo(() => calculateDashboardFinancialSummary({ transactions: data.transactions, budgets: data.budgets, budgetAdjustments: data.budgetAdjustments, goals: data.goals, goalContributionPlans: data.goalContributionPlans, month }), [data.transactions, data.budgets, data.budgetAdjustments, data.goals, data.goalContributionPlans, month]);
  const action = useMemo(() => calculateNextBestAction({ monthlyStatus: summary.monthlyStatus, budgetProjection: summary.budgetProjection, safeSavingsCapacity: summary.safeSavingsCapacity, primaryGoal: summary.primaryGoal, hasActiveBudgetAdjustment: summary.savingsCapacity.activeAdjustmentTarget !== null }), [summary]);
  const hasPriority = summary.hasTransactions && summary.hasBudgets;
  const hasUsage = summary.income > 0 && summary.expenseTransactionCount > 0;
  const hasSavings = summary.hasBudgets && summary.budgetProjection.canProject && summary.safeSavingsCapacity > 0;
  const metrics = [
    { value: hasPriority ? action.title : t.noPriority, detail: hasPriority ? action.description : t.priorityHelp },
    { value: hasUsage ? `${(summary.expenses / summary.income * 100).toLocaleString(language, { maximumFractionDigits: 1 })}%` : "—", detail: hasUsage ? `${money(summary.expenses)} · ${t.ofIncome}` : t.noIncome },
    { value: hasSavings ? `${money(summary.safeSavingsCapacity)}${t.perMonth}` : "—", detail: hasSavings ? action.description : t.notCalculated },
    { value: summary.primaryGoal?.goal.name ?? t.noGoal, detail: summary.primaryGoal ? `${money(summary.primaryGoal.calculation.remainingAmount)} ${t.remaining}` : t.goalHelp },
  ];
  const hasData = summary.hasFinancialData && !data.isHydrating;
  const recommendation = hasData && action.type !== "no_action";
  const monthLabel = new Intl.DateTimeFormat(language === "pt" ? "pt-PT" : language === "es" ? "es-ES" : "en-GB", { month: "long", year: "numeric" }).format(new Date());
  const panel = (heading: string, title: string, detail: string) => <section className={`${card} px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{heading}</h2><div className="h-[130px]"><Neutral title={title} detail={detail} /></div></section>;

  return <div className="relative min-h-screen bg-[#080B0F]"><DesktopScaleCanvas><main className="relative h-[1024px] w-[1536px] overflow-hidden text-[#F5F7FA]"><section className="absolute left-[231px] top-[107px] h-[810px] w-[1164px] overflow-hidden rounded-[38px] border border-[#28313B]/16 bg-[#0D1117]/50 px-[32px] py-[16px] shadow-[0_22px_42px_rgba(0,0,0,0.45)] backdrop-blur-[20px]"><div className="flex h-[767.67px] w-[1098px] flex-col gap-[12px] overflow-hidden">
    <div className="flex h-[36.75px] shrink-0 items-center gap-[18px]"><div className="h-[37px] w-[37px] overflow-hidden"><Image src="/moneypilot/moneypilot-logo.svg" alt="" width={180} height={40} priority className="h-[37px] w-auto max-w-none" /></div><span className="money-pilot-wordmark font-brand text-[21.44px] font-medium tracking-[0.429px]">MoneyPilot</span></div>
    <header className="flex h-[58px] shrink-0 items-center justify-between"><div><h1 className="text-[23px] font-semibold leading-none">{t.title}</h1><p className="mt-[5px] text-[13px] text-[#9CA6B2]">{t.description}</p></div><div className="flex items-center gap-[16px]"><div className="flex h-[38px] items-center gap-[7px] rounded-[19px] border border-[#28313B] px-[13px] text-[11px] capitalize text-[#9CA6B2]"><Image src="/moneypilot/budgets/icons/calendar.svg" alt="" width={18} height={18} />{monthLabel}</div><Image src="/moneypilot/dashboard-avatar.png" alt="" width={52} height={52} className="rounded-full" /></div></header>
    <div className="flex h-[100px] shrink-0 gap-[12px]">{metrics.map((metric, index) => <article key={t.labels[index]} className={`${card} flex h-[100px] w-[265.5px] flex-col gap-[6px] px-[12px] py-[10px]`}><div className="flex items-center gap-[8px]"><span className="flex size-[30px] items-center justify-center rounded-[9px] border" style={{ borderColor: styles[index].color, backgroundColor: `${styles[index].color}24` }}><Image src={`${iconRoot}/${styles[index].icon}`} alt="" width={20} height={20} /></span><h2 className="text-[11px] font-semibold">{t.labels[index]}</h2></div><strong className="truncate text-[18px] leading-none">{data.isHydrating ? "—" : metric.value}</strong><p className="truncate text-[9px] text-[#9CA6B2]">{data.isHydrating ? t.loading : metric.detail}</p></article>)}</div>
    <div className="flex h-[177px] shrink-0 gap-[12px]"><section className={`${card} h-[177px] w-[677px] px-[12px] py-[11px]`}><div className="flex items-center gap-[7px]"><span className="flex size-[25px] items-center justify-center rounded-[8px] border border-[#3B82F6]/50 bg-[#60A5FA]/15 text-[8px] font-bold text-[#60A5FA]">MP</span><h2 className="text-[14px] font-semibold">{t.analysis}</h2></div><div className="h-[125px]"><Neutral title={hasData ? action.title : data.isHydrating ? t.loading : t.noInsights} detail={hasData ? action.description : data.isHydrating ? "" : t.insightsHelp} /></div></section><div className="h-[177px] w-[409px]">{panel(t.comparison, t.notEnough, t.comparisonHelp)}</div></div>
    <div className="flex h-[175px] shrink-0 gap-[12px]"><section className={`${card} h-[175px] w-[409px] px-[12px] py-[10px]`}><h2 className="text-[14px] font-semibold">{t.spending}</h2><InsightsSpendingChart categories={summary.categorySpending} total={summary.expenses} language={language} emptyTitle={t.noSpending} emptyCopy={t.spendingHelp} totalLabel={t.total} /></section><div className="h-[175px] w-[677px]">{panel(t.patterns, t.noPatterns, t.patternsHelp)}</div></div>
    <div className="flex h-[170px] shrink-0 gap-[12px]"><div className="h-[170px] w-[409px]">{panel(t.plan, recommendation ? action.title : t.noRecommendation, recommendation ? action.description : t.recommendationHelp)}</div><div className="h-[170px] w-[677px]">{panel(t.opportunities, summary.monthlyStatus === "over_budget" ? action.title : t.noOpportunities, summary.monthlyStatus === "over_budget" ? action.description : t.opportunitiesHelp)}</div></div>
  </div></section></main></DesktopScaleCanvas></div>;
}
