import assert from "node:assert/strict";
import test from "node:test";
import { calculateGoal, calculateGoalCollectionTotals } from "../../src/components/goals/goal-calculations.ts";
import { calculateGoalPlanMonthlyTarget, isGoalContributionPlanStale } from "../../src/components/goals/goal-contribution-plan.ts";
import { selectPrimaryGoal, type Goal } from "../../src/components/goals/goal-model.ts";
import { calculateDashboardFinancialSummary } from "../../src/components/dashboard/dashboard-financial-summary.ts";
import { readFileSync } from "node:fs";

const goal = (targetAmount: number, savedAmount: number, targetDate = "2027-01"): Goal => ({ id: "goal", name: "private", targetAmount, savedAmount, targetDate, priority: "primary" });
const now = new Date(2026, 8, 10);

test("calculates safe remaining money and partial progress", () => { const result = calculateGoal(goal(0.3, 0.1), now); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.remainingAmount, 0.2); assert.ok(Math.abs(result.progressRatio - (1 / 3)) < 1e-12); });
test("preserves legitimate zero progress", () => { const result = calculateGoal(goal(100, 0), now); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.progressPercent, 0); assert.equal(result.isCompleted, false); });
test("recognizes exact completion with zero remaining and contribution", () => { const result = calculateGoal(goal(100, 100), now); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.progressPercent, 100); assert.equal(result.remainingAmount, 0); assert.equal(result.requiredMonthlyContribution, 0); });
test("preserves real progress above 100 while bounding only visual progress", () => { const result = calculateGoal(goal(100, 125), now); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.actualProgressPercent, 125); assert.equal(result.progressPercent, 100); assert.equal(result.visualProgressPercent, 100); assert.equal(result.remainingAmount, 0); });
test("invalid money and zero target produce typed unavailability", () => { for (const result of [calculateGoal(goal(Number.NaN, 0), now), calculateGoal(goal(0, 0), now), calculateGoal(goal(Infinity, 0), now)]) { assert.equal(result.available, false); assert.equal(result.remainingAmount, null); assert.equal(result.progressRatio, null); assert.equal(result.isCompleted, null); } });
test("uses civil month differences across December and January", () => { const result = calculateGoal(goal(120, 0, "2027-01"), new Date(2026, 11, 15)); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.monthsRemaining, 1); assert.equal(result.requiredMonthlyContribution, 120); });
test("handles future, current, past and missing target months", () => { const future = calculateGoal(goal(120, 0, "2027-01"), now); const current = calculateGoal(goal(120, 20, "2026-09"), now); const past = calculateGoal(goal(120, 20, "2026-08"), now); const missing = calculateGoal(goal(120, 20, "invalid"), now); assert.equal(future.available && future.requiredMonthlyContribution, 30); assert.equal(current.available && current.requiredMonthlyContribution, 100); assert.equal(past.available && past.requiredMonthlyContribution, null); assert.equal(missing.available && missing.requiredMonthlyContribution, null); });
test("normalizes only the final monthly monetary result", () => { const result = calculateGoal(goal(1, 0, "2026-12"), now); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.requiredMonthlyContribution, 0.3333); });
test("aggregates collection totals atomically and order-independently", () => { const goals = [goal(0.1, 0.0001), { ...goal(0.2, 0.0002), id: "two", priority: "secondary" as const }]; const result = calculateGoalCollectionTotals(goals); assert.deepEqual(result, calculateGoalCollectionTotals([...goals].reverse())); assert.equal(result.available, true); if (!result.available) return; assert.equal(result.targetAmount, 0.3); assert.equal(result.savedAmount, 0.0003); assert.equal(result.remainingAmount, 0.2997); });
test("an invalid goal prevents partial collection totals", () => { const result = calculateGoalCollectionTotals([goal(100, 10), { ...goal(100, Number.NaN), id: "private-id" }]); assert.equal(result.available, false); assert.equal(result.targetAmount, null); assert.equal(result.savedAmount, null); assert.equal(result.remainingAmount, null); assert.equal(JSON.stringify(result).includes("private"), false); });
test("an unsafe collection prevents partial totals", () => { const result = calculateGoalCollectionTotals([goal(900719925474.0991, 0), goal(0.0001, 0)]); assert.equal(result.available, false); assert.equal(result.unavailableReason, "unsafe_aggregate"); assert.equal(result.targetAmount, null); });
test("monthly plan targets use safe decimal aggregation", () => { assert.deepEqual(calculateGoalPlanMonthlyTarget(0.1, 0.2), { available: true, value: 0.3 }); assert.deepEqual(calculateGoalPlanMonthlyTarget(900719925474.0991, 0.0001), { available: false, reason: "unsafe_aggregate" }); });
test("plan staleness treats invalid comparisons as stale", () => { const plan = { goalId: "goal", monthlyTarget: 30, baselineRequiredMonthlyContribution: 20, savingsBoost: 10, createdAt: "2026-09-10T00:00:00.000Z" }; assert.equal(isGoalContributionPlanStale(plan, 20, 10), false); assert.equal(isGoalContributionPlanStale(plan, null, 10), true); assert.equal(isGoalContributionPlanStale(plan, Number.NaN, 10), true); });
test("primary selection and ordering remain unchanged", () => { const secondary = { ...goal(100, 0), id: "first", priority: "secondary" as const }; const primary = { ...goal(100, 0), id: "second" }; const goals = [secondary, primary]; assert.equal(selectPrimaryGoal(goals), primary); assert.deepEqual(goals, [secondary, primary]); });
test("dashboard exposes primary-goal unavailability without a false percentage", () => { const summary = calculateDashboardFinancialSummary({ transactions: [], budgets: [], budgetAdjustments: {}, goals: [goal(Number.NaN, 0)], goalContributionPlans: {}, month: "2026-09", now }); assert.equal(summary.hasGoals, true); assert.equal(summary.goalsAvailable, false); assert.equal(summary.primaryGoal, null); });
test("next best action blocks goal recommendations when goal calculations are unavailable", () => { const source = readFileSync(new URL("../../src/components/dashboard/next-best-action.ts", import.meta.url), "utf8"); assert.match(source, /!goalsAvailable \|\| \(hasGoals && !primaryGoal\).*goal_calculation_unavailable/); });
