"use client";

import { useCurrency } from "@/components/CurrencyProvider";
import { useEffect, useId } from "react";
import { IconAlertTriangle } from "@tabler/icons-react";
import type { Goal } from "@/components/goals/goal-model";
import type { Language } from "@/components/LanguageProvider";
import { formatGoalTargetDate } from "@/components/goals/goal-model";

const copy: Record<Language, { title: string; description: string; target: string; saved: string; warning: string; cancel: string; confirm: string }> = {
  en: { title: "Delete goal?", description: "This removes the goal from your list for this session.", target: "Target", saved: "Saved", warning: "You cannot undo this action in the current local session.", cancel: "Cancel", confirm: "Delete goal" }, pt: { title: "Excluir meta?", description: "Isso remove a meta da sua lista nesta sessão.", target: "Meta", saved: "Guardado", warning: "Não é possível desfazer esta ação na sessão local atual.", cancel: "Cancelar", confirm: "Excluir meta" }, es: { title: "¿Eliminar objetivo?", description: "Esto elimina el objetivo de tu lista durante esta sesión.", target: "Objetivo", saved: "Ahorrado", warning: "No puedes deshacer esta acción en la sesión local actual.", cancel: "Cancelar", confirm: "Eliminar objetivo" },
  de: { title: "Ziel löschen?", description: "Dadurch wird das Ziel für diese Sitzung aus deiner Liste entfernt.", target: "Ziel", saved: "Gespart", warning: "Diese Aktion kann in der aktuellen lokalen Sitzung nicht rückgängig gemacht werden.", cancel: "Abbrechen", confirm: "Ziel löschen" }, fr: { title: "Supprimer l’objectif ?", description: "Cette action retire l’objectif de votre liste pour cette session.", target: "Objectif", saved: "Épargné", warning: "Cette action est irréversible pendant la session locale actuelle.", cancel: "Annuler", confirm: "Supprimer l’objectif" }, nl: { title: "Doel verwijderen?", description: "Hiermee wordt het doel voor deze sessie uit je lijst verwijderd.", target: "Doel", saved: "Gespaard", warning: "Je kunt deze actie in de huidige lokale sessie niet ongedaan maken.", cancel: "Annuleren", confirm: "Doel verwijderen" }, it: { title: "Eliminare l’obiettivo?", description: "Questa azione rimuove l’obiettivo dall’elenco per questa sessione.", target: "Obiettivo", saved: "Risparmiato", warning: "Non puoi annullare questa azione nella sessione locale corrente.", cancel: "Annulla", confirm: "Elimina obiettivo" },
};

export function DeleteGoalModal({ goal, language, onClose, onConfirm }: { goal: Goal; language: Language; onClose: () => void; onConfirm: () => void }) {
  const { formatMoney: money } = useCurrency();
  const titleId = useId(); const text = copy[language];
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[rgba(2,6,10,0.68)] backdrop-blur-[2px]" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby={titleId} className="h-[424px] w-[500px] rounded-[24px] border border-[var(--border-default)] bg-[var(--background-elevated)] p-[27px] text-[var(--text-primary)] shadow-[0_24px_24px_rgba(0,0,0,0.52)]"><div className="flex items-center gap-[16px]"><span className="flex size-[44px] items-center justify-center rounded-full bg-[#F43F5E]/12 text-[#F43F5E]"><IconAlertTriangle size={23} /></span><div><h2 id={titleId} className="text-[20px] font-semibold">{text.title}</h2><p className="text-[10px] text-[var(--text-secondary)]">{text.description}</p></div></div><div className="mt-[26px] h-[96px] rounded-[14px] border border-[#F43F5E]/30 bg-[#F43F5E]/7 p-[15px]"><strong className="text-[12px]">{goal.name}</strong><div className="mt-[13px] flex justify-between text-[10px] text-[var(--text-secondary)]"><span>{text.target} {money(goal.targetAmount)}</span><span>{text.saved} {money(goal.savedAmount)}</span><span>{formatGoalTargetDate(goal.targetDate, language)}</span></div></div><div className="mt-[108px] flex h-[44px] items-center justify-center rounded-[12px] border border-[#F43F5E]/20 bg-[#F43F5E]/5 text-[9px] text-[#F43F5E]">{text.warning}</div><div className="mt-[20px] flex justify-end gap-[10px]"><button type="button" onClick={onClose} className="h-[40px] w-[100px] rounded-[20px] border border-[var(--border-default)] bg-[var(--background-control)] text-[11px] font-semibold text-[var(--text-secondary)]">{text.cancel}</button><button type="button" onClick={onConfirm} className="h-[40px] w-[118px] rounded-[20px] bg-[#F43F5E] text-[11px] font-semibold text-white">{text.confirm}</button></div></section></div>;
}
